### ISSUE TITLE
Make the validation error message 'The data was invalid' customizable or clearer

### ISSUE THREAD

**Issue by SamuelFerracini** [statamic/ideas#1004]
It would be wonderful if we could modify the default error message for validation to provide more informative feedback. I have implemented a custom rule using regular expressions to identify invalid characters in the entry's content. However, when this rule fails, the message "The data was invalid" raised by Statamic but this does not adequately explain the issue. Thank you in advance.

**Comment by jasonvarga** [comment]
That's the validation message in general. You should also see an inline error message on the actual field itself which would provide more context.

![CleanShot 2023-06-20 at 09 46 28](https://github.com/statamic/ideas/assets/105211/3c7d119a-12b5-4d44-bf65-78da08fda8fc)
