### ISSUE TITLE
Toggle in listings

### ISSUE THREAD

**Issue by wm-simon** [statamic/ideas#101]
The possibility to toggle settings directly in listing, like in the collection overview would be great. Right now, there is just a "true", if it's activated. Alternatively would be a check-icon better, instead of the text "true".

**Comment by jasonvarga** [comment]
Can you elaborate? I don’t really know what you’re referring to. Maybe a screenshot?

**Comment by Pfeifakopf** [comment]
Sure...

Current listing:
![image](https://user-images.githubusercontent.com/3351449/76631256-aa243280-6541-11ea-8389-9176cc55ffec.png)
Setting in entry:
![image](https://user-images.githubusercontent.com/3351449/76631297-b9a37b80-6541-11ea-8ba1-6c583519e362.png)

Toggle or icons:
![toggle](https://user-images.githubusercontent.com/3351449/76631879-a7760d00-6542-11ea-9389-29d388550f01.jpg)
![toggle_2](https://user-images.githubusercontent.com/3351449/76631880-a80ea380-6542-11ea-8e1a-97b910a6d353.jpg)

**Comment by jasonvarga** [comment]
You want to be able to actually **change** the value from the listing? Or do you just want it to look nicer than `true`?

I would say the toggle implies you can change it, which wouldn't really be something we can do.

However the checkmark is nice.

**Comment by Pfeifakopf** [comment]
I would like to change the setting, but i thought, this perhaps could not be possible to do. That's way I thought, you can just show the icons instead of the true.

**Comment by zehfred** [comment]
This would be a really nice feature. It makes more sense from a UX point of view to show users a visual indicator instead of true/false.
