### ISSUE TITLE
Parent dropdown should have a "Please select" as default

### ISSUE THREAD

**Issue by maxi032** [statamic/ideas#1014]
When I edit a page, I can see in the right sidebar that there is a parent dropdown and over there, are the other pages that could be selected as parents of the current page.
When I first look at it, my impression is that the first value from the list (About us) is already selected, while in reality it is not like that. 
I think that this can be confusing for both developers and site owners.
Don't you think that by default there should be a 'Please select'? or please chose?

![pages-ui](https://github.com/statamic/ideas/assets/1525885/d33f5343-4f16-41e9-bba3-24fa024c9cde)

**Comment by jasonvarga** [comment]
The parent field will be populated with the parent entry in the structure. It's empty by default if you are creating an entry at the top level. e.g. this blue button:

![CleanShot 2023-07-10 at 11 11 15](https://github.com/statamic/ideas/assets/105211/048d7053-c25f-4ddb-81c4-69d5821965dd)
![CleanShot 2023-07-10 at 11 12 22](https://github.com/statamic/ideas/assets/105211/658753c5-02a3-42bd-b9a9-372f42e52e4f)


If you create the entry as a child of another page, it will fill it with that entry. e.g. this dropdown:

![CleanShot 2023-07-10 at 11 11 58](https://github.com/statamic/ideas/assets/105211/e40713b9-7c40-4cce-8715-32a1a8768414)

![CleanShot 2023-07-10 at 11 12 38](https://github.com/statamic/ideas/assets/105211/2341cbbd-85f3-4b13-a104-9c16573f7a0f)
