### ISSUE TITLE
GraphQL: add "site" argument to the entries query (in addition to singular entry)

### ISSUE THREAD

**Issue by fabiangigler** [statamic/ideas#1016]
The ability to filter the `entry` query by site handle in multisite / localized statamic sites was added 2 years ago in this PR by @jasonvarga, changing about 4 lines:
https://github.com/statamic/cms/pull/4055/files

However the `site` argument is still missing for the `entries` query, see here:
![GraphiQL screenshot](https://github.com/statamic/ideas/assets/3050232/d38fab47-5087-41a9-a200-e6d3336f5cec)

While the same result can be achieved via the filter argument and adding the site to the allowed filter configuration, direct support as an argument as well as symmetry between the queries would be nice.
From local testing the effort should not be much higher than in the PR above.

If you want me to open a PR, let me know.

**Comment by jasonvarga** [comment]
Happy to take a look at a PR. 👍
