### ISSUE TITLE
Adding fullscreen and ruler support to the code fieldtype

### ISSUE THREAD

**Issue by petemolinero** [statamic/ideas#1021]
If a site uses the code fieldtype extensively at all it can feel a bit small. Adding [the ability to fullscreen](https://codemirror.net/5/demo/fullscreen.html) it is a supported CodeMirror feature and is unobtrusive. I think it should be a great addition to core.

Also, if a developer is working in it, it can be nice to have rulers that indicate conventional line length limits (80 char soft limit, 120 char hard limit). I think it the code fieldtype could have an option to display or hide rulers, with hidden being the default setting. This feature is already [supported by CodeMirror as well](https://codemirror.net/5/demo/rulers.html).

I've already [developed a PR](https://github.com/statamic/cms/pull/8509) for this just to understand whether it was possible and how hard it would be.

**Comment by petemolinero** [comment]
![fullscreen-and-rulers](https://github.com/statamic/ideas/assets/1924752/83015186-31c0-4d6e-9b58-bfc4961c3f4e)

**Comment by duncanmcclean** [comment]
Closing since the related PR has been merged, https://github.com/statamic/cms/pull/8509.
