### ISSUE TITLE
Renaming an asset will not update references inside Replicator or Bard sets 

### ISSUE THREAD

**Issue by tobimori** [statamic/ideas#1044]

**Comment by j3ll3yfi5h** [comment]
Hey @tobimori 

This sounds like a issue for statamic/cms and not like an issue for statamic/ideas.

And it should be fixed:
https://github.com/statamic/cms/pull/8630

If not, please create an issue in statamic/cms and use the issue template for it.

**Comment by tobimori** [comment]
Oops, I didn't notice I was in the wrong repo. Sorry!
