### ISSUE TITLE
Customization of taxonomy permalink structure

### ISSUE THREAD

**Issue by godismyjudge95** [statamic/ideas#1054]
Would be nice to be able to customize the permalink structure for a taxonomy.

I found this useful when I want the taxonomy named with an internal nomenclature but need the public facing url to be something a little more user friendly.

**Comment by jasonvarga** [comment]
Duplicate of https://github.com/statamic/cms/issues/2403 and being worked on in https://github.com/statamic/cms/pull/8627

**Comment by godismyjudge95** [comment]
@jasonvarga sorry for the duplicates, I must have missed that in my search.  Also you guys are 🔥  getting my features/issues fixed before I get a chance to create a PR 😂
