### ISSUE TITLE
Warm static page cache on page save

### ISSUE THREAD

**Issue by JoeriE** [statamic/ideas#1061]
Hi,

I don't know if it's possible already but it would be nice if static page cache would be invalidated and warmed on page save / publish. 

Best wishes,
Joeri

**Comment by duncanmcclean** [comment]
This should be happening already. Are you using the queue at all?

**Comment by JoeriE** [comment]
@duncanmcclean Oh, I didn't know that. I haven't configured anything expect changing STATAMIC_STATIC_CACHING_STRATEGY to full and adding the rewrites to my htaccess.

**Comment by duncanmcclean** [comment]
No worries! I only asked since there's an outstanding bug when using the queue and static caching together so wanted to rule that out (statamic/cms#3291).

**Comment by JoeriE** [comment]
So do I need to set anything up to warm the cache after save? My queue connection is currently sync. It's invalidating the correct page(s), but it's not regenerating the page.

**Comment by duncanmcclean** [comment]
Apologies, mis-read your issue! Warming entries after clearing them isn't currently possible - there's an existing feature request for that: #977.

**Comment by ryanmitchell** [comment]
You can do this now using the `UrlInvalidated` event: https://github.com/statamic/cms/pull/8902

**Comment by duncanmcclean** [comment]
Closing in favour of #977.
