### ISSUE TITLE
Weglot integration

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/ideas#1079]
A client recently requested a Weglot integration for their new website. Unfortunately there is no such integration for Statamic available at the moment:
https://www.weglot.com/integrations

I have no idea, how much work this integration with Statamic would cost, as well as how many clients would use Weglot for their translations.

Please leave a "thumbs up" if you would also welcome such integration.

**Comment by AndreasSchantl** [comment]
I am pretty confident to say that such a third party integration won't make it into Statamic core. You could create your own addon for it and offer it to others.

**Comment by j3ll3yfi5h** [comment]
@AndreasSchantl is this Repo only for Core Features?

Maybe you're right, but how can we measure then, if features/addons are wished from other users too?

**Comment by AndreasSchantl** [comment]
It's the correct repo for that, and the thumbs up is used for measuring. But if you look at Statamic, there are no third party integrations whatsoever. That's why I wouldn't bet on a core integration of Weglot.

**Comment by j3ll3yfi5h** [comment]
I always thought about an addon and not about adding it to the core – makes totally sense.

**Comment by j3ll3yfi5h** [comment]
While having a deeper look on how Weglot works, i found out, that there is no need to develop a separate integration. It does all the magic with the general js integration: https://www.weglot.com/integrations/translate-website

> Compatible with any CMS and non-CMS technology

🤷🏼‍♂️
