### ISSUE TITLE
Extend Ray modifier for use of the color helper function

### ISSUE THREAD

**Issue by joschuba** [statamic/ideas#1083]
Would be really nice to be able to select the color in Ray when using the Ray core modifier. 

Plain PHP:
```php
ray('Hello world')->color('red');
```

Usage of the modifier like this:
```antlers
{{ hello_world | ray('red');
```

If you want to have it in core, would be happy to PR it in, should be a one liner. Just let me know.

**Comment by jackmcdade** [comment]
PR away!
