### ISSUE TITLE
CMS - Section nesting

### ISSUE THREAD

**Issue by nemmel2000** [statamic/ideas#1096]
I would like to add a section block in my CMS and add nested fields in this section for conditional showing and other implementations. At the moment we need to add these conditions to all the fields.

**Comment by ryanmitchell** [comment]
I think you should be able to do this with the new group field type:
https://statamic.dev/fieldtypes/group

**Comment by duncanmcclean** [comment]
Closing since you can do this with the Group fieldtype, like Ryan mentioned.
