### ISSUE TITLE
FR: able to configure the 'cancel' button in Configuration Modal

### ISSUE THREAD

**Issue by edalzell** [statamic/ideas#110]
Using `ConfirmationModal` for my Charge addon, in the CP, and I give folks the ability to cancel a subscription.

So this dialog has a `Cancel` and a `Cancel Subscription` button, which is not ideal.

Can you make the button configurable or are you open to a PR?

**Comment by edalzell** [comment]
<img width="625" alt="image" src="https://user-images.githubusercontent.com/6069653/77839926-5109f080-7136-11ea-876e-dd83fdeb3c4e.png">

**Comment by edalzell** [comment]
Or maybe make `ResourceDeleter` a bit more generic as I'm having to replicate much of its code?

**Comment by jackmcdade** [comment]
Your wish has been granted. You can now pass `cancel-text="Nevermind"` or whatever you need.
