### ISSUE TITLE
FR: Improve tree/list view toggles

### ISSUE THREAD

**Issue by mikemartin** [statamic/ideas#112]
When toggling between the structure Tree view and List view on a collection, the disabled state for the active view is not intuitive.
<img width="900" alt="Screen Shot 2020-04-01 at 10 44 42 am" src="https://user-images.githubusercontent.com/414211/78085180-ed1d4b80-7405-11ea-8ce1-493a028461c7.png">

I'd recommend highlighting the active view more prominently, so it's clear which view is selected.
<img width="987" alt="Screen Shot 2020-03-31 at 2 26 44 pm" src="https://user-images.githubusercontent.com/414211/78085345-69179380-7406-11ea-9c7e-702cdb989ad4.png">

**Comment by mikemartin** [comment]
Here's an overview for the MacOS **Segmented Controls** from Apple's Human Interface Guidelines:

<img width="771" alt="Screen Shot 2020-04-01 at 10 56 43 am" src="https://user-images.githubusercontent.com/414211/78085731-826d0f80-7407-11ea-9f9b-1a1af9cbfdbb.png">

https://developer.apple.com/design/human-interface-guidelines/macos/selectors/segmented-controls/

**Comment by mikemartin** [comment]
Explored a couple more treatments for the active state:

<img width="900" alt="Screen Shot 2020-04-01 at 10 58 48 am" src="https://user-images.githubusercontent.com/414211/78085835-d4159a00-7407-11ea-81e1-90afdb93a3ce.png">

<img width="891" alt="Screen Shot 2020-04-01 at 11 07 35 am" src="https://user-images.githubusercontent.com/414211/78086266-27d4b300-7409-11ea-951f-83afd5d5f6e8.png">

**Comment by mikemartin** [comment]
Alright, last one. 😂

This is using the `btn-flat` style that's used on the Assets listing.
<img width="878" alt="Screen Shot 2020-04-01 at 11 52 00 am" src="https://user-images.githubusercontent.com/414211/78088285-65d4d580-740f-11ea-9f9a-278ab8754d2b.png">

**Comment by jasonvarga** [comment]
If I had to choose, my preference would be this one:

![image](https://user-images.githubusercontent.com/105211/78143143-db36ab00-73fb-11ea-8bd0-3c6951164a93.png)

The Apple style one feels overpowering.

**Comment by mikemartin** [comment]
@jasonvarga I thought you'd like that one. Look familiar?

<img width="826" alt="Screen Shot 2020-03-31 at 2 13 55 pm" src="https://user-images.githubusercontent.com/414211/78144818-d87b9a80-747b-11ea-9b65-d686ddda3ba1.png">

**Comment by jackmcdade** [comment]
Thanks for all the ideas. Went with this:

![image](https://user-images.githubusercontent.com/44739/78197562-b5d58b80-7453-11ea-9974-a1a3fecbdf70.png)

**Comment by mikemartin** [comment]
@jackmcdade Looks awesome. Sorry to nitpick, but could you make the white button the same color as the disabled Save Changes button? It's a slight difference but I think it would help make it look less "active".

**Comment by jackmcdade** [comment]
That doesn’t makes sense to me. Why wouldn’t it be the same as any other clickable button?

**Comment by mikemartin** [comment]
@jackmcdade It's still not completely clear which button is selected. My suggestion was to make the other button less prominent. While you have the dark gray and the inner shadow, I still feel like there needs to be another visual cue.

![toggle_buttons-color_schemes](https://user-images.githubusercontent.com/414211/78222832-9c931480-7511-11ea-9cad-f864b1fe1919.png)

https://uxmovement.com/buttons/why-toggle-buttons-are-confusing/
