### ISSUE TITLE
Group fieldtype to allow for width constraints

### ISSUE THREAD

**Issue by johncarter-** [statamic/ideas#1131]
The group fieldtype would be great if you could apply widths to the sub-fields:

![image](https://github.com/statamic/ideas/assets/3776888/9c1425de-4766-45db-a9b0-4bace0644906)

**Comment by jasonvarga** [comment]
You can already apply widths to sub fields in the group fieldtype.

In your screenshot, you're using fieldsets. You can't apply widths to entire imported fieldsets. Single fields, sure.

If you define widths in the fieldset, they will be applied when imported into your group field too.
