### ISSUE TITLE
Allow Blueprint Sections to nest their data under a key

### ISSUE THREAD

**Issue by schwartzmj** [statamic/ideas#1142]
As an alternative to the "Group" field type, it would be nice to be able to allow an entire Blueprint Section / tab to have its own data key.

e.g. You have your standard "Main" Blueprint Section with its fields. These are top-level fields on the entry.

You then make a new Blueprint Section that has this feature enabled called `Stuff`, presumably with the key `stuff`.

You make a field within that Blueprint Section called `Things` that is accessed like: `stuff:things` instead of `things`.

**Comment by schwartzmj** [comment]
Or, another idea: all an option to remove styling for a "Group" field.

**Comment by duncanmcclean** [comment]
> Or another idea: allow an option to remove styling for a "Group" field.

This would probably be the easiest way to make this happen, since I imagine changing the way sections/tabs save data would be quite a lot of work.

Closing in favour of #1137.
