### ISSUE TITLE
Disable routing for taxonomies

### ISSUE THREAD

**Issue by bogaertmi** [statamic/ideas#1145]
Would it be possible to expose an option to disable the taxonomy routes.
Preferable with the option to still keep slugs, for usage with eg. indexing for search.

To be able to hide the “visit url” & “live preview” buttons in the taxonomy term in the CMS.

Currently have to overload the Statamic/Taxonomies/LocalizedTerm.php class for the function "route" to achieve this.

Thanks!

**Comment by ryanmitchell** [comment]
Seems like this could be easily done if/when https://github.com/statamic/cms/pull/8627 merges, then similar to collections when there are no routes these buttons disappear?

**Comment by duncanmcclean** [comment]
Closed by #10789, which'll be included in the next release.
