### ISSUE TITLE
Highlight that features aren’t working because of license issues

### ISSUE THREAD

**Issue by dave-smyth** [statamic/ideas#1148]
It would be helpful on the `/cp/utilities/git` page if Statamic could highlight when git isn’t pushing because of a license issue. I’ve experienced this on two occasions recently:

1. Prepping a server to go live and testing before the key is added
2. Upgrading a site from 3 to 4, testing the git and not realising the key hadn’t been updated

In both cases this involved a lot of troubleshooting. The experience would be greatly improved if the page highlighted that this feature won’t work until the license key is added (or renewed).

**Comment by duncanmcclean** [comment]
Whether you have a valid key in your `.env` file or not, as long as you have Pro enabled in `config/statamic/editions.php`, Pro features should be working.

**Comment by dave-smyth** [comment]
Huh!

In `2` (above), Git started working when the key was added, so I assumed there was a blocker in production...

**Comment by duncanmcclean** [comment]
Nope.

Maybe you had your config cached, which only got cleared by adding the license key?
