### ISSUE TITLE
Upgrade to Glide 3

### ISSUE THREAD

**Issue by jolora** [statamic/ideas#1157]
I'm trying out the v5 alpha by integrating into a new Laravel 11 project. Statamic cannot be installed into the project without removing Intervention as Glide 2.7 requests Intervention 2 (EOL) whereas Laravel 11 uses Intervention 3.

**Comment by duncanmcclean** [comment]
Unfortunately, it doesn't look like Glide 3 has been properly released yet, it's still in beta.

**Comment by jasonvarga** [comment]
> whereas Laravel 11 uses Intervention 3.

Laravel doesn't. Do you mean your app has manually required intervention?
