### ISSUE TITLE
Site events

### ISSUE THREAD

**Issue by SteveEdson** [statamic/ideas#1169]
In V5, when editing, adding or deleting a site, it would be good to fire an event, like Statamic does for other content types.

This way, we can hook into it to:

- clean up the content files which are left over when the site is deleted
- move the content files if the handle changes
- create some skeleton files for new sites

**Comment by Sennik** [comment]
I agree to this and I like to add a feature related to this: 

When creating a new site it would be nice to have the option to start with a copy of the content of an existing site. My translators prefer translating content by replacing it with their language and I personally like to start with structure/content when I am adding a new site to a multisite configuration.

**Comment by jackmcdade** [comment]
Closing this FR because we're already working on it here! https://github.com/statamic/cms/issues/10403
