### ISSUE TITLE
Allow for marking blueprints in custom namespaces as "Hidden"

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/ideas#1175]
On most blueprints, like those for collections & taxonomies, there's an option on the edit page to mark the blueprint as "Hidden".

![CleanShot 2024-06-06 at 16 36 16](https://github.com/statamic/ideas/assets/19637309/8887d9a0-efda-4f4c-9442-17a04dc22719)

However, the hidden toggle isn't shown for "custom namespaces" (eg. those registered with `Blueprint::addNamespace();`. 

In my case, with Runway, it would be nice to show this option since hiding a resource's blueprint now correlates to whether the "Create" button is displayed or not (ref: statamic-rad-pack/runway#508).

Just leaving this here as a reminder to come back to.

**Comment by mefenlon** [comment]
I have been using the hidden: true in my blueprints from #508. I have noticed that if the blueprint is editied in cp, the hidden: true line is removed.
