### ISSUE TITLE
Set STATAMIC_STACHE_WATCHER default to false in the config

### ISSUE THREAD

**Issue by de-raaf-media** [statamic/ideas#1178]
Please set STATAMIC_STACHE_WATCHER to false in the config by default. You can always set this to true in your .env file but this will make sure you don't accidentally set it to true on production. Took me a while to figure out why performance was slow.

Regards,
Mark

**Comment by jackmcdade** [comment]
Unfortunately we can’t do that — if we set it to false then everyone building sites for the first time will be confused by why their site doesn’t update when they’re making changes in the code.

**Comment by de-raaf-media** [comment]
Makes sense. Thanks for replying.
