### ISSUE TITLE
Display custom control panel logo as plain text instead of an image file

### ISSUE THREAD

**Issue by daun** [statamic/ideas#1185]
It would be great if there was an option to just display the site's name in plain text in the control panel, instead of linking an image file. Might just be via an env var: `STATAMIC_CUSTOM_LOGO_TEXT=Widgets Inc`. There's a few advantages I can think of:

- looks cleaner
- less bandwidth
- easier to match the typeface and font size of the control panel
- light/dark mode comes along for free
- less setup for new projects: just paste in the name

**Comment by daun** [comment]
Happy to create a PR if that's something you're willing to support in the future.

**Comment by jasonvarga** [comment]
This sounds like a nice idea to me. 👍

**Comment by jackmcdade** [comment]
Agreed. I'm in.
