### ISSUE TITLE
Add a way to disambiguate taxonomy tags from system tags in views

### ISSUE THREAD

**Issue by steveparks** [statamic/ideas#1195]
I created a taxonomy called 'Section', with the intention I could have paths like '/blog/section/{tag}'

Then, in my views I wanted to display the terms assigned to an entry on its view with {{ section }} <li>...</li> {{ /section }}.

This didn't work. 

In researching why, I found there is a Statamic system tag called {{ section }}, and this appears to create a conflict.

So I guess that taxonomies can't be named the same thing as any of the existing Statmic tags.

As section (and collection) are words that could often be used for taxonomies, it would be useful if there was a way of disambiguating between Statamic system tags and taxonomy tags in views.

At the moment in a view, % can be used to signify a tag, and $ for a variable. But the % doesn't distinguish between types of tag.

I suggest introducing an additional character, perhaps ^ to disambiguate Taxonomy tags in views. This will allow content designers and editors to name taxonomies anything they like, while enabling developers to build views that they know won't break.

**Comment by jasonvarga** [comment]
> But the % doesn't distinguish between types of tag.

What do you mean "types" of tags?

If you have a taxonomy named section, `{{ section }}` will still just be a variable. `{{ $section }}` should disambiguate it.

**Comment by steveparks** [comment]
The $ can be used to disambiguate the variable, but what would you use to disambiguate the taxonomy?

Eg how would you use this disambiguation to work with a taxonomy called 'section', such as:

```
<ul>
{{ section }}
 <li>{{ title}}
{{ /section }}
</ul>
```

**Comment by jasonvarga** [comment]
```
<ul>
{{ $section }}
 <li>{{ title}}
{{ /$section }}
</ul>
```

**Comment by steveparks** [comment]
ohhh I seeee - the taxonomy object _is_ just another variable?

I'd understood taxonomies were a special kind of tag. Ok, sorry, my bad. 

I'll close this, but I'll have a look if there's anything I can contribute to the docs page after learning from my confusion.

Thanks for clarifying for me.

**Comment by steveparks** [comment]
Ok, I submitted a PR to add a sentence in two places in the docs to explain this to newbs like me.
[#1434](https://github.com/statamic/docs/pull/1434)
