### ISSUE TITLE
White Labeling Business Theme Dark Mode

### ISSUE THREAD

**Issue by jason-beach** [statamic/ideas#1196]
Would be nice to be able to update the conic gradient (background color) on the dark version of the business theme. For example, to add 'bg-blue-500' and the conic gradient would be a blue instead of the default to match brand.

![CleanShot 2024-07-09 at 16 45 57@2x](https://github.com/statamic/ideas/assets/11856709/bc5301d6-a779-4e27-ae57-ac4065c8243b)

Thanks

**Comment by andjsch** [comment]
You can already to this by overriding that specific class using a custom stylesheet. 
https://statamic.dev/white-labeling#custom-css

**Comment by duncanmcclean** [comment]
Using a custom spreadsheet is the easiest way to customize this (or any other CSS in the Control Panel).

**Comment by jason-beach** [comment]
@duncanmcclean , thanks - I did consider this and will work just fine.
