### ISSUE TITLE
Using modifiers in title_format

### ISSUE THREAD

**Issue by Paperweb** [statamic/ideas#1210]
Hi there, 

_I'm a new user of Statamic, and really enjoy it so far.
Thanks for this awesome tool !_

**Issue**

I tried to use a modifier in my title_format, like so :

`{ first_name } { last_name | truncate(1, '.') }`

and it doesn't seem to be parsed properly, as i get :

`John { last_name | truncate(1, '.') }`

Is that a lack of feature, or a bug ?

Generally, i find that using logic and operators in title_format could be useful. 

Thank you !

PW

**Comment by andjsch** [comment]
Hey!
A GH issue is not the right place for support requests. Please head over to the [discord](https://statamic.com/discord) or to the [GH discussions](https://github.com/statamic/cms/discussions/4254).

Other than that: Looks like you aren't using double curly braces. Try this: ``{{ first_name }} {{ last_name | truncate(1, '.') }}``
Also, check out the ``at`` modifier: ``{{ last_name | at:0 }}``

Sometimes, there's also some weird whitespace added by editors. Try removing the spaces between the curly braces like so `` {{first_name}}``. You can readd them after that.

Docs: https://statamic.dev/modifiers/truncate
Antlers templating in general: https://statamic.dev/antlers

**Comment by Paperweb** [comment]
Thank you ! 
Adding another couple mustaches did the trick. 
It's strange, because i thought i tried that. Sorry for the derangement.

The [docs](https://statamic.dev/collections#titles) should maybe be updated with double braces.

I'll remember the Discord for other similar issues.

Cheers !

---

EDIT :

I even got to make work exactly what i wanted, which is to add the last name's initial only when the first name is also someone else's (which is specified with an `homonym` toggle field in the collection entry blueprint) : 

`{{ first_name }} {{ homonym ?= ( last_name | truncate(2, ".") ) }}`

Statamic is awesome :pray: :clap:

**Comment by duncanmcclean** [comment]
Glad to hear you managed to get it sorted! Feel free to contribute to the docs if you feel it could be made clearer.
