### ISSUE TITLE
Dictionary Tag to loop over all its items (like taxonomy tags)

### ISSUE THREAD

**Issue by JorisOrangeStudio** [statamic/ideas#1214]
Would love to see a tag to loop over all the possible dictionary items (augmented), like the [taxonomy tag](https://statamic.dev/tags/taxonomy#example):

```html
{{ dictionary type="file" from="dictionary.json" }}
    <li>{{ key }} - {{ value }}</li>
{{ /dictionary }}
```

This way you can use the Dictionary data outside of a Entry's scope, for example to populate dropdowns in a filter. 

~~This is already possible to the pre-made Dictionaries like [countries](https://statamic.dev/fieldtypes/dictionary#countries), but not for the File & Custom dictionaries.~~ 
Seems like it is not possible outside a Entry's scope (without `countries` field handle available)

**Comment by duncanmcclean** [comment]
Good idea!
