### ISSUE TITLE
View other users {collection} entries

### ISSUE THREAD

**Issue by de-raaf-media** [statamic/ideas#1220]
I did a quick search but I don't think this feature request exists yet. In my Statamic project I have multiple users. I don't want to **show** my users entries that they cannot edit (other authors entries). But there does not seem to be a rule for this. Is there a reason for this?

Is it possible to add a rule for this? Or can I somehow achieve this myself?

Currently these rules are available for other authors entries.

'edit_other_authors_{collection}_entries' => "Edit other authors' entries",
'publish_other_authors_{collection}_entries' => "Manage publish state of other authors' entries",
'delete_other_authors_{collection}_entries' => "Delete other authors' entries",

I would very much like a new rule:
**'view_other_authors_{collection}_entries' => "View other authors' entries",**

Regards,
Mark

**Comment by jasonvarga** [comment]
You can hook into the query used for listings.

https://statamic.dev/extending/hooks#entry-index-query-query

See https://github.com/statamic/cms/pull/10479

```php
use Statamic\Hooks\CP\EntriesIndexQuery;

EntriesIndexQuery::hook('query', function ($payload, $next) {
    $payload->query->where('author', User::current()->id());

    return $next($payload);
});
```

**Comment by de-raaf-media** [comment]
Thanks, that is certainly a pointer in the right direction to achieve this. My feature request is that it would be nice if this becomes part of the existing Statamic EntryPolicy.php. 

It would be nice to have this available by default :-)

**Comment by de-raaf-media** [comment]
Thanks @jasonvarga, that actually helped me a lot!

My feature request remains. It would be nice to have this permission available by default :-)
