### ISSUE TITLE
When re-naming assets, have an option to pre-populate filename field rather than using a placeholder

### ISSUE THREAD

**Issue by mattmultiplied** [statamic/ideas#1225]
Currently when re-naming assets, it sets the placeholder with the original filename although there's no way to populate the value of the field with the filename.

<img width="637" alt="Screenshot 2024-09-13 at 16 34 44" src="https://github.com/user-attachments/assets/9e7b5d67-96be-49fe-87ab-7d5587d8a6ee">

It would be good to have the option to populate this field with the original filename. This would be incredibly valuable if you have multiple files to rename due to a repeated spelling mistake, or something similar.

To throw some ideas out of how it could work:

- Have a separate button for 'Amend filename' which pre-populates the field rather than as a placeholder.
- An option in the configuration to choose where it pre-populates the field on renaming files.
- A button or a key press such as tab which fills the field in on press.

**Comment by daun** [comment]
This would be super helpful! I think populating the input with the current name **and also selecting it** would be a great default — easy to modify the current name, and just as easy to delete the whole thing and start over.

**Comment by duncanmcclean** [comment]
Closed by statamic/cms#10941
