### ISSUE TITLE
Antlers mode for code fieldtype

### ISSUE THREAD

**Issue by tobiaseichert** [statamic/ideas#123]
I am in the process of creating some blog posts on working with Statamic. For this reason, I'd like to present some Antlers code like you do on statamic.dev.

However, you cannot select Antlers as the language for syntax highlighting in the Code fieldtype. Is this just missing right now or is there a better alternative to implement this?

Also, is there a way to make the code field appear on the frontend the same way as it appears in your form without manual HTML/CSS customisation?

<img width="743" alt="Screenshot 2020-03-04 at 15 52 21" src="https://user-images.githubusercontent.com/29119234/75891538-32af1e80-5e30-11ea-84dc-cafdd15f06b2.png">

**Comment by petemolinero** [comment]
@jasonvarga @jackmcdade Hi folks! Looks like this issue was labeled as "added", but I'm still not seeing it as [an option in the docs](https://statamic.dev/fieldtypes/code#options). Is it possible to do Antlers syntax highlighting in the code field currently?

**Comment by jasonvarga** [comment]
Not sure what the added label means honestly but no there's not currently an Antlers option. `handlebars` is pretty close though.

**Comment by petemolinero** [comment]
@jasonvarga Sounds good, thanks!
