### ISSUE TITLE
Don't show update notification if current version is greater than "latest"

### ISSUE THREAD

**Issue by finnjsmith** [statamic/ideas#1237]
I usually update all my dependencies via CLI, using composer and npm. This sometimes ends up bumping the latest stable version of a package to a version which is greater than the one suggested in the "updates" section of the control panel, see here with the Eloquent Driver package: ![Screenshot 2024-10-11 at 08 33 39](https://github.com/user-attachments/assets/cc0cf18e-98a7-4bc2-b2ca-5a39df393ff5)

I am proposing that the control panel notification should only show up if the current version of the package is < the most recent version shown in the control panel, rather than just the != which is how it works currently.

**Comment by duncanmcclean** [comment]
There should never really be a situaton where you have a newer version installed than we have listed on the changelog. It's a known issue at the moment, see statamic/cms#10277.

**Comment by efc** [comment]
There "should" never be, but that is clearly not always the case. Infrastructure does sometimes have problems. I think a sanity check like this would be helpful. For example, couldn't this also happen if someone is developing an addon and has a more recent "version" installed locally than statamic.com knows about in the changelog? If Statamic could sense that a greater version number is installed than is evident on the changelog, maybe it could suppress the update badge but include some indication (like a caution badge) in the updates list?
