### ISSUE TITLE
User switch for the frontend

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/ideas#126]
The possibility to switch between different users in the frontend, to check the shown contents would be really nice, for example by adding a button in the backend, to "open site as username".

**Comment by jasonvarga** [comment]
Not really a core feature. However this exists as an add on for v2. https://statamic.com/marketplace/addons/impersonator

I’m sure it will be updated for v3 at some point.

**Comment by jackmcdade** [comment]
There's a v3 version too, check it out: https://github.com/aryehraber/statamic-impersonator/tree/statamic-3

**Comment by Pfeifakopf** [comment]
Thank you, it works perfectly!

**Comment by jasonvarga** [comment]
Of course there is. I shouldn't have doubted you, @aryehraber
