### ISSUE TITLE
Statamic requests per second (slow benchmark)

### ISSUE THREAD

**Issue by vitalijalbu** [statamic/ideas#1268]
Hi guys, I just saw this interesting article about different PHP versions benchmarks.
Statamic cms seems slower than craftcms, is that correct?
Anyone ever did a request per second performance comparison??

https://kinsta.com/blog/php-benchmarks/

![IMG_5448](https://github.com/user-attachments/assets/c4151ca8-e2fe-424d-b06a-ce5794348578)

**Comment by vitalijalbu** [comment]
What do you think about ?

**Comment by duncanmcclean** [comment]
The benchmarks were made with developer mode active, which naturally makes things slow. 

When you're running Statamic in production, things will often be much faster, which makes it misleading.

They even mentioned in the post:

![image](https://github.com/user-attachments/assets/af95c39c-57d1-4183-8d9a-64e717d3e4bc)

We've complained about it in the past to no avail: https://x.com/jackmcdade/status/1760307373078372373?s=46&t=NUuEhrB3yxALCBq7Nej9Kg

**Comment by vitalijalbu** [comment]
Anyone with a good heart and time could do a stress test to see how many requests it handles?😁💪

**Comment by andjsch** [comment]
> Anyone with a good heart and time could do a stress test to see how many requests it handles?😁💪

There's multiple huge sites out there that use Statamic. The most recent one is TV2 with a fairly stock Statamic installation with quite a lot custom addons. There's performance metrics available within [Discord](https://discord.com/channels/489818810157891584/489864118719873024/1253414158813106197). Hope that answers your question.
