### ISSUE TITLE
Fetching different sizes of image via Content API

### ISSUE THREAD

**Issue by philsturgeon** [statamic/ideas#127]
This is starting off as a question, which might be a suggestion for more docs, or a feature request, I'm not sure, buuut: can API consumers talking to the Content API request a different size of image? 

<img width="863" alt="Screen Shot 2020-04-06 at 13 19 01" src="https://user-images.githubusercontent.com/67381/78557831-6dc6b800-7809-11ea-8bdc-5c00779f550e.png">

I know Glide is being used and this seems relevant to that. Maybe calling the image api_url could accept some width & height parameters? This would be roughly equivalent to the [gatsby image plugin](https://www.gatsbyjs.org/packages/gatsby-image/#how-to-use) where you can request whatever size you need and even control the crop approach too.

**Comment by goellner** [comment]
We use [imgix](https://www.imgix.com/) for that in our projects. This way we are only using the path of the image and can output whatever image size we want. Plus its much faster than glide and it gets cached automatically. This does take a lot of strain from the server too.

**Comment by jasonvarga** [comment]
Closing this since it's doable in GraphQL https://statamic.dev/graphql#custom-fields
