### ISSUE TITLE
Do not infer use of broadcasting based on provider registration.

### ISSUE THREAD

**Issue by geertjanknapen1** [statamic/ideas#1285]
So I was creating a simple widget that uses jQuery under the hood to post to an endpoint to fetch new data for a graph.

But the following jQuery always resulted in the error below it.
```js
$.post(window.datasetRoute, { year: year })
```

```shell
Uncaught TypeError: Cannot read properties of undefined (reading 'socketId')
    at M.value (app-bc6ae7f0.js:14:19994)
    at app-bc6ae7f0.js:14:20816
    at Function.<anonymous> (jquery.js:2:72498)
    at Function.each (jquery.js:2:3129)
    at l (jquery.js:2:72464)
    at Vt (jquery.js:2:72601)
    at Function.ajax (jquery.js:2:74869)
    at ce.<computed> [as post] (jquery.js:2:78232)
    at HTMLSelectElement.<anonymous> (failed-jobs-statistics.js:6:25)
    at HTMLSelectElement.dispatch (jquery.js:2:40035)
```

After some digging, and [a little hint from Erin in Discord](https://discord.com/channels/489818810157891584/1318226017612992522), I found out that Statamic enabled broadcasting based on if the `BroadcastServiceProvider` is registered.

```php
// \Statamic\src\Providers\BroadcastServiceProvider.php:51
protected function enabled()
{
    return in_array(
        \Illuminate\Broadcasting\BroadcastServiceProvider::class,
        array_keys($this->app->getLoadedProviders())
    );
}
```

However, because we just upgraded to Laravel 11 (in a new project), the providers all got registered automatically. So without us noticing, Statamic assumed we were using broadcasting when we were not.

I think it makes more sense to let the user explicitly decide if broadcasting should be enabled, rather than inferring it based on whether a provider is or isn't registered or it should be documented somewhere that Statamic infers the use of broadcasting based on the providers registration.

**Comment by duncanmcclean** [comment]
Do you have a `routes/channels.php` file?

**Comment by geertjanknapen1** [comment]
Hey Duncan, I do, but that's also the default one. It does not really contain any code.

```php
<?php

use Illuminate\Support\Facades\Broadcast;

/*
|--------------------------------------------------------------------------
| Broadcast Channels
|--------------------------------------------------------------------------
|
| Here you may register all of the event broadcasting channels that your
| application supports. The given channel authorization callbacks are
| used to check if an authenticated user can listen to the channel.
|
*/

// Broadcast::channel('App.Models.User.{id}', function ($user, $id) {
//     return (int) $user->id === (int) $id;
// });
```

**Comment by duncanmcclean** [comment]
That's strange... 

Laravel 11 [doesn't come](https://github.com/laravel/laravel/tree/11.x/routes) with a `channels.php` routes file out of the box. It's only be created when you run `php artisan broadcasting:install` - that's what loads Laravel's `BroadcastServiceProvider`.

If you upgraded from a Laravel 10 application (eg. you're using the "old" app skeleton), you'll always have the `channels.php` routes file but you'll have to manually enable the `BroadcastServiceProvider` in your `config/app.php` file.

I'm not sure how you ended up with it with a fresh Laravel app. You might be able to just get rid of it.

**Comment by geertjanknapen1** [comment]
Right that does make sense, I didn't set up the new project, just took over from a colleague, so that might be why.
