### ISSUE TITLE
Actions on Collection

### ISSUE THREAD

**Issue by buffalom** [statamic/ideas#131]
Hi guys,

It would be pretty cool to have a way to create actions for collections.
I imagine those to create buttons where the "Create Entry" button is and to execute a function just like they do now but without specific items and instead just a collection. Inside of this function you could then select whatever items you need for this action.

A usecase for this could be to export all items from a collection or to perform an action on a specific set of items (eg. all entries with a specific toggle set) without having to select them individually.

Currently you cannot execute an action on more than 100 items anyway because the pagination does not allow selecting items from several pages. That's kind of a bummer.

A possible advanced version of this feature would be to allow these actions to be executed on a certain filter only. This would give the user more control on what items to execute the action on by allowing him to set any filter and execute the action on its items.

**Comment by edalzell** [comment]
Thinking about this one, my thoughts:

* first pass at this would be simple actions. They'd go here: 
<img width="242" alt="image" src="https://github.com/user-attachments/assets/fcf4800b-431a-4bc0-aa22-74f4c2fdc859">

* you'd register them the same was as other actions, but these are a new "type"
* scope them similarly, with `visibleTo`
* no other UI right now
* action would get name of the "resource" (i.e. the collection name, taxonomy name, `users`, runway resource, etc)
