### ISSUE TITLE
Ability to attach Blueprints into Navigation objects

### ISSUE THREAD

**Issue by sebabal** [statamic/ideas#135]
It would be handy to have the ability to attach blueprints to the Navigation items that way we could add metadata to the elements.

**Comment by jesseleite** [comment]
Just a note that you can already define [entry_link blueprints](https://statamic.dev/collections#entry-link-blueprint) for structured collection links, but not yet for structured navigation links.

**Comment by iamparagon** [comment]
Up doot on this one. Would be great to add options for classes and option for opening in a new tab.

**Comment by dannyuk1982** [comment]
+1 for this, seems essential for most navs in order to be able to open in new tabs or add rel="nofollow"

**Comment by jasonvarga** [comment]
Closing in favor of #175 which has more 👍 's.
