### ISSUE TITLE
Glide use resources/images folder

### ISSUE THREAD

**Issue by dwainscheeren** [statamic/ideas#137]
Make it possible to load images from the `resources/images` folder inside a project.
`{{ glide src="/resources/images/image.jpg" }}`

**Comment by ncla** [comment]
You could copy the directory to public with Laravel Mix `mix.copy('resources/images/', 'public/images');`, from there Glide tag can access images.

**Comment by jackmcdade** [comment]
If you made that directory an Asset Container you should be able to access it no problem.
