### ISSUE TITLE
FR: HTML Comments to Indicate Partials, Layouts & Templates

### ISSUE THREAD

**Issue by jcohlmeyer** [statamic/ideas#139]
One thing I miss from working with Drupal was the ability to turn on a debug/dev feature that added HTML comments around the output of different PHP files.

In Statamic I think it could be nice to have an option in development to put HTML comments at the beginning and end of each partial, view and layout. That way when you are trying to figure out what partial prints the code you are looking at in your browser you can easily trace it back to the appropriate antlers file.

In the meantime here is a simple partial that I used to demonstrate the idea in antlers, but this could be quite repetitive and error-prone to manually do in every file.

```
{{ if environment == 'local' }}
  <!-- Start Partial: resources/views/partials/_long_text.antlers.html -->
{{ /if }}

{{ long_text | markdown }}

{{ if environment == 'local' }}
  <!-- End Partial: resources/views/partials/_long_text.antlers.html -->
{{ /if }}
```

**Comment by jcohlmeyer** [comment]
Discord Discussion: https://discordapp.com/channels/489818810157891584/489825364902805505/698970789994561546

**Comment by jasonvarga** [comment]
This might be a useful feature for the Laravel community in general.

I might take a shot at turning this into a standalone package.

**Comment by jasonvarga** [comment]
Here you go: https://github.com/pixelfear/laravel-view-debug 😘

**Comment by jcohlmeyer** [comment]
Amazing, thank you!
