### ISSUE TITLE
Show user blueprint, when making new user

### ISSUE THREAD

**Issue by wm-simon** [statamic/ideas#142]
When you add an user with the cp, you have to open the user and edit the contents from the blueprint. To show the blueprint, for example as last step, would make the adding faster.

**Comment by jackmcdade** [comment]
The idea was for the user to be able to update their own info after logging in, thus making it faster to create users. Adding the blueprint would make it slower...

**Comment by Pfeifakopf** [comment]
Ah, ok. In my case I'm adding workers of a company, categorize them into groups and add contact infos, etc. They will never login themselves...

**Comment by jasonvarga** [comment]
This request is a bit unclear and needs more details. Feel free to update it.
