### ISSUE TITLE
User listing customizable

### ISSUE THREAD

**Issue by wm-simon** [statamic/ideas#146]
The columns should be customizable by the blueprint, like collections.

**Comment by edalzell** [comment]
Our use case is that we use `first_name` and `last_name` and now can't see those in the listing.

**Comment by aerni** [comment]
> Our use case is that we use `first_name` and `last_name` and now can't see those in the listing.

Same here. Also the default `name` stays in the listing even though I removed the field from the user blueprint.

**Comment by duncanmcclean** [comment]
This seems to be possible now. You can customise the displayed columns on the Users Listing in the same way you can with the collections listing table.
