### ISSUE TITLE
A Loop tag in core?

### ISSUE THREAD

**Issue by damcclean** [statamic/ideas#147]
I've found this [little addon for v2](https://github.com/lesaff/Statamic-Loop) which adds a `loop` tag to Statamic. I think it would be a nice tag to add into core.

## Use cases
For example, the use case I had was I wanted to create a select element for the user to pick what quantity of item they wanted to add to their cart. I also wanted the backend user to pick a maximum amount of the item that a customer could add.

```
<select name="quantity">
   {{ loop from='1' :to='max_quantity' }}
      <option value="{{ value }}">{{ value }}</option>
   {{ /loop }}
</select>
```

I could also see this tag coming in useful if you're wanting to build a selector for birth years or something like that, where you could just do:

```
<select name="birth_year">
   {{ loop from='1900' to='2020' }}
      <option value="{{ value }}">{{ value }}</option>
   {{ /loop }}
</select>
```

**Comment by jasonvarga** [comment]
Useful. I think it should be called `range` though, and copy the PHP `range()` method behavior.

**Comment by damcclean** [comment]
Sounds good. If you think it's something you'd like in core, do you mind if I try and create a pull request to bring it in?

**Comment by jasonvarga** [comment]
Go for it!
