### ISSUE TITLE
Be able to access the unaugmented data

### ISSUE THREAD

**Issue by edalzell** [statamic/ideas#148]
Scenario, I have a bard field w/ no sets and it may have images in it.

I'd like to "do stuff" with the images (add classes, lightbox hooks etc).

The data is in there: 
<img width="496" alt="image" src="https://user-images.githubusercontent.com/6069653/79671605-795a9d00-8180-11ea-9e09-de46722a3dfa.png">

Maybe a `field_raw` that doesn't augment?

**Comment by jasonvarga** [comment]
{{ field | raw }}

**Comment by edalzell** [comment]
That's not in CoreModifiers, is it hidden somewhere else?

**Comment by edalzell** [comment]
And it doesn't seem to work : 
<img width="266" alt="image" src="https://user-images.githubusercontent.com/6069653/79674095-deb88900-8194-11ea-9dee-7fb1bbf5344d.png">

<img width="595" alt="image" src="https://user-images.githubusercontent.com/6069653/79674112-06a7ec80-8195-11ea-8a97-5aa74f2758e2.png">

**Comment by jasonvarga** [comment]
It’s an array though.  Loop over it.

{{ field raw=“true” }} {{ /field }}

**Comment by edalzell** [comment]
lol I was using it on the wrong field. Sheesh.
