### ISSUE TITLE
Add modal to save if you try to navigate away and have unsaved changes

### ISSUE THREAD

**Issue by jmartsch** [statamic/ideas#150]
Right now if I have an unsaved page and click on a navigation item, or navigate to another URL, a JS alert is triggered, which only states, that unsaved changes my not be saved.

It would be a good addition to add a modal on page unload event:
"Do you want to save your changes before leaving?" with options "Yes" or "No".
If you choose "Yes" the changes would be saved and then the user would be redirected and a "Saved" message should appear.
If he chooses "No" he is instantly redirected.

**Comment by jackmcdade** [comment]
I would love to support this but it's nearly impossible, unfortunately.
