### ISSUE TITLE
Use declarative buttons instead of rotating dots menu icon

### ISSUE THREAD

**Issue by jmartsch** [statamic/ideas#152]
As we all know ;) and stated in many articles (for reference [this one](https://uxplanet.org/the-ultimate-guide-to-the-hamburger-menu-and-its-alternatives-e2da8dc7f1db): 
The hamburger menu is not so good UX and there could be better alternatives. 

A declarative button for the actions would be much better.

Here is a quick mockup which is an improvement:
![msedge_2020-04-22_21-06-14](https://user-images.githubusercontent.com/551551/80024375-3cbfd600-84df-11ea-9ba7-865b74617b08.png)

Maybe it is even better to reduce the actions to only one button which is labeled "Actions" and there you have all actions combined, like
- Edit collection
- Scaffold resources
- Create entry
  - Page
  - Article

Maybe they can be differentiatet them with something like opt-groups.

**Comment by jasonvarga** [comment]
What do you suggest for the buttons on the right of each row in the table?

**Comment by jackmcdade** [comment]
We've had this pattern for almost 5 years. Google uses it, Shopify uses it, a number of other huge platforms use it as well. I know there are a lot of people who write about how bad of a pattern "hamburger" icons are, but no one is confused about them anymore. They're very ingrained into most people's typical day to day.

**Comment by jmartsch** [comment]
Even though many companies use the hamburger menu frequently, and it is now accepted or known by many people, it does not automatically make it right or intuitive. 

What is hidden behind the ominous 3 points/strokes? There is no indicator what appears when you click on the icon. 

If you want to use the hamburger menu, you should at least write a label for it like "more", "more actions", "menu", "navigation" etc. 

This tells the user directly what is hidden behind the icon.

Why not use a secondary button with a dropdown? What are the cons?

**Comment by jmartsch** [comment]
Feel free, to close this discussion, if you like, but I would like to hear your opinions on my arguments :)

**Comment by jackmcdade** [comment]
There are a few reasons I'm 100% fine with this. I'm a big proponent of clarity in design, using text labels over icons everywhere possible, but these twirldown "more actions" help us in a number of ways. And just to be clear, I'm referring to the one next to the publish/save buttons, and all the others in table rows, like entry/asset lists.

1. Addon developers can hook into the list of links inside and add their own actions. Not knowing what might be in the list means writing a generic label that can be translated into 20 languages accurately is a little tricky.

2. Space is very valuable. There are a lot of things can _can_ show in that button area and in a table row and eating up 140px for a full button with label can have an adverse affect. If you want to show more than 4 columns in a listing, seeing the word "Actions" over and over in each row adds distracting visual noise for an affordance of secondary importance.

<img width="1055" alt="Screen Shot 2020-04-23 at 10 17 24 AM" src="https://user-images.githubusercontent.com/44739/80109618-ae356e00-854b-11ea-8015-917a7f334ae5.png">

Next to publish/save buttons you lose that space used for the entry title causing line wrapping sooner and causing a more awkward UI more of the time.

<img width="1053" alt="Screen Shot 2020-04-23 at 10 19 49 AM" src="https://user-images.githubusercontent.com/44739/80109931-1edc8a80-854c-11ea-9ff7-248b0f19f5f2.png">

In German many labels are quite a bit longer than English (as you well know) and space gets eaten up even more quickly.

3. Hiding "more actions" behind a commonly used icon isn't much more vague than the words "more actions" themselves. Either way you don't know what's going to be behind them. But once you've clicked them **once**, you'll see that it reveals extra, contextual controls. And once you've seen that, you learn that extra contextual controls are available everywhere you see that icon.

**Comment by jmartsch** [comment]
I absolutely understand your points. Thank you for your explanation.
