### ISSUE TITLE
Easy way to change positioning of Control Panel navigation

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/ideas#153]
I'd like to be able to move my `Simple Commerce` nav section to be positioned under the `Content` section.

The only way I'd be able to do this right now is to merge the items inside my section into the content one, which isn't ideal.

Attached a screenshot for some context
![image](https://user-images.githubusercontent.com/19637309/80037719-0ccaff80-84ec-11ea-9f13-81cd4c7f6a29.png)

**Comment by sjclark** [comment]
@duncanmcclean did you ever find a workaround for this?

**Comment by duncanmcclean** [comment]
> @duncanmcclean did you ever find a workaround for this?

No, I haven't. I've just put up with it.

**Comment by jasonvarga** [comment]
Will be included in the new nav builder in 3.4. https://github.com/statamic/cms/pull/6678
