### ISSUE TITLE
CP: Navigation in collections confusing

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/ideas#154]
When ordered collections are used for the navigation, there is no need for a navigation menu additionally. But the users will still open the navigation section, to look for pages entries. So it would be really helpful, if you could pin ordered collections directly to the navigation section, like:
- Navigation
  - Pages

**Comment by jasonvarga** [comment]
If you don't have any other navigations, give your clients a role that limits access to the navigation section. Then they just wont see it at all.
