### ISSUE TITLE
maxlength attribute for <text> and <textarea>

### ISSUE THREAD

**Issue by WiebkeVog** [statamic/ideas#155]
If the limit is exceeded, it should not be possible to add more text. Can you add the maxlength attribute to the Text-Fieldtype and Textarea-Fieldtype?

Maybe it makes sense to include the property `maxlength` in the configuration, so that your limit functionality isn't broken?

**Comment by jackmcdade** [comment]
I purposely didn’t support this so that you have the opportunity the edit your text to fit into the amount of space, just like the way Twitter does. A hard limit would force you to write elsewhere and paste and check, and that workflow is really annoying.

**Comment by jasonvarga** [comment]
You can add max:somenumber validation rules too.
