### ISSUE TITLE
'Learn more about' bubbles should have custom classes

### ISSUE THREAD

**Issue by JonKaric** [statamic/ideas#157]
It would be really useful for the new 'Learn more about...' bubbles to have their own classes, something like:

`class="help help-collections"`

This would enable us to either:
- Hide the messages (Clients using the control panel won't find them useful in my case)
- Manipulate the messages (Show a custom message, eg a link to a custom help guide)

**Comment by jasonvarga** [comment]
You can add `'link_to_docs' => false,` to `config/statamic/cp.php`

Looks we forgot to update statamic/statamic when we added those. We'll get on that.
