### ISSUE TITLE
Headless support for Live Preview (and the Visit URL button)

### ISSUE THREAD

**Issue by igregson** [statamic/ideas#161]
Feature request: Allow easy customization of the text and behavior of these buttons:

![image](https://user-images.githubusercontent.com/2054975/80744374-69718000-8ad3-11ea-9b28-6b03352c3921.png)

Our usecase: We're planning to use Statamic 3 as a 100% headless CMS. This means that we _really_ need to be able to customize these buttons. Specifically, we'd like to change the "Live preview" button to simply read "Preview" and for it to link to a specific URL (something like `https://our-custom-preview-domain/[entry-slug]`). And we'd also like to change the root URL for the "Visit URL" button.

Relevant discussion to this was had in [CMS PR 1624](https://github.com/statamic/cms/pull/1624).

**Comment by Buffalom** [comment]
To get the "Visit URL" button to point to your frontend already you can set the sites url in `config/sites.php` to the one of your frontend.

**Comment by igregson** [comment]
Thanks @Buffalom. That's helpful in the interim. 

I'm seeing that the the path to `sites.php` should be `config/statamic/sites.php`. Confusingly, this is the path listed in the docs ([here](https://statamic.dev/configuration#config-files)) but not the one that's seen if looking directly at the repo ([here](https://github.com/statamic/cms/tree/master/config)).

**Comment by jasonvarga** [comment]
It should be config/statamic/sites.php

The directory in the repo you linked to will be ends up being config/statamic

**Comment by GioChocolateBro** [comment]
Sorry for the duplicate issue.

I might not have a full picture of the situation. 
But an SPA using the statamic content api would also need a "preview" function besides the external url right?
Or could we get here with the [current extension possibilities](https://statamic.dev/extending/live-preview) of live preview

**Comment by jasonvarga** [comment]
I see this issue as "just make live preview work for headless situations please".  😄

**Comment by jasonvarga** [comment]
Headless live preview is in 3.3 beta.

**Comment by Buffalom** [comment]
Looks amazing, thanks @jasonvarga
