### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by dwainscheeren** [statamic/ideas#162]
There is currently no sitemap and it's the basic of a CMS so I should really consider making a sitemap default in statamic.

**Comment by damcclean** [comment]
Like you said, there's no sitemap functionality in core but [SEO Pro](https://statamic.com/addons/statamic/seo-pro), the first party SEO addon for Statamic supports generating sitemaps.

You can alternatively create a sitemap yourself by creating a custom route with a template that just contains the sitemap XML.

In your `routes/web.php` file, you'd do something like this:

```
Route::statamic('/sitemap', 'sitemap-template', ['layout' => '', 'content_type' => 'xml']);
```

And then in your `sitemap-template` you'd add whatever you need to create a sitemap.
