### ISSUE TITLE
Allow the REST API to identify Entries by Slug

### ISSUE THREAD

**Issue by Buffalom** [statamic/ideas#164]
I often use statamic headless with a nuxt frontend application.
The only problem I have with the Content API so far is the identification of an entry by its id.
This is a dealbreaker since I do not want the route in my frontend to contain an awful id but without it I cannot fetch the entry from the cms.
What is the slug there for, if not to identify the resource?

[Discarded PR](https://github.com/statamic/cms/pull/1507)

**Comment by jasonvarga** [comment]
One way to do this now is by filtering the listing:

```
/api/collections/blog/entries?filter[slug:is]=something&limit=1
```

**Comment by Buffalom** [comment]
I believe the only disadvantage of this is that it returns an array rather than an object right? Performance-wise it should be about the same.
