### ISSUE TITLE
Breadcrumbs for the assets

### ISSUE THREAD

**Issue by wm-simon** [statamic/ideas#166]
For a better overview and a faster navigation, especially with a lot of levels in the assets, it would be helpful to have breadcrumbs to navigate. 
To possibility to change the folder directly through the breadcrumbs would make it a lot faster, like in the windows explorer:
![image](https://user-images.githubusercontent.com/3351449/80928782-ff90f900-8da6-11ea-9928-fb0b3e7f7a65.png)

**Comment by jackmcdade** [comment]
We've had this for a while.
