### ISSUE TITLE
Replace asset filenames in markdown after renaming

### ISSUE THREAD

**Issue by jmartsch** [statamic/ideas#167]
## Bug Description
When I rename an asset/image in the control panel, the filename should be replaced in all markdown files to reflect the new filename, else you would get a broken image.
## How to Reproduce
- Upload an image to assets
- Add an image to an entry for example a page in a bard field
- Rename the image
- Open the page that contains the image in the browser
- The image is missing

## Environment

**Statamic version:** 3.0.0.-beta-26

**PHP version:** 7.3

**Comment by jackmcdade** [comment]
Moving this to the ideas repo. This is a complex, nuanced feature that many CMSes don't support. Renaming a file has implications, not all of which can be mitigated by the CMS. For example, what if you...

- linked to an image from an email
- hardcoded a URL in a template
- Emailed a link to a zip file to someone

**Comment by jmartsch** [comment]
I don't quite understand the concern. Currently, there is already the possibility to rename an asset (an image in my case) in the Control Panel. If you do this, it will no longer be accessible at the previous URL.

This results in the image that was used in a template no longer being displayed. No matter if it is linked absolute or relative.

What I ask for is that once you have renamed the asset, the templates are adjusted. A simple search and replace where the image name is the same as the previous name.

I think the user/developer is responsible here to know what the effects of renaming an asset/resource will be.

![image](https://user-images.githubusercontent.com/551551/81570976-9a8a6400-93a1-11ea-9a05-d98b774c54c2.png)

**Comment by jesseleite** [comment]
Coming in 3.2 🤘
