### ISSUE TITLE
Native support for multisite roles to limit user access

### ISSUE THREAD

**Issue by tao** [statamic/ideas#174]
I'm working on a multisite in Statamic 3 which supports multiple languages, to make it less complicated for the editors on the CMS, I want to make language roles and hide content from other languages and prevent them from editing things they shouldn't. 

I thought that might make a good example for the documentation and I started making a custom policy but ran into a problem as the multisite variables are protected.

```php
    public function boot(\Statamic\Sites\Sites $sites)
    {
        $this->registerPolicies();

        $this->app->booted(function() use ($sites) {
            Permission::register('manage {multisite} entries', function ($permission) use ($sites) {
                $permission
                    ->label('Manage :multisite entries')
                    ->replacements('multisite', function() use ($sites) {
                        return $sites->all()->map(function ($site, $key) {
                            return [
                                'value' => $site->handle, // protected
                                'label' => $site->config->name, // protected
                            ];
                        });
                    });
            });
        });
    }
```

However, because there is a multisite dropdown in the Statamic control panel I thought this might need more native support... otherwise a small update to make accessing the Multisite names possible so we can make this possible.

Do you think that might be possible or does it make the cms overly complicated?

**Comment by dambridge** [comment]
Don't think I've seen this one pulled over here yet... https://github.com/statamic/cms/issues/2667
