### ISSUE TITLE
Ability to use blueprints or fieldsets with Navigations to customize fields

### ISSUE THREAD

**Issue by matrad** [statamic/ideas#175]
It would be great if we can set the title for a reference entry in the navigation that we can name a Menu-Item in different navigations differently.

For example we have the top-menu and the footer-menu, in the top menu we've limitations by design and would like to use a short-variant of the menu, in the footer menu we have space and can add the longer description.

Current workaround is a Fieldset we create and adding a text-field for each menu and saving the title in the content, but it's a lot of work - would be easier to handle within the navigation.

**Comment by FlorianMoser** [comment]
+1

There are many use cases for this. Another example would be a parent node that links to the same page as its first child, but needs another title:

- About us (links to /about)
  - Our philosophy (links to /about)
  - Team
  - ...

**Comment by Krzemo** [comment]
+1 from me too ...
Allowing for custom blueprint for nav collection would suffice I guess

**Comment by studio1902** [comment]
Yep +1. Blueprints attached to nav items would be brilliant. For stuff like adding icons, navigation titles, colours, you name it. In some use cases it makes more sense to edit this in the navigation and not in the collection's entry itself.

**Comment by karpoq** [comment]
+1

**Comment by robdekort** [comment]
+1 custom fields are almost always a must for navs, the available workarounds all take the configuration away from where it makes most sense.

**Comment by jasonvarga** [comment]
Please give the original issue a thumbs up instead of commenting +1. We can see which issues people are most interested when we sort by number of reactions. (But feel free to also comment with extra context)

**Comment by stuffedmotion** [comment]
Custom fields for nav items are crucial for our use case

**Comment by MadeByMike** [comment]
Solving this with just a blueprint for the Nav entries feels less restrictive and probably more straight forward

**Comment by edalzell** [comment]
Same as https://github.com/statamic/ideas/issues/318

**Comment by edalzell** [comment]
and this one: https://github.com/statamic/ideas/issues/135

**Comment by jasonvarga** [comment]
Done in 3.2!

(How did we forget to race over here and close this issue?)
