### ISSUE TITLE
Add navigations endpoint to content api

### ISSUE THREAD

**Issue by marcusand** [statamic/ideas#176]
Would be great to have an endpoint for fetching navigation structures like
`GET /api/navigations/{navigation_name}`.

Maybe in a way that it only returns the entry titles and links but also the option to dissolve all relationships in the tree and get all data fields. 

Does this make sense? Anyone else like to see this feature?

**Comment by ty3sc** [comment]
> Anyone else like to see this feature?

This would be very helpful for me!

**Comment by jasonvarga** [comment]
Will be available in 3.1 (and currently available as a preview, in 3.1.0-alpha.1)
