### ISSUE TITLE
CP pages

### ISSUE THREAD

**Issue by MadJack-3** [statamic/ideas#182]
Add pages back to the CP. This is were people will manage content that do not need access to the back end.

**Comment by jackmcdade** [comment]
I don’t understand. Can you elaborate?

**Comment by MadJack-3** [comment]
My apologies, I didn't realize the pages were moved to collections, I found it not long after I posted this.  Just migrated to v3 over the weekend.  Only thing I would like to add is making the pages, or other items that can be multiple layers be auto collapsed instead of auto expanded.  I added a separate idea for this earlier already.
