### ISSUE TITLE
Add language key to content API

### ISSUE THREAD

**Issue by chrislow** [statamic/ideas#185]
I think it would be nice, if the content API would pass meta info about the language. This is handy when Statamic is only used as a headless CMS. This feature would be connected to the Statamic multisite feature.

Maybe something like this would be nice:

```json
{
  "data": [
    {
      "title": "Mein erster Tag",
      "language": "de"
    },
    {
      "title": "My First Day",
      "language": "en"
    }
  ],
}
```

**Comment by fjahn** [comment]
You can already do this by adding `fields=locale` to your query path like so:

`endpoint?fields=locale`

Which would result in this

```json
{
  "data": [
    {
      "title": "Mein erster Tag",
      "locale": "german"
    },
    {
      "title": "My First Day",
      "locale": "english"
    }
  ],
}
```

*`german` and `english` being the site handles you specified in `sites.php`.*

You can filter also for a specific site on all endpoints by filtering for `site` like so: `/endpoint?filter[locale]=default`.

**Comment by chrislow** [comment]
@fjahn thank you! this issue can be closed then :)
