### ISSUE TITLE
Add core modifier iso_format

### ISSUE THREAD

**Issue by vguerrerobosch** [statamic/ideas#187]
I'm wondering if you would consider adding a core modifier for dates to use Carbon isoFormat. I could create a PR for this if you are up to it.

```php
/**
 * Converts a string to a Carbon instance and formats it with ISO formats.
 *
 * @param $value
 * @param $params
 * @return string
 */
public function isoFormat($value, $params)
{
    return $this->carbon($value)->isoFormat(Arr::get($params, 0));
}
```

**Comment by damcclean** [comment]
If you're looking for a way to do it right now, Statamic provides the `format` modifier from where you can convert it to a proper timestamp.

```
{{ a_date | format="c" }}
```

**Comment by jackmcdade** [comment]
Yes, this is the most flexible, one-size-fits all solution. Thanks for tracking down the right argument @damcclean!

**Comment by vguerrerobosch** [comment]
I was thinking in multilingual functionality, because `format_localized` doesn't give you all the power `isoFormat` provides as far as I know. For instance:
```
{{ date | iso_format="lll" }}
```
would output `Wed, Oct 23, 2019 12:00 PM` in English and `mié., 23 de oct. de 2019 12:00` in Spanish for instance. There are many other string formats provided that adapt their shape for the specific language just and example.

Also, from the Carbon documentation:
> You also may know formatLocalized() method from Carbon 1. This method still works the same in Carbon 2 but you should better use isoFormat() instead.

Of course I did my custom modifier, just thought it might be handy for many people.

**Comment by jackmcdade** [comment]
Added to `master`! Thanks for your persistence :)

**Comment by vguerrerobosch** [comment]
Thank you for reconsidering this. Surely I didn’t make my point on the first place.
