### ISSUE TITLE
Couple templates to blueprints using `template: '@blueprint'` convention?

### ISSUE THREAD

**Issue by jesseleite** [statamic/ideas#192]
Generally speaking, content templates are pretty coupled to the blueprint used on the content.  If the user has to select the blueprint, they shouldn't also have to select the template.  Two approaches to handling this are:

1) Throwing a hidden `template` field with default value on each blueprint:

```yaml
-
  handle: template
  field:
    type: template
    default: 'map-page'
```

...which would automatically save a hardcoded `template: 'map-page'` to each entry.

2) Or something more on-the-fly like throwing `template: page` onto the collection yaml, and then:

```html
{{ partial :src="blueprint" }}
```

...this is nice because it can be configured on an existing set of entries without having to add `template` values to existing entries.  However, it requires a view file to handle logic, and conceptually we're not even loading 'partials', we're loading whole templates.

# The problem

If templates are fairly coupled to blueprints, why not make couple them by default right from the collection yaml?

# Possible solution

Throw this in the collection yaml:

```yaml
template: '@blueprint'
```

If the entry blueprint's handle is `map_page`, it'll try to load a `map_page` antlers view on-the-fly.

# Pros

- It's a one-liner solution to coupling templates to blueprints.
- Syntax-wise, this on-the-fly behaviour is similar to how we now do `redirect: '@child'` for first-child redirects on the link fieldtype.

# Cons

- None?  If you want to override this functionality on a specific entry, you could still hardcode a `template`.

**Comment by jackmcdade** [comment]
![approved](https://user-images.githubusercontent.com/44739/82829531-7b9bcf80-9e81-11ea-8843-dfb494743299.jpg)

**Comment by skoontastic** [comment]
Does this work yet? It's open, so I assume no. I was just going to add a feature request for this exact thing.

**Comment by jasonvarga** [comment]
It does not.
