### ISSUE TITLE
Add Max-items to replicators

### ISSUE THREAD

**Issue by padders** [statamic/ideas#196]
It would be great to have an option to add a limit on the number of items (of any set, or a specific set) that can be added to a replicator.

**Comment by jasonvarga** [comment]
Limiting a single set is a good idea.

If you want to limit the whole thing though, you can add a `max:3` validation rule.

**Comment by padders** [comment]
Ah ok, cool, that works. Is there a way to change the error message? I'm getting the following at the moment which doesn't make a lot of sense when I'm adding sets!

`May not be greater than 2 characters.`

**Comment by jasonvarga** [comment]
Oh, add an `array` validation rule too. (Although that should be applied behind the scenes automatically for you. I'll fix that.)

**Comment by padders** [comment]
Adding Array validation sorted the error message. Cheers :)
