### ISSUE TITLE
Seperate collection content from their structure

### ISSUE THREAD

**Issue by jonassiewertsen** [statamic/ideas#198]
I wanted to  bring this up in ideas. A seperation would be useful, to keep the overall structure of the collections without their content. 

That would require to save the structure tree of collections in another file. 

![statamic](https://user-images.githubusercontent.com/38906163/83488820-bfa85900-a4ad-11ea-8f07-27ae97575a03.png)

**Comment by jmartsch** [comment]
Yes please. This is not an edge case and a needed and welcome change. Not seperating content from structure is one thing, that really annoys me in my currently used CMS ProcessWire.

**Comment by jasonvarga** [comment]
It'll happen. Just wasn't thinking about this angle when it was implemented.

**Comment by jasonvarga** [comment]
This will be in 3.1
