### ISSUE TITLE
Toggle dev mode for super users?

### ISSUE THREAD

**Issue by lklion** [statamic/ideas#20]
Maybe It could be useful in a series of cases, for example to show automatically labels for fields instead of title (without click) or to show direct doc links in section or under particular fields type.

Could it make sense?

**Comment by jmartsch** [comment]
This would be nice, but I would display them side by side, so he sees what normal users see, and what handle developers would have to use.
![image](https://user-images.githubusercontent.com/551551/79977009-d9fa1a80-849d-11ea-9c32-31550e90de77.png)

**Comment by jackmcdade** [comment]
Hover to reveal!
