### ISSUE TITLE
YAML front matter with Antlers

### ISSUE THREAD

**Issue by edalzell** [statamic/ideas#200]
Would be super cool if we could put Antlers tags in our yaml front matter:
```
next: {{ collection:next in="pages" limit="1" }}{{ url }}{{ /collection:next }}
```

**Comment by jasonvarga** [comment]
Use a partial?

**Comment by jesseleite** [comment]
If you are getting super custom like that, what about `make:tag` and solving it with PHP?

**Comment by edalzell** [comment]
I'd then have to make a tag every time I wanted something like that, which doesn't seem right. It's not **that** custom, many folks have asked about Antlers in front matter.

As with many things, there are ways around it, thought it might be a nice-to-have.

**Comment by jackmcdade** [comment]
In this one specific case it might be nice to actually support a `next` and `previous` var inside the root context so you could just always do `{{ next:url }}`, `{{ next:title }}`, etc. 🤔
