### ISSUE TITLE
Compress javascript in yield tags

### ISSUE THREAD

**Issue by padders** [statamic/ideas#204]
Hi guys, 

Given my previous questions I'm probably asking something that you've already done! So sorry if that's the case.

We've been using yield tags to include specific JS files and specific inline JS for certain partials that require them. So using a `{{ section:page_scripts }}` tag like in Statamic v2 and a `{{ yield:page_scripts }}` tag in the template/layout file.

I was wondering if there was a way to minify inline JS on runtime, or possible combine all the components inside yield tags into one js file?

Or is there a better way to deal with JS that is specific to certain fieldsets/partials only? (I'm going to look at Alpine this morning, so that might be the answer)

**Comment by jackmcdade** [comment]
Best practices would warrant that your JavaScript should be pre-compiled and minified or use a modular approach (much like [Critical CSS](https://web.dev/extract-critical-css/)). Compressing the contents of the partial tag isn't a usecase even 99% of users would use, so alas this would need to be addon territory.
