### ISSUE TITLE
Alias all closing tags in Antlers with `end`

### ISSUE THREAD

**Issue by benfurfie** [statamic/ideas#21]
In v2, there's a mixed pattern of how you can close tags. For example, you can write:

```
{{ if condition }}
    // Code goes here
{{ endif }}
```

and

```
{{ if condition }}
    // Code goes here
{{ /if }}
```

But others like collection don't have that alias.

```
{{ collection from="blog" }}
    // Code goes here
{{ /collection }}
```

It's a personal preference (granted), but I'd love to be able to have a consistent alias that would enable users to close tags with the keyword end, as well as the /. E.g.

```
{{ collection from="blog" }}
    // Code goes here
{{ endcollection }}
```

**Comment by jackmcdade** [comment]
We had an internal discussion and even prototyped it and we've decided we will not be supporting this syntax. Thanks though Ben!

**Comment by jasonvarga** [comment]
I'd remove `{{ endif }}` if I could.

**Comment by jackmcdade** [comment]
Same.
