### ISSUE TITLE
FR: Allow addons to append sections to existing blueprints

### ISSUE THREAD

**Issue by AndrewHaine** [statamic/ideas#211]
I can listen to the `PublishBlueprintFound` (as below) and add a section to the Blueprint there with some custom fields however, the content doesn't get saved to the entry because part of the validation in the `EntriesController@update` method retrieves the original Blueprint - stripping out the additional field data.

```php
/**
  * @param \Statamic\Events\Data\PublishBlueprintFound $event
  *
  * @return void
  */
public function handle(PublishBlueprintFound $event)
{
    $bp = $event->blueprint;
    $contents = $bp->contents();

    $on_page_bp = // Retrieve blueprint
    $on_page_fields = $on_page_bp->contents()['sections']['main'];

    $contents['sections']['Section'] = $on_page_fields;

    $bp->setContents($contents);
}
```

**Comment by jasonvarga** [comment]
Doable using EntryBlueprintFound event
