### ISSUE TITLE
Bard anchor collection integration

### ISSUE THREAD

**Issue by studio1902** [statamic/ideas#217]
In v2 when you added a link to some text via the Bard editor you could select pages to link too. In v3 users have to manually type a URL which is less user friendly. Some integration with collections would be nice. It would be even cooler if links weren't hard coded but just if Bard would just save the relationship.

**Comment by robdekort** [comment]
Post by me.

**Comment by jmartsch** [comment]
Similar to #236. Please vote for it and #234 also.
