### ISSUE TITLE
Change Preview Link

### ISSUE THREAD

**Issue by pxwee5** [statamic/ideas#224]
Hi, 

I'm using Statamic v3 as a headless CMS and using NextJS for the frontend. Can we change the URL of the preview and send data to my nextjs preview page? 

If we can't do this immediately, can you explain how it works or how I could hook into this to provide this functionality ?

**Comment by duncanmcclean** [comment]
This will be possible in Statamic 3.3 (coming soon) - see the [preview docs](https://statamic-3-dot-3.netlify.app/live-preview/#headless-frontend-frameworks).
