### ISSUE TITLE
Form listing full width

### ISSUE THREAD

**Issue by wm-simon** [statamic/ideas#225]
It would be nice, if the form listing view in the cp would take the full width, like the collection view.

**Comment by stuartcusackie** [comment]
I agree. I have some quite long grid fields and could use the extra space for editing rows.

**Comment by jackmcdade** [comment]
> I agree. I have some quite long grid fields and could use the extra space for editing rows.

I think you must be thinking of the publish form?

**Comment by jackmcdade** [comment]
Done.

**Comment by stuartcusackie** [comment]
> > I agree. I have some quite long grid fields and could use the extra space for editing rows.
> 
> I think you must be thinking of the publish form?

oh yeah! "form submission listing"

Is this done for the entry form too?
