### ISSUE TITLE
Bard fieldtype: add sticky option

### ISSUE THREAD

**Issue by joroe** [statamic/ideas#229]
Hey Folks!
I love the new bard fields toolbar_mode: fixed option that lets the user always know that there are formatting options without having to click on text first (as with the floating option or in statamic 2). Now I have an usecase where a bard field gets very long and the user always needs to scroll up to use the toolbar. Using the old floating option is a solution but the perfect solution would be making the toolbar sticky so the user can always see the toolbar when scrolling down in a long bard field.

Thanks for considering!

**Comment by jackmcdade** [comment]
Bard's toolbar should already be sticky. Are you saying it isn't in v3? What version of Statamic and what browser are you on?

**Comment by joroe** [comment]
currently v3.0.0-beta.33
Chrome 83 on MacOS 10.15.4
Its a bit special because I am using bard inside a replicator. Maybe it's that?

**Comment by jackmcdade** [comment]
Oh yeah inside replicator we disable it because it's super hairy.

**Comment by joroe** [comment]
Hmk. I guess thats quite unusual. Maybe sometime?

**Comment by jackmcdade** [comment]
Yeah maybe sometime – it's the possibility of infinitely nested fieldtypes that causes an issue with `position: relative` and sticky. It blew my brain into 7 different bits and took my kids a weekend of searching the woods to find them all again.
