### ISSUE TITLE
Allow CMS user to open navigation item in new window

### ISSUE THREAD

**Issue by 1stevengrant** [statamic/ideas#232]
I've had a customer ask to be able to define whether a link can open in a new window for a nav item.

I think on this pane https://d.pr/i/T5RUM3 - a checkbox to open in a new window option would be great?

**Comment by jesseleite** [comment]
You can actually add a checkbox yourself by creating a custom `entry_link` blueprint... https://statamic.dev/collections#entry-link-blueprint

**Comment by 1stevengrant** [comment]
does that work though? When trying to create that blueprint via the cp, you can't because it already exists.

I added it manually but it doesn't show the new field here https://d.pr/i/Eezi3D

**Comment by jasonvarga** [comment]
You can add any sort of field to nav items in 3.2
