### ISSUE TITLE
Add option to collapse replicator sets by default

### ISSUE THREAD

**Issue by aerni** [statamic/ideas#233]
It would be great to be able to add something like `collapse: true` to a replicator to collapse the sets by default. This would greatly improve the overview when dealing with a lot of sets.

**Comment by ReneWeCode** [comment]
Our clients and I would really support this idea!

**Comment by Tobiasmidskards** [comment]
Would be awesome with this feature!

**Comment by patrickhoehn** [comment]
I need this too!

**Comment by jasonvarga** [comment]
Implemented in https://github.com/statamic/cms/pull/2771

**Comment by twd3** [comment]
It would be super cool if this worked on Bard as well.
