### ISSUE TITLE
Make UI of adding/modifying links in Bard better

### ISSUE THREAD

**Issue by jmartsch** [statamic/ideas#234]
Setting links is cumbersome. 
The URL input field of Tiptap is bad from the UI because it is too small and truncates URLs.
Two alternatives based on tiptap that solved this problem are
https://leecason.github.io/element-tiptap/
https://donotebase.github.io/quasar-tiptap/

![image](https://user-images.githubusercontent.com/551551/87789137-d1b44000-c83e-11ea-95ce-7c89b83b7a9a.png)

**Comment by arthurperton** [comment]
@jmartsch the UI for adding links in Bard has had a complete overhaul recently. Is your issue resolved now?

**Comment by jasonvarga** [comment]
(Yes)
