### ISSUE TITLE
Route binding names are too generic

### ISSUE THREAD

**Issue by imliam** [statamic/ideas#237]
I'm not a huge fan of the names used with `Route::bind()` in Statamic 3, when using it as a package in an existing Laravel application. My main concern is that **the naming is too broad, making it easy to conflict with names used in apps**.

For example, a typical route in a Laravel app may look like this:

```php
Route::get('users/{user}', function (App\User $user) { ... });
```

However, with Statamic installed, this simple route model binding case won't work as expected because the name `user` is explicitly bound to Statamic's own logic, which returns something different, so doesn't line up.

https://github.com/statamic/cms/blob/master/src/Providers/RouteServiceProvider.php#L184-L191

```php
Route::bind('user', function ($handle, $route) {
    throw_unless(
        $user = User::find($handle),
        new NotFoundHttpException("User [$handle] not found.")
    );

    return $user;
});
```

One obvious workaround for this on the developer's side is to rename all of their references to `user` to something that doesn't conflict:

```php
Route::get('users/{uz3r}', function (App\User $uz3r) { ... });
```

However, this feels gross to me. I wouldn't expect that installing a package like Statamic into an app would force other chunks of code to be changed and enforce the developer to change naming conventions as a workaround.

"user" isn't the only name either, there's a ton of route parameter names bound like this with vague named like "site", "global", "asset", etc.

Would it be possible that Statamic can change its route binding names to something that won't conflict with existing apps? Perhaps prefixing each of them for internal use in Statamic?

```php
Route::bind('statamic_user', ...);
```

Thoughts?

**Comment by jasonvarga** [comment]
Resolved in https://github.com/statamic/cms/pull/5775
