### ISSUE TITLE
Improve Laravel Nova integration

### ISSUE THREAD

**Issue by chrisbjr** [statamic/ideas#238]
Hi, I've been working on a project which utilizes both Statamic and Laravel Nova. Since Statamic now works as a package for Laravel, I'd think that adding other packages like Nova should be seamless but a lot of issues come up.

I've had success in integrating Laravel Nova into the project and I've outlined details on how I've accomplished it here: https://github.com/statamic/cms/issues/1764

It would be great though if the developer experience here would be seamless as I think using Statamic to manage the front end and Laravel Nova to manage the backend is a great combo.

Thanks

**Comment by stuartcusackie** [comment]
"Statamic to manage the front end and Laravel Nova to manage the backend"

This is exactly what I am hoping to achieve. What a combination it would be.

**Comment by jasonvarga** [comment]
It's been possible to use Nova with Statamic for a little while now. I tried it out and wrote the few steps needed.

Here you go! https://statamic.dev/knowledge-base/laravel-nova

Let me know how you get on.
