### ISSUE TITLE
Add EntryEditing event

### ISSUE THREAD

**Issue by aerni** [statamic/ideas#243]
It would be great to get an event that fires when an entry is being edited. I want to modify the blueprint only when the entry is being edited. Currently, I have to hack around this with the `EntryBlueprintFound` event like this:

```php
public function handle(EntryBlueprintFound $event)
{
  $isProduct = $event->blueprint->handle() === 'product';
  $isEditing = $event->entry;

  if ($isEditing && $isProduct) {
    $content = $event->blueprint->contents();
    $content['sections']['basic']['fields'][2]['field']['read_only'] = true;
    $event->blueprint->setContents($content);
  }
}
```

**Comment by jesseleite** [comment]
Not sure that's a hack, as that's exactly how the `EntryBlueprintFound` event is to be used.  You'll have an entry when editing, and you won't when creating.  Also, you're modifying a 'blueprint', which makes sense in a blueprint event, no?

**Comment by aerni** [comment]
Ah ok. Glad I'm using it correctly then. Maybe the docs could be a bit clearer on that matter. It wasn't clear to me that there won't be an `$event->entry` when you're creating an entry but only when editing an existing one.
