### ISSUE TITLE
Showing the handle of a field in the entry editing interface in the control panel 

### ISSUE THREAD

**Issue by erlingokse** [statamic/ideas#246]
I <3 Statamic, but this is a small thing that annoys me quite often.

It typically goes like this:

1.  I create a new fieldset or blueprint
2. I add fields with great handles
3. I create an entry and add content to a field
4. I open my IDE and create the template for it
5. I forgot what the handle was. Was it _hero_image_ or _image_hero_? Or maybe _hero_asset_? 🙇‍♂️
6. I open the latest tab in my browser, and there's the entry editing interface in the control panel where I just used to added some content.
7. I sigh.
8. I navigate through the control panel to find the field and find the handle. (It was _asset_hero_, of course 🤷‍♂️)
9. I feel frustrated.
10. I navigate back to the entry I was testing stuff in.
11. Found out I couldn't remember the handle of the other field.

Rinse and repeat.

I've got two possible solutions:
1. I can get better at remembering the damn name I gave that thing.
2. You guys make it possible to inspect (like just a css class or something would do the trick) or hover on a field in the control panel UI to get the handle ❤️

Thanks!

**Comment by erlingokse** [comment]
Dang! You got it already! (Found in in another issue.) For others: Clicking the label of a field shows the handle ❤️

My life just got 1 % better.

**Comment by jackmcdade** [comment]
Click the field name (Input label) and see what happens :)
