### ISSUE TITLE
UI/UX - Spacing / padding / active states around input fields on smaller screens

### ISSUE THREAD

**Issue by sebszocinski** [statamic/ideas#247]
![image](https://user-images.githubusercontent.com/5466694/88508350-bce56280-d01d-11ea-9bf5-b0bf4012d524.png)

See above, I feel these little things could be tidied up a bit... mainly the active state outline - it seems to cut off early on smaller screens or when in Live Preview mode. The second field "Show Fee" could have a little more padding on the left.

**Comment by jackmcdade** [comment]
Will be resolved in v4 via https://github.com/statamic/cms/pull/7559

**Comment by AndreasSchantl** [comment]
@jackmcdade Throwing this in here as well. Some buttons are way over the right. If you tab through with the keyboard, you cannot scroll back to the left
<img width="302" alt="image" src="https://user-images.githubusercontent.com/9936988/220466574-03173163-ad33-457d-91c2-40a45f1dc9af.png">
<img width="305" alt="image" src="https://user-images.githubusercontent.com/9936988/220466841-cbe81e57-c6aa-4893-8665-df037039c7fa.png">

**Comment by jackmcdade** [comment]
Are you looking at the UI improvements PR?On Feb 21, 2023, at 4:51 PM, Andreas Schantl ***@***.***> wrote:﻿
@jackmcdade Throwing this in here as well. Some buttons are way over the right. If you tab through with the keyboard, you cannot scroll back to the left

**Comment by AndreasSchantl** [comment]
That was V3. But It's happening on that PR as well. Probably the buttons could wrap into a second line?
<img width="303" alt="image" src="https://user-images.githubusercontent.com/9936988/220474531-9a8b2461-90e4-498b-a6b5-f54a1f9ae395.png">

**Comment by jackmcdade** [comment]
They do. I don’t see what you’re seeing. On Feb 21, 2023, at 5:37 PM, Andreas Schantl ***@***.***> wrote:﻿
That was V3. But It's happening on that PR as well. Probably the buttons could wrap into a second line?

**Comment by jackmcdade** [comment]
<img width="663" alt="CleanShot 2023-02-21 at 18 01 07@2x" src="https://user-images.githubusercontent.com/44739/220478283-2d89cccf-d5e2-43e7-9cf3-30c8aa9446fb.png">

**Comment by AndreasSchantl** [comment]
It's a markdown set to 1/3 of the width. The image button is cut off for me, and if I tab through with the keyboard, the above is happening.
