### ISSUE TITLE
Renaming Content Blocks

### ISSUE THREAD

**Issue by jamie-brown** [statamic/ideas#249]
It would be great to be able to rename content blocks within a collection that are built out from the Bard field. For example:

<img width="1270" alt="Screenshot 2020-07-28 at 12 46 58" src="https://user-images.githubusercontent.com/3788827/88661664-cbd91d00-d0d0-11ea-8da3-f8de9a3ef06a.png">

When collapsed, if you have multiple fields/fieldsets it looks quite messy as it shows a preview of the JSON. It would be nice if we can change the names of the blocks and hide the JSON data like so:

<img width="1269" alt="Screenshot 2020-07-28 at 13 04 13" src="https://user-images.githubusercontent.com/3788827/88663195-19ef2000-d0d3-11ea-99fa-1c406e1ac901.png">

**Comment by jamie-brown** [comment]
I came to open up a feature request to name content blocks, but it looks like my older self beat me to it. 😂

My client requested this after we merged their big site from Webflow over to Statamic. I still think it is a great idea as people not so technical that need to edit these blocks don't really know what block to look for, so they end up expanding everything and trawling through.

**Comment by jasonvarga** [comment]
If you add `replicator_preview: false` to all the fields inside the set except for one identifying one (if you don't have one, you could make a text field just for this purpose), it should do what you're asking.

**Comment by jamie-brown** [comment]
Awesome works perfectly. 

Thank you, Jason.
