### ISSUE TITLE
Define preset to use in composer arguments

### ISSUE THREAD

**Issue by benfurfie** [statamic/ideas#25]
Out of the box, Statamic 3 comes with a resources folder that contains a sass folder. I, like many others, don't use Sass/Scss. I use PostCSS. While it's trivial to delete that folder, it would be great if there was an ability to define a front end preset to use during the composer command.

**Comment by jasonvarga** [comment]
This could be solved with a starter kit.

Doable right now, but will be even simpler eventually. #501
