### ISSUE TITLE
Navigation - add a new tab/window option

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/ideas#255]
As the Navigation section allows a mix of entry links and external links, probably some of those external (or maybe internal) links will want to be `target="_blank"`. It doesn't appear there is a way to specify this.

The same probably applies with `rel="nofollow"`.

**Comment by rrelmy** [comment]
@dannyuk1982 Did you find a solution for this?
It is an issue we are facing currently with a new page

**Comment by dannyuk1982** [comment]
No, unfortunately not, IIRC I put in a conditional that looked if the link started with http, I'm not sure why the issue is closed, I'll reopen

**Comment by rrelmy** [comment]
Thanks.

Basically it would be nice to be able to edit the navigation entry blueprint to add custom fields.
There are multiple use cases that come to mind (subtitle, target, icons, custom style for items …)

**Comment by dannyuk1982** [comment]
Agree! It feels very half-cooked at the moment.

**Comment by duncanmcclean** [comment]
There's an existing FR issue if you're wanting blueprints on navs, please leave a 👍  reaction on there. #135
