### ISSUE TITLE
Visual suggestions for Fields in Bard Sets

### ISSUE THREAD

**Issue by pryley** [statamic/ideas#262]
**1. Let us hide field labels**

Sometimes when a field is self-explanatory it may be desirable to hide the Label to save space, particularly inside Bart sets which already take up a lot of visual space. There are also placeholder values which can be set which negate the need for a visual label. There are other ways to keep it accessible than always having a visual label (i.e. using a screen reader class on visually hidden labels).

![image](https://user-images.githubusercontent.com/134939/89452583-84334080-d723-11ea-885f-c43dd9328145.png)

vs

![image](https://user-images.githubusercontent.com/134939/89452562-7b426f00-d723-11ea-857b-76e6278c9e36.png)

**2. Use grid classes for layouts**

Grid classes allow to to define a set gap between each item and solve complex spacing issues. For example, what if we could have the fieldset look like this?

![image](https://user-images.githubusercontent.com/134939/89453180-74682c00-d724-11ea-8539-65cc2b8cbf79.png)

**Comment by pryley** [comment]
This could also be possible to do using the `cp.css` [as shown here](https://statamic.dev/extending/control-panel#adding-css-and-js-assets), however in order to allow full customisation, we would need to somehow be able to target the fieldset by its handle which currently does not exist in the DOM.

**Comment by robdekort** [comment]
Lovely idea. Grouping fields for visual arrangement would be a nice addition as well.

**Comment by duncanmcclean** [comment]
I believe all of the points in this issue have already been addressed - correct me if I've missed anything:

* You can hide display labels using a toggle introduced in statamic/cms#7737.
* The consistency of spacing between fields was improved in [v4.0.0](https://github.com/statamic/cms/releases/v4.0.0).
* The ability to "group fields" isn't *yet* possible but there's another FR open for that: #210

<img width="844" alt="image" src="https://github.com/statamic/ideas/assets/19637309/00744f4f-51cd-48ac-ac95-78c84f10869a">
