### ISSUE TITLE
Deploy to Vercel

### ISSUE THREAD

**Issue by f3l1x** [statamic/ideas#265]
Hi ✋ I am author of [PHP runtime](https://github.com/juicyfx/vercel-php) for [Vercel](https://vercel.com) (formerly ZEIT). 

I came across statamic v3 and wonder if we can somehow deploy it to Vercel, relying on serverless lambda powered by php. I have some working examples of nette / symfony / laravel, etc. 

I offer you my help if you consider interesting. 

See ya!

**Comment by jackmcdade** [comment]
Here's what i've done to use the static site generator: https://github.com/statamic/ssg#deploy-to-vercel

I haven't tried to get it to run on serverless as a dynamic php app though. Would love to work it out!
