### ISSUE TITLE
Add "Copy URL" option to asset action popover list

### ISSUE THREAD

**Issue by notnek** [statamic/ideas#266]
My clients upload PDFs into the asset container and need to get the public URL for use elsewhere. It would be nice if there was a "Copy URL" that put the asset's URL in your clipboard for use elsewhere.

Current popover list:

![Screen Shot 2020-08-12 at 3 14 06 PM](https://user-images.githubusercontent.com/114763/90057672-ba863800-dcae-11ea-84de-8afb20e3de87.png)

Desired popover list:

![Screen Shot 2020-08-12 at 3 14 35 PM](https://user-images.githubusercontent.com/114763/90057691-c2de7300-dcae-11ea-8e1d-9ed170bbf001.png)

Happy to add this functionality myself if needed.

**Comment by jackmcdade** [comment]
Certainly a good idea. Just in case you _weren't_ aware, if you click on the asset and get the edit/details modal there's a "copy link" button there you can use in the mean time.

**Comment by notnek** [comment]
@jackmcdade I actually don't see that button. When I click on the asset (tested a PNG and PDF), I see buttons for:

- Close modal
- Download file
- Open in a new window (doesn't always work for PDFs as some browsers just download the file)
- Rename file
- Move file
- Set focal point (for the PNG only)
- Delete
- Save

Am I completely overlooking that button? 🙈

**Comment by jackmcdade** [comment]
Ah sorry it's the open in a new window button. You can right click and copy that url.

**Comment by notnek** [comment]
That's what I tried first. But it's an anchor without a `href` ☹️ (Editor.vue: `window.open(this.asset.url, '_blank');`)

Happy to PR an improvement for that and (separately if needed) a copy URL action.

**Comment by damcclean** [comment]
This issue might need #342 to be implemented first before this issue can be dealt with.

**Comment by jasonvarga** [comment]
Will be in the next release.
