### ISSUE TITLE
Support `slots` for partials

### ISSUE THREAD

**Issue by edalzell** [statamic/ideas#268]
Had a discussion recently with someone who wants Antlers to be more like Blade and one of the items they brought up were the support of "slots".

I took a quick look and it's pretty trivial to support at least some basic functionality:
In `Partial.php`:
<img width="624" alt="image" src="https://user-images.githubusercontent.com/6069653/90090266-6f811a80-dcd8-11ea-917e-98a94c71ec35.png">

In the template: 
<img width="284" alt="image" src="https://user-images.githubusercontent.com/6069653/90090283-7c057300-dcd8-11ea-88c0-732550077f0f.png">

Would you folks be open to a PR for this?

**Comment by jonassiewertsen** [comment]
That would be amazing

**Comment by damcclean** [comment]
This feature has been implemented in v3.0.13 so this issue can be closed.
