### ISSUE TITLE
Middleware group for webhooks

### ISSUE THREAD

**Issue by aerni** [statamic/ideas#269]
I had a [recent discussion](https://discordapp.com/channels/489818810157891584/674287924547813416/743173584230285422) with @edalzell and @jonassiewertsen on Discord about the best way to handle routes for webhooks.

Creating a route for webhooks requires you to add the route to `protected $except = ['route']` in the `App\Http\Middleware\VerifyCsrfToken` middleware. Sadly, there's no way to programmatically add to that array. 

In an addon context, this makes the setup for the end-user more complicated. It would be great if there was a way to bypass this middleware for webhooks.

Erin suggested that we could create a new middleware group for webhooks. This would be identical to the web middleware group minus `VerifyCsrfToken`. And then make this possible in the addon's service provider.

```php
protected $routes = [
    'webhooks' => __DIR__.'/../routes/webhooks.php'
];
```

I'd be happy to take a look at this if you're open for a PR.

**Comment by jesseleite** [comment]
Why not use `->withoutMiddleware([VerifyCsrfToken::class])` on your webhook route?  From Laravel docs...

![image](https://user-images.githubusercontent.com/5187394/90141700-76944100-dd49-11ea-85f5-2128d961671a.png)

**Comment by aerni** [comment]
You're a genius! That should do it. 🤪

**Comment by edalzell** [comment]
@jesseleite @aerni that's Laravel 7 only.

**Comment by jesseleite** [comment]
You could have your addon proactively require `^7.0`, since most people creating statamic apps will be getting 7.x anyway.  Just because Statamic's core supports 6.x, doesn't mean all Statamic and Laravel packages are going to support 6.x.

**Comment by edalzell** [comment]
Yup, that's what I've done with all my addons.

**Comment by jesseleite** [comment]
Cool, closing this :)
