### ISSUE TITLE
Fieldtype changes to help with form blueprints.

### ISSUE THREAD

**Issue by theblacksheepltd** [statamic/ideas#272]
The ability to use blueprints for forms has made it possible to build front end forms via the CP. Here are a few additions that would make this easier:

- **Default value for _hidden_ field** - When creating a blueprint for an embedded form (i.e. Salesforce embed), hidden fields with prefilled values are necessary. Having a default value field in the _hidden_ fieldtype would make this easier.

- **Options array on _collection_ fieldtype** - I have clients who use dropdowns/checkboxes based on collections. They sometimes need to add hard-coded options to the option list, like an "all/All Cities" option when used with a "locations" collection. A key/value array saved within the fieldtype would allow for this. Could also be used for a custom "Select" labeling.

- **Default values on text and select fieldtypes** - I just miss this feature from v2. It is nice to be able to set this on select/radio fields.

**Comment by damcclean** [comment]
You can already set default fields by setting `default: something` on the YAML config for the field. There's an issue currently open (#356) to make it part of the Statamic UI.
