### ISSUE TITLE
Any hints on how to render a nav using blade?

### ISSUE THREAD

**Issue by kevinarrieta** [statamic/ideas#273]
I'm starting playing around with Statamic, I really like it, I was able to render a nav using Antlers, but I decided to star trying blade, is it possible to render a nav using blade? can someone please guide on how to accomplish that? I'm sorry if this is something kind of obvious, I just couldn't find how to do it

**Comment by jackmcdade** [comment]
Hello there!

We have plans to make our core tags and features more Blade friendly (with docs). Some are easier than others to work with at the moment. For now the best way to see what's involved is to look at the code inside the tag and see if that's something you can run inside Blade. 

For example, the Nav stuff happens in the [Nav tag](https://github.com/statamic/cms/blob/master/src/Tags/Nav.php#L10-L13), which extends the [Structures tag](https://github.com/statamic/cms/blob/master/src/Tags/Structure.php#L29-L43), which is basically just a call to the [TreeBuilder](https://github.com/statamic/cms/blob/master/src/Tags/Nav.php#L10-L13).

The way the nav is assembled though you'd need to work some of it out in a controller. For now, I'd recommend using Antlers for the nav if you possibly can :)

P.S. The best place to post questions like this is [the forum](https://statamic.com/forum). This repo is for feature requests 😊

**Comment by kevinarrieta** [comment]
Thanks Jack, very useful! I'll post my questions on the forum from now on!
