### ISSUE TITLE
Default all fields to `replicator_preview: false`

### ISSUE THREAD

**Issue by johncarter-** [statamic/ideas#282]
I would argue that the name of the set is sufficient in most replicators and therefore I would propose that `replicator_preview: false`  should be default on all fields.

It would save us having to go through each field to make the UI not like this:

![image](https://user-images.githubusercontent.com/3776888/91307582-0e604900-e7a6-11ea-8ff2-35335f79156e.png)

**Comment by jasonvarga** [comment]
The fields that are outputting JSON is obviously not right. I would say we should make sure those look better.

Having to enable the preview if you _do_ want it would definitely be even more laborious.

However, adding an option _to the replicator_ to hide the previews could be a nice option.

**Comment by johncarter-** [comment]
Okay, well I am at your mercy but in my opinion it should be hide all sub-fields by default then you can enable them when appropriate. Maybe I am missing some use-cases.

**Comment by jasonvarga** [comment]
The whole reason we added the previews in the first place is because people were saying that the set names alone were not enough.

**Comment by johncarter-** [comment]
Okay then. Cool.

**Comment by jasonvarga** [comment]
I still think being able to disable the previews on the replicator level is fine, if you prefer them all disabled.

**Comment by robdekort** [comment]
I agree with John here. I'd rather enable them on a field by field basis. The replicator currently looks better with all fields off than all fields on. I rather have them all off and pick the ones I want on while creating my sets.

**Comment by jackmcdade** [comment]
I like the idea of enabling them specifically. Their verbose, messy defaults kinda always bothered me.

**Comment by edalzell** [comment]
so @jackmcdade @jasonvarga, if this were to be implemented, you'd like a replicator config `preview_fields` that hides all fields, unless the field is explicitly set to display?

**Comment by lokmanm** [comment]
Apart from [Hiding replicator fields in preview](https://github.com/statamic/cms/pull/6022), would it be possible to select which fields to display on a replicator set ? Or will that require another PR ?
