### ISSUE TITLE
Expose "width" fieldtype.

### ISSUE THREAD

**Issue by michaellindahl** [statamic/ideas#286]
It would be awesome if you could expose the width functionality in Blueprint as a selectable Blueprint field.

I would like to have a collection that contains a width field so that the user can select at what width an item should be displayed at. It would be awesome if I could allow all or a subset of the options. Sure, I could use the select, or range fieldtype; but the width fieldtype is just so awesome for this.

The alternative is using a the select or button group fields.
![image](https://user-images.githubusercontent.com/692663/91644744-dbab9000-e9f3-11ea-98ac-5d9665511f87.png)

**Comment by jasonvarga** [comment]
Will be in 4.0
