### ISSUE TITLE
Live Preview context

### ISSUE THREAD

**Issue by 1stevengrant** [statamic/ideas#290]
If I'm publishing an piece of context, Live Preview is great to preview the actual entry itself but that piece of content might be exposed across a number of different places.

As an example, I publish a blog post that might be featured on the home page of a site and most definitely on a blog index.

It would be great to be able to use Live Preview to see what the content would look like in those particular context cases.

I would expect to be able to set the contexts in config for a collection.

**Comment by jasonvarga** [comment]
Good idea. 👍

**Comment by tao** [comment]
I think a nice addition to this would be allowing a different template for live preview in the collection, for instance:

```yaml
template: faq/show
preview: faq/live-preview-template
layout: layout
route: 'faq/{slug}'
```

For example, I want to show ALL the FAQ entries on one page, but for the live preview it would be nice to just show one on a custom template... and something else that might be nice is adding a `live-preview: true` to the context so we can check in antlers if it's a live preview or a web page:

```html
{{ if live-preview }}
   <p>Note to editors: if a PDF file exists the user will not see this page, instead the PDF will open directly.</p>
{{ else }}
   {{ content }}
{{ /if }}
```

**Comment by tao** [comment]
For my FAQ pages at the moment I do this workaround and use the preview template directly. The FAQ is a tree with two levels for topics, so in the preview I just want to see the one child entry.

```yaml
title: FAQ
sites:
  - en
template: faq/preview
layout: layout
```

Then in my routes file I override the FAQ view:

```php
Route::statamic('faq/{slug}', 'faq.show');
```

And in the `faq.show` class I show all the children (Q&A) under one topic and link to the anchor on the page... like this: `/faq/connecting-with-others#what-events-do-you-hold`

So in the `faq.show` view I just render all children under one topic like this:

```
{{ nav:collection:faq }}
          {{ if slug == segment_2 }}
              {{ children }}
                  ... my questions and answers list...
              {{ /children }}
          {{ /if }}
{{ /nav:collection:faq }}
```

Just thought I'd share this use-case of how I need different contexts/views for live-preview as it may help when planning this feature request.

**Comment by jasonvarga** [comment]
Live Preview targets are a thing in 3.3. statamic/cms#5109
