### ISSUE TITLE
Caching for API routes

### ISSUE THREAD

**Issue by goellner** [statamic/ideas#292]
Would be great to have a caching for API routes, which gets invalidated, when the content changes. This would speed up headless sites a lot.

**Comment by marcusand** [comment]
yes, please!

**Comment by gefangenimnetz** [comment]
We recently had an event with lots of concurrent users. SPA was built in a way to poll for a collection every 15 seconds. Basically server died soon (PHP processes took to long). We (emergency) switched to a static json file that basically contained the API response and manually changed content in there from time to time. A cached API response with invalidation would probably have helped a lot.

**Comment by jasonvarga** [comment]
Available in the 3.1 preview.
