### ISSUE TITLE
Don't list error templates in the "template" field

### ISSUE THREAD

**Issue by FlorianMoser** [statamic/ideas#293]
Currently, the template fields lists templates, layouts and error templates:

<img width="202" alt="grafik" src="https://user-images.githubusercontent.com/8578668/91861121-bf665800-ec6c-11ea-93ce-df7b717bede9.png">

It doesn't make much sense to show templates that are not intended to be used as such, like error pages and complete layouts. Maybe only consider templates in a /template directory? Or add the option to the template fieldset to choose a directory?

**Comment by jasonvarga** [comment]
Fair, but if you're intending for only a subset of templates to be selectable, perhaps just make a `select` field with the options you actually want.

**Comment by jackmcdade** [comment]
the thing about templates vs layouts is that we don't enforce a naming structure. In v2 we did, but in v3 you can arrange them however you want. We might just end up with the same problem in reverse ("why doesn't my template show up?"). However, excluding the errors makes a lot of sense. I can't think of any good reasons why you'd create an entry and map it to a 404 on purpose 😂

**Comment by FlorianMoser** [comment]
> Fair, but if you're intending for only a subset of templates to be selectable, perhaps just make a `select` field with the options you actually want.

> We might just end up with the same problem in reverse ("why doesn't my template show up?").

That makes sense. I guess it is freedom vs. tight structure.

> I can't think of any good reasons why you'd create an entry and map it to a 404 on purpose 😂

Me neither, actually 😂

**Comment by caseydwyer** [comment]
It would be kinda nice to have an "exclude directories" option (or a similar concept) on the Template fieldtype. For example, to avoid this sort of thing: 
![image](https://user-images.githubusercontent.com/13950848/107122821-aa1ad880-685f-11eb-9c15-84a125b78218.png)
