### ISSUE TITLE
Package minus Tailwind/Mix

### ISSUE THREAD

**Issue by websmyth** [statamic/ideas#294]
It would be cool to have the option of installing V3 without Tailwind and Laravel Mix. I understand these are popular, but for non-Tailwind/Mix users, they have to be manually stripped out in each project if installed by the normal method.

Removing these might also reduce the barrier to entry for new Statamic users (especially those unfamiliar with Tailwind/Mix).

**Comment by jasonvarga** [comment]
You can fork statamic/statamic and rip out tailwind (and replace it with what you prefer), then use that as the boilerplate for your new sites.

**Comment by websmyth** [comment]
If we do that, is it still possible to install through the terminal? Sorry, bit of a newbie question...

**Comment by damcclean** [comment]
Yes, you'll still be able to install it later if you want to.

**Comment by websmyth** [comment]
By cloning only I guess or `composer create-project`?

**Comment by damcclean** [comment]
Either.

**Comment by websmyth** [comment]
Mega, thanks!
