### ISSUE TITLE
Add user permissions for sites/locales

### ISSUE THREAD

**Issue by AndreasSchantl** [statamic/ideas#295]
## Feature Description
Right now it is not possible to restrict access to different versions of the site for users. It would be great to have this feature added.

**Statamic version:** 3.0.2

**Comment by tao** [comment]
I believe these are related:

- https://github.com/statamic/ideas/issues/174
- https://github.com/statamic/cms/issues/2667

**Comment by jasonvarga** [comment]
Closing in favor of statamic/cms#2667
