### ISSUE TITLE
Allow choosing from multiple asset containers in asset fields

### ISSUE THREAD

**Issue by fitzage** [statamic/ideas#298]
In v2, I could set an asset container for a field, but then allow choosing a different asset container instead, which is not possible in v3. There are some reasons why I would like to see this added back in:

- I would like specific fields to use a specific asset container, but then be able to have a field elsewhere that is able to choose from various asset containers so I don’t have to duplicate the image.
- These asset containers might have different blueprints for their images, which is why just using multiple folders in one asset field doesn’t necessarily solve the problem.
- I could convert my half dozen asset containers from V2 into folders in one asset container, but that means a LOT of work, particularly to update all existing asset fields.

**Comment by jasonvarga** [comment]
With the way asset containers work in v3, I don't think this will ever happen. Not natively anyway. Maybe you could make a custom fieldtype.

**Comment by Swennet** [comment]
@jasonvarga Having this feature would solve a particular use case for us:

We would like to have a "shared" asset container linked to a filesystem outside of our project root that multiple Statamic websites can use. We would then attach two asset containers "Assets" and "Shared Assets" to our Asset fields.

We considered using a symlinked directory in our storage folder for this, but it seems like [Flysystem doesn't support](https://github.com/thephpleague/flysystem/issues/599#issuecomment-179246996) this.
