### ISSUE TITLE
rtl version of the cms admin

### ISSUE THREAD

**Issue by farshadff** [statamic/ideas#299]
hi , i wanted to know if there is any rtl option for the admin panel of statamic or are there any language file so i cant translate that to my own language and use it in rtl mode . thanks in advance

**Comment by jasonvarga** [comment]
There are language files so can translate it, but there's currently no rtl mode.

https://statamic.dev/cp-translations#contributing-a-new-translation

**Comment by farshadff** [comment]
thanks for the great work :)
