### ISSUE TITLE
FR: Reuse blueprints and columns from user preferences in selector stack of Relationship fieldtype

### ISSUE THREAD

**Issue by sauerbraten** [statamic/ideas#3]
It would be much better to just use the columns from a user's preferences to render a selector stack when linking an entry from a collection using the Relationship fieldtype. Right now, when we use `<relationship-fieldtype>` in one of our components or even a Bard toolbar button child component, we have to re-implement logic on what columns to show for what collections in that stack, after we already added that logic to our wrapping PolygonRelationship, even though it's right there in the user preferences.

**Comment by duncanmcclean** [comment]
Done in statamic/cms#8900
