### ISSUE TITLE
Tag to get a collections mount url

### ISSUE THREAD

**Issue by robdekort** [statamic/ideas#301]
It would be nice if you could get the url for the entry a collection is mounted on. Something like: `{{ collection:mount from="blog" }}`

This useful when for example you show recent entries on your site and want a read more link. 

Now I usually make a global for this.

**Comment by freshface** [comment]
@robdekort  https://statamic.com/forum/4925-get-url-of-page-with-mounted-collection#reply-16620

**Comment by robdekort** [comment]
Lovely, that should be merged into core.
