### ISSUE TITLE
Bring back the 'click the label to reveal the handle' feature

### ISSUE THREAD

**Issue by JayGeorge** [statamic/ideas#302]
## Description of the Problem

There used to be a neat feature where you could click the name of a field in the CP and it would tell you the handle.

I see that's gone now… presumably in the accessibility updates, since clicking on the label should technically just focus the field.

This is kind of a shame though—that was a really handy feature! I hope there's a way to bring this back without affecting the accessibility of the label.

Maybe you're already aware and plan to work on this.

## What steps will reproduce the problem?

1. Go the control panel
2. Go to a page or collection
3. Click the field label

## What is the expected result?

The label should reveal the handle for the label, as before

## What happens instead?

Since the accessibility updates of 3.0.3 (which are otherwise great), clicking the label simply focuses the field

## Is this a regression?

Yes, I believe it regressed in 3.0.3

**Comment by jackmcdade** [comment]
Yeah you’re right that it was accessibility related. I’m working on a keyboard shortcut to toggle all of them on and off, but because global reactivity is complicated it didn’t make the release. 😅

**Comment by JayGeorge** [comment]
Oh, that's great to hear! That would be awesome

**Comment by ReneWeCode** [comment]
@jackmcdade A "copy to clipboard"-button would be pretty awesome 😎

**Comment by rrelmy** [comment]
Version 3.1.31 brought back the handle as tooltip, but not within replicators or bard elements.

I think we should reopen statamic/cms#1312
