### ISSUE TITLE
Add toggle to Grid row

### ISSUE THREAD

**Issue by aerni** [statamic/ideas#303]
Make it possible to enable/disable a Grid row the same way you can with Replicator and Bard sets.

**Replicator/Bard**
<img width="892" alt="Bildschirmfoto 2020-09-06 um 12 49 15" src="https://user-images.githubusercontent.com/23167701/92324174-7aad3900-f03f-11ea-89b3-77218096e812.png">

**Grid**
<img width="894" alt="Bildschirmfoto 2020-09-06 um 12 49 24" src="https://user-images.githubusercontent.com/23167701/92324175-7bde6600-f03f-11ea-9fb2-76132fc591cf.png">

**Comment by jasonvarga** [comment]
I'd suggest using a Replicator with a single set. It's basically the same thing. Especially once #29 is implemented.
