### ISSUE TITLE
Field instructions below field

### ISSUE THREAD

**Issue by MattRogowski** [statamic/ideas#311]
It would be nice if we would be able to choose whether the instructions for a field below the field instead of above it. The reason being if one field has instructions and another doesn't (or one field has a longer description than another), it can make the publish form look unbalanced:

![image](https://user-images.githubusercontent.com/545339/92740896-08f22980-f376-11ea-85ed-d005737d9bda.png)

To me, this would look nicer, and it's still clear there's instructions:

![image](https://user-images.githubusercontent.com/545339/92741077-3212ba00-f376-11ea-890f-15fd2c6a44bf.png)

I'm aware this may end up cluttering the blueprint form with an extra option, but I think it would help create nicer looking publish forms.

**Comment by jackmcdade** [comment]
We sure did! Let's bring it back baby.

**Comment by jasonvarga** [comment]
I dunno, I like the offset fields. It's avant-garde.

**Comment by MattRogowski** [comment]
❤️

**Comment by damcclean** [comment]
@jackmcdade @jasonvarga What do you think the best way of implementing this would be? 

From looking at the [v1 docs](https://v1.statamic.com/learn/control-panel/fields-and-fieldsets), it looks like the above and below instructions were different keys, is that the same way you'd implement it in v3 or would you use a select field for selecting if you want it above/below?

**Comment by jasonvarga** [comment]
I think an option to choose the position will be easier to implement.

I'm not sure that many people would need instructions above _and_ below a single field.

**Comment by jesseleite** [comment]
Instructions above _and_ below would be

>avant-garde.

**Comment by jasonvarga** [comment]
Will be in 3.2.3
