### ISSUE TITLE
Navigation height fix

### ISSUE THREAD

**Issue by sarunaslite** [statamic/ideas#313]
Fix navigation height:

`.nav-main.scss` 67 line change to `height: calc(100% - 52px);`

Space for the trial message:
`.nav-main ul:last-child { padding-bottom:48px;}`

![nav-main](https://user-images.githubusercontent.com/39726634/92926259-6ce32380-f444-11ea-8b1d-f4c06fbe18f5.png)

**Comment by jasonvarga** [comment]
This was intentionally changed from 52 already, in https://github.com/statamic/cms/issues/2134

**Comment by sarunaslite** [comment]
@jasonvarga it is not the same problem and still not fixed.
Statamic 3.0.47
Video:
https://user-images.githubusercontent.com/39726634/111275977-793c7900-863f-11eb-8e2a-44fbfaf1dc60.mov
Solution:
https://github.com/statamic/ideas/issues/313#issue-699264812

**Comment by sarunaslite** [comment]
@jackmcdade can you check this?

**Comment by duncanmcclean** [comment]
Looks like it's been fixed to me, I'm using Statamic v3.0.47.

![image](https://user-images.githubusercontent.com/19637309/111611738-ac644100-87d4-11eb-8829-8fc68cb57768.png)

If you're still running into the issue, try running `php artisan statamic:install` to publish the latest JS & CSS and also try opening the Control Panel in a different browser in case caching is causing issues.

**Comment by sarunaslite** [comment]
No luck. I don't know why but it seems Statamic is trying to show license message by adding `showing-license-banner` class, which breaks sidebar height.
<img width="1440" alt="Screenshot 2021-03-18 at 12 38 39" src="https://user-images.githubusercontent.com/39726634/111613294-05d56b80-87e7-11eb-84eb-25442deaa26d.png">

**Comment by duncanmcclean** [comment]
> No luck. I don't know why but it seems Statamic is trying to show license message by adding `showing-license-banner` class, which breaks sidebar height.
> <img alt="Screenshot 2021-03-18 at 12 38 39" width="1440" src="https://user-images.githubusercontent.com/39726634/111613294-05d56b80-87e7-11eb-84eb-25442deaa26d.png">

What's your licensing status? Are you in trial mode, have you dismissed the trial banner?

**Comment by sarunaslite** [comment]
Our license is pro.
<img width="989" alt="Screenshot 2021-03-18 at 12 55 27" src="https://user-images.githubusercontent.com/39726634/111615315-40400800-87e9-11eb-85f5-5b674da48a24.png">

**Comment by duncanmcclean** [comment]
Ah, I see what you mean. I can replicate on a production Pro site.

![image](https://user-images.githubusercontent.com/19637309/111623386-3b2b8a80-87e2-11eb-9ad0-9933033ce1e8.png)

**Comment by jackmcdade** [comment]
Fixed in https://github.com/statamic/cms/commit/b1582d590208e204b1e5c6bd005aef260aac5adb.
