### ISSUE TITLE
Content Redirect Management

### ISSUE THREAD

**Issue by sg-modlab** [statamic/ideas#316]
There was a redirect plugin in v2 that not sure is being ported to v3. Allowed for automated redirect rules to be created when slugs and such changed. Also, allowed for manual redirects to be configured and would track 404s to help assess where redirects may make sense.

This type of plugin has become a go to need on our site builds and we are not plugin crazy. Feeling like this type of functionality should be out of the box.

**Comment by damcclean** [comment]
This feature hasn't been implemented into Statamic v3 core yet, although someone has [created an addon](https://statamic.com/addons/rias/redirect) which I believe achieves the same thing.
