### ISSUE TITLE
Allow non-links and additional data in navigations

### ISSUE THREAD

**Issue by MattRogowski** [statamic/ideas#318]
I'm building a "mega-menu" style nav with a row of items in the header that when clicked displays a panel with a list of sub-pages. What I can't currently do is have a top-level item that isn't a page - for example, I may want to add a "Services" item that contains a sub-menu of all the services on offer, but there is no top-level Services page. Currently, I'd need to create one simply to be able to add it to the navigation.

A suggestion that I think has been included in other tickets too is to be able to add additional data for nav items, for example to show some blurb or an image in the sub-menu panel. Currently we'd have to add this to the main blueprint for all pages, even though it'd only be used on pages that are top-level menu items.

Edit: This may be more in need of a "menu builder" addon than navigation though - aware it may be going outside the bounds of what the navigations are designed for. I also need 2 separate links of sub-links but can see it getting far too complicated.

**Comment by ashbakernz** [comment]
I second this,  I'm trying to have icons for each navigation item, setting the YAML doesn't seem to do it. Would be awesome if we could add blueprints /fields to the navigations.

**Comment by edalzell** [comment]
In my case I'd like to use a different colour in each nav item, that is user configurable

**Comment by geekish** [comment]
+1. I would love to be able to use blueprints for navigations... for custom icons, title text, etc.

**Comment by JonKaric** [comment]
+1. Would love to see this happen. Would be great to have a navigation title, like in Wordpress too.

**Comment by MarlBurroW** [comment]
+1, Come from Wordpress+ACF and for me this feature is essential.

**Comment by jasonvarga** [comment]
Please give a thumbs up reaction to the issue instead of leaving a +1 comment.

**Comment by jackmcdade** [comment]
Added in 3.2.

**Comment by MattRogowski** [comment]
Outstanding, thank you
