### ISSUE TITLE
Allow .jp2 as filetype in Assets

### ISSUE THREAD

**Issue by joseph-c-c** [statamic/ideas#324]
Allow an assets container to handle .jp2 file extension identical as .jpeg

**Comment by jackmcdade** [comment]
I looked into supporting this and unfortunately not all browsers support rendering jp2 images, nor does the gd library support manipulating them. We'd only be able to support it when using imagick and using safari, which isn't a consistent experience. At this time, we'll need to close this request as blocked. Sorry!
