### ISSUE TITLE
FR: Reorder Structures

### ISSUE THREAD

**Issue by mikemartin** [statamic/ideas#33]
Structures are ordered alphabetically but it would improve the sidebar navigation if we could number order the listing to move Structures of higher importance (Pages) to the top of the list.

<img width="1678" alt="Screen Shot 2019-10-24 at 2 54 43 pm" src="https://user-images.githubusercontent.com/414211/67538422-bb9fa600-f72a-11e9-981e-7794e2c7b112.png">

**Comment by jasonvarga** [comment]
Most likely made redundant by changes in #74 and/or #100
