### ISSUE TITLE
Create/edit forms by non-dev client

### ISSUE THREAD

**Issue by remiduval** [statamic/ideas#333]
I happen to have clients that regularly need to create/edit forms on their website and I have no easy option to offer that wouldn't involve giving them access to all blueprints, explaining what's a blueprint and risking they edit other vital blueprints.

**Solution 1: Granular permissions for blueprints**
Give rights to specific blueprints and allow editing blueprints for your own forms.

**Solution 2: Form fields edition inside 'Forms' section**
I love the idea that form fields are just another blueprint in the end. Maybe that's how it should be handled 'under the hood' but I'd find it a bit more straightforward to have the edition of the fields for a form directly in the 'Forms' section. And to then give full rights on that section to the client.

Open to other solutions that would allow a non-dev to create/edit forms :)

**Comment by duncanmcclean** [comment]
We now have a "Configure Form Fields" permission, which will allow you to give your client access to edit *just* form blueprints.

Added in statamic/cms#7923.

![CleanShot 2024-07-08 at 10 38 11](https://github.com/statamic/ideas/assets/19637309/5f565704-376c-48f7-b0a2-d78822bc88f4)
