### ISSUE TITLE
Save button position

### ISSUE THREAD

**Issue by jasonvarga** [statamic/ideas#336]
On "content" forms we have the save button at the top.

On "configuration" forms we have them at the bottom.

The justification was because you might frequently go to the content form to edit a single thing and quickly leave.
On configuration pages we want you to definitely see all the fields so you have to scroll past everything.

Some people disagree with this UX decision.

**Comment by patrickhoehn** [comment]
@jasonvarga, how about having save buttons on top and bottom or a floating button? On very long pages it gets kind of annoying if you have to scroll to the top first, hit save, scroll back down, make changes, scroll up, hit save

**Comment by jackmcdade** [comment]
They'll all be at the top in 4.0. https://github.com/statamic/cms/pull/7600
