### ISSUE TITLE
FR: Content Model and Routing step improvements

### ISSUE THREAD

**Issue by mikemartin** [statamic/ideas#34]
As users are still learning the new concepts introduced in V3, it would be help to reiterate the purpose and importance of Blueprint and Structures in the Create Collection wizard.

1) Could add the dashboard definition for the Blueprint field.
> Blueprints define the custom fields used to create and store your content.

<img width="1038" alt="Screen Shot 2019-10-25 at 1 35 37 pm" src="https://user-images.githubusercontent.com/414211/67538947-68c6ee00-f72c-11e9-9e39-ce9d3e9378b9.png">

2) Same goes for the Structure field in the Routing step.

> Structures establish the heirarchy of your pages and help you manage your site navigation.

<img width="1014" alt="Screen Shot 2019-10-25 at 1 42 38 pm" src="https://user-images.githubusercontent.com/414211/67539289-5dc08d80-f72d-11e9-8e10-743f9b4a356f.png">

3) It would also be useful to know which fields are required and which are optional. As I understand it, a Blueprint is required and a Structure is optional. Is that right?

**Comment by jasonvarga** [comment]
Irrelevant now.
