### ISSUE TITLE
Allow Actions to run javascript (or open a new window)

### ISSUE THREAD

**Issue by edalzell** [statamic/ideas#342]
In our use case, of creating a URL that allows folks to review draft content, it would be ideal if we could copy that URL to the clipboard so they could then share it.

Alternatively, if we could open a new window instead of a redirect, that would be a good second-choice.

**Comment by edalzell** [comment]
This might be better as two issues.

**Comment by jesseleite** [comment]
If an action could run javascript, theoretically you could have it open a modal, a stack, a panel, etc.  One issue seems good for now 👍

**Comment by jonassiewertsen** [comment]
This feature would be really useful.
