### ISSUE TITLE
Possible user provider conflict when using the "file" users repository on existing app

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/ideas#345]
I'm just wondering if this is safe... If I want to use the "file" method for storing statamic users then can I define two Laravel User Providers with the same name? Example:

```
'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],

        'users' => [
            'driver' => 'statamic'
        ],
    ],
```

To me this seems like it might cause problems. I haven't run into any yet but maybe somebody knows better?

If it is a problem then perhaps we need a config variable to define a custom Statamic user provider? Example:

```
//config/statamic/auth.php
    'repository' => 'file',
    'provider' => 'statamic_users' // New config variable

//config/auth.php
  'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],

        'statamic_users' => [
            'driver' => 'statamic'
        ],
    ],
```

**Comment by damcclean** [comment]
May be related to statamic/cms#2391

**Comment by jasonvarga** [comment]
Closing in favor of https://github.com/statamic/cms/issues/2391
You can't have multiple providers.
