### ISSUE TITLE
Specifiy site(s) when getting entries of collection

### ISSUE THREAD

**Issue by gefangenimnetz** [statamic/ideas#346]
### Suggestion
Add a parameter to the `{{collection}}` tag e.g. (sites) that allows one to specify the sites where you want to get the entries from (only the current one when parameter is omitted) to get collection entries from multiple sites at the same time.

### Reasoning
You have a multilingual website (German + English). Almost every content is translated and basically a copy of another page (origin: xyz). This website also has a blog (collection). A lot of the blog posts (collection entities) are only available in a certain language (not linked via origin) – in the Blog page you want to list all of the posts no matter what language they are. Or even more specific: On the German Blog you want to list both German and English posts however on the English Blog you only want to list English posts.

Another use case we currently actually have: Online trainings (webinars). Some of them are in English some of them in other languages. On the home page all of them shall be listed, no matter in what language they are – of course they get a little country flag ;)

We could then filter out all the entries that are just translations (have an origin) to make sure we do not show the same entry multiple times.

### Example
Get all entries from collection _blog_ in the sites with handles _default_ and _english_ but filter out the translations (entries with an origin)
`{{collection:blog sites:in="default|english" origin:doesnt_exist="true"}}`

---

If there is a way to archive this already I’d really appreciate your help here.

**Comment by jasonvarga** [comment]
At the moment you can do `site="english"`, but it only supports a single site.

Ideally you could just do `site="default|english"` like you mentioned.

A workaround for now would be to do `site="*" site:in="default|english"`
(The `*` makes the tag avoid the built in site filtering, then `site:in` is just a manual query condition)

**Comment by gefangenimnetz** [comment]
```antlers
{{ collection:blog_posts site="*" site:in="default|english" origin:doesnt_exist="true"}}
```
I was not aware that `site` is available at this level – and can be used as a parameter. I just read up on the documentation; site is a system variable and because of how the cascade works available in the view, right?

In my point of view this issue/idea can be closed @jasonvarga, since the workaround does not feel much like a workaround at all to me but is an actual solution ;)

Thank you very much!
