### ISSUE TITLE
Cache tag `key` param

### ISSUE THREAD

**Issue by jesseleite** [statamic/ideas#349]
Add ability to customize cache `key` when using cache tag in antlers...

```
{{ cache key="breakfast" }}
    ...
{{ /cache }}
```

This way, devs can handle their own cache invalidation using event handlers, etc. in PHP land.

**Comment by damcclean** [comment]
This issue can be closed now as the PR has been merged and released.

**Comment by jesseleite** [comment]
Rad 🤘
