### ISSUE TITLE
Add Purpose to Create Structure screen

### ISSUE THREAD

**Issue by mikemartin** [statamic/ideas#35]
The starting screen for **Create Structure** might be an opportunity to introduce the concepts of Collection and Navigation structures. It would help solidify the user's understanding of how Structures can be used, and would also reduce the amount of steps in the following Wizard flow.

This could be a useful pattern for other Create screens such choosing how Collections should be ordered.

<img width="856" alt="Screen Shot 2019-11-20 at 11 34 02 am" src="https://user-images.githubusercontent.com/414211/69198852-4472fb80-0b8a-11ea-9ae2-6334ebfa66da.png">

**Comment by jasonvarga** [comment]
Irrelevant with new structure changes in beta 20.
