### ISSUE TITLE
Multisite site switch

### ISSUE THREAD

**Issue by Pfeifakopf** [statamic/ideas#352]
Should multisites only be used for different languages or could it be used for subsites with different content, but with the same template/theme? 

A use case could be for branches and product-sites. But in this cases, the site switch on the sidebar is confusing, because the sites should not be linked to each other and the sites should not be generated, when someone clicks on an other site.

If you have multiple branches with different languages, it's getting more confusing. It would be helpful, if there would be a setting that allows to link depending sites and just show them in the sidebar instead of showing all.

```
Sites
| - 
  | - Branch 1
| - 
  | - Branch 2 Lang 1
  | - Branch 2 Lang 2
| - 
  | - Branch 3 Lang 1
  | - Branch 3 Lang 2
```

**Comment by jasonvarga** [comment]
Sounds like #17
