### ISSUE TITLE
Bard toolbar sticky/fixed in fullscreen mode

### ISSUE THREAD

**Issue by robdekort** [statamic/ideas#354]
It would be usefull to have a sticky toolbar in full screen mode. Currently you have to scroll all the way down, select something, scroll up and use the toolbar.
![bard](https://user-images.githubusercontent.com/69107412/94913798-282e3380-04aa-11eb-9bf9-27b008e45fa7.gif)

**Comment by jackmcdade** [comment]
It's definitely sticky already. 🤘

**Comment by robdekort** [comment]
Not here! Due to it being in a replicator maybe?

**Comment by robdekort** [comment]
See the gif, I just tested and it seems to still be doing that.

**Comment by jackmcdade** [comment]
You never said anything about a Replicator 😆  Totally different test.

**Comment by robdekort** [comment]
Any

**Comment by jackmcdade** [comment]
But...but it works on my machine...

**Comment by robdekort** [comment]
🤷🏻‍♂️ 

Just sent you a DM with a vid and install instruction if you wanted jump in this rabbit hole.

**Comment by robdekort** [comment]
Do you know why it worked on your machine? You were probably already running the latest update (3.0.46) that fixed it. It now also works on my machine :-).

**Comment by jackmcdade** [comment]
Huzzah!
