### ISSUE TITLE
Ability to customise text for creating new collection items through widgets

### ISSUE THREAD

**Issue by MikeHarrison** [statamic/ideas#358]
It would be great to be able to customise the text displayed in widgets to create new items in collections. Currently I have the following Collection widgets in my dashboard, which are displaying the following text:

```
Blog            => 'New Blog'
Pages           => 'New Contact' (this looks to be lifting the name of the first blueprint used in the collection)
Projects        => 'New Projects'
```

This 'Add new entry' text customisation could be part of the "Configure Collection" setup.

**Comment by jackmcdade** [comment]
Covered in https://github.com/statamic/cms/pull/7217.
