### ISSUE TITLE
Enhance the locales tag (improved locale switching)

### ISSUE THREAD

**Issue by FlorianMoser** [statamic/ideas#359]
As discussed in Discord, I suggest to add the following enhancements to the locales tag:

1. Add a parameter for the "site" wildcard. Currently a specific locale can be added to the locales tag to return only locale data for a specific site: `{{ locales:fr }}`. With an additional parameter we could also use variables to set the site handle: `{{ locales :site="my_handle" }}`.

2. Currently, the locales only returns results for locales, the current page has been translated for. If you use the locales tag as a language switcher, you get an inconsistent list of locales, if not all pages are translated. This could be circumvented by always returning all locales as array key and a value of NULL, if there is no translation. Or by adding a "filter" parameter to the locales tag, that can be set to TRUE or FALSE.

**Comment by jasonvarga** [comment]
You can use `{{ sites }}` to loop over all sites regardless of whether the item has been translated.
