### ISSUE TITLE
Dump data after augmentation has taken place

### ISSUE THREAD

**Issue by damcclean** [statamic/ideas#362]
I wish it was possible to dump variables after the augmentation has taken place, rather than before when you just get the `Value` object.

This might already be implemented but I couldn't find anything about it in the documentation.

**Comment by jasonvarga** [comment]
Dumping the individual field will show the augmented version.

ie. `{{ dump }}` shows everything as `Value` objects.
`{{ title | dump }}` or `{{ dump:title }}` will show the augmented value.
