### ISSUE TITLE
Output array from custom tag as var rather than iterable tag pair

### ISSUE THREAD

**Issue by jesseleite** [statamic/ideas#364]
If I make a custom antlers tag and return an array of data, I know we can iterate over using a tag pair:

```
{{ my_tag_array_data }}
    {{ title }}
    {{ author }}
{{ /my_tag_array_data }}
```

But what if I want to pass that data into a vue component:

```
<my-component :some-prop='{{ my_tag_array_data | to_json }}'>
```

Maybe the user could explicitly set `$isPair = false` in the custom tag, or maybe antlers could detect if modifiers are used?We

**Comment by jasonvarga** [comment]
Another idea I had could be a `Variable` class that works similar to a `Tags` class, but doesn't have parameters.

Any parameters on it would actually be treated like modifiers.

``` php
class MyVariable
{
  public function value()
  {
    return 'something';
  }
}
```
```
{{ my_variable | upper }} // SOMETHING
```
