### ISSUE TITLE
Clear cache from url?

### ISSUE THREAD

**Issue by MikeHarrison** [statamic/ideas#369]
Hi,

This may have issues / consequences unforseen by me, but I think it might be a useful feature to be able to clear the cache via a url? I work with a lot of different clients on shared hosting etc. where it is a pain to get SSH access. I hit the `Call to a member function selectedQueryColumns() on null` error fairly regularly when pushing changes to a site, and then it is a bit of a rigmarole to get access to clear the cache.

If I could go to https://clientsite.com/cp/cache/clear to clear the cache (provided I was logged in), this would save a fair bit of bother.

As I said, just a thought, and may have issues attached to it, but I thought it might be nice.

**Comment by jackmcdade** [comment]
Good news – it already exists!

/cp/utilities/cache

![image](https://user-images.githubusercontent.com/44739/96872655-e86fc180-1441-11eb-9b6e-bef37ab7b73a.png)

**Comment by MikeHarrison** [comment]
Hi Jack,

Thanks for the quick reply. Yep I have seen that, but when I am hitting that cache error above I can't access that page at all, or any of the cp or site. So my thought was a URL that when you hit it clears the cache. If that makes sense!

**Comment by jackmcdade** [comment]
Ah I see. That would be very dangerous because it would allow someone with knowledge of that URL to DDOS your site as the cache rebuild process is the most intensive request. You could probably write a little tiny addon that did this on a hidden URL only you knew about I suppose?

**Comment by MikeHarrison** [comment]
Ah yes that sounds like a super bad idea, thanks for indulging me!
