### ISSUE TITLE
Add a WP-like Multisite implementation

### ISSUE THREAD

**Issue by morhi** [statamic/ideas#374]
The current multisite implementation is more like a switch to provide the same page in multiple languages. The translations may be accessed through a different subdomain, subfolder or another domain. However, I have a website request, which has more complex requirements and I don't have a good idea how to make this with Statamic.

This is the current situation and the requirements:
- The project owner is a company with multiple branches
- Each branch operates independently from each other
- Each branch needs to have an independent website, in terms of creating independent content, but with the same templates / blueprints etc.
- Each branch needs to have its own domain
- Users should be global, but it needs to be possible to give them rights to specific branches
- Everything except the content should be global like blueprints, fieldsets, templates, but should be extendable or overridable for a specific branch

Do you have an idea how to implement with the current Statamic features, is it currently not possible or would you add this features under a new feature name? It is possible to use the WP Multisite feature for this project, but I don't want to use WP but Statamic, of course.

Looking forward to your thoughts!

**Comment by aerni** [comment]
If I understand correctly, those sites are completely independent except for the basic structure of blueprints, fieldsets, templates, and global users. 

I'm just thinking aloud and this is not tested. I'd probably look into a monorepo. Create a fresh installation for each site in a subfolder. And then symlink the shared files and folders to a shared folder outside the site's folder. This way you can share all the settings, blueprints, etc. but still have independent content.

**Comment by jasonvarga** [comment]
I'd go with what aerni has suggested. These sound like completely independent sites except for a few things.
