### ISSUE TITLE
No option to use pagination parameter on search results

### ISSUE THREAD

**Issue by padders** [statamic/ideas#375]
Hi Guys,

It looks like there is no option to use pagination on search results, it just has a limit and an offset. I could do the pagination manually but you have a lovely parameter for collections and taxonomies which would be great if it was added to the search function.

Something like this...

```
{{ search:results paginate="12" }}
   {{ if no_results }}
      <h2>No results.</h2>
   {{ else }}

      <a href="{{ url }}" class="result">
         <h2>{{ title }}</h2>
         <p>{{ content | truncate:240 }}</p>
      </a>

      {{ paginate }}
         {{ partial src="partials.paginate" }}
      {{ /paginate }}
   {{ /if }}

{{ /search:results }}
```

Cheers :)

**Comment by jasonvarga** [comment]
Supported since 3.0.30
