### ISSUE TITLE
Get current user with API

### ISSUE THREAD

**Issue by mikemartin** [statamic/ideas#381]
For many sites I'll often show the current user's account menu with the `loggedin` and `user` tags. 

Could the Statamic API have an endpoint for `/users/current` to expose the current users details? (name, email, photo) 

I've built my own route and controller to do this in the meantime.

routes/web.php
`Route::middleware('api')->get('/!/user/current', 'CurrentUserController@index');`

app/Http/Controllers/CurrentUserController.php
```php
<?php

namespace App\Http\Controllers;

use Statamic\Facades\User;

class CurrentUserController
{
    public function index()
    {

      $user = User::current();

      if (!$user) {
        return [
          'loggedIn' => false
        ];
      }

      return [
        'loggedIn' => true,
        'email' => $user->email() ?? null,
        'name' => $user->get('name') ?? null,
        'photo' => $user->get('photo') ?? null,
      ];
    }
}
```

**Comment by jasonvarga** [comment]
I don't think this is something we'd want to expose by default. A route that people would know exists on every Statamic site that exposes user info sounds like an accident waiting to happen.

We'd probably also need a way to customize exactly what user data is shown on the route. At that point, you might as well just make the route you've already created. As you've shown, there's not much to it!
