### ISSUE TITLE
Git Integration branch config

### ISSUE THREAD

**Issue by callum-veloxcommerce** [statamic/ideas#383]
Please consider the following proposal for a configuration property to allow env file and config file to control which branch the statamic site pushes to as it seems to default to master. I am using reset head to deploy my branch to my server and i need to choose which branch to push the updates to as it is pushing everything to master.

Add to config/git.php:
```
    /*
    |--------------------------------------------------------------------------
    | Git Branch
    |--------------------------------------------------------------------------
    |
    | The checked out git branch to push changes to. Defaults to master.
    |
     */
    'branch' => env('STATAMIC_GIT_BRANCH', 'master'),
```

Replace push() in src/Console/Processes/Git.php:
```

    /**
     * Git push.
     *
     * @return null
     */
    public function push($branch = 'master')
    {
        return $this->runGitCommand('push', 'origin', $branch, '--porcelain');
    }
```

Replace push() in src/Git/Git.php:
```
    /**
     * Git push tracked content for a specific repo.
     */
    protected function push($gitRoot)
    {
        GitProcess::create($gitRoot)->push(config('statamic.git.branch'));
    }
```

**Comment by jasonvarga** [comment]
@jesseleite  Why do we specify the branch at all? Can't it push to HEAD?

**Comment by jesseleite** [comment]
@jasonvarga That is exactly what we currently do... https://github.com/statamic/cms/blob/8cea1834f12b9be2878a2832ecba32baf86d52e8/src/Console/Processes/Git.php#L28-L36

@callum-veloxcommerce I'm curious on your use case for pushing to a different branch?

**Comment by jasonvarga** [comment]
I misread the comment. I thought his suggestion was our current code.

**Comment by jesseleite** [comment]
Think we're going to close this for now, as we don't want to over-complicate the git feature by encouraging diverging content branches. It could get messy if people start enabling git in multiple environments with push configured to different branches.

If you want people pushing content that is not ready for production, I might suggest they save their entries as drafts, or maybe even utilitize Statamic's revisions system 👍
