### ISSUE TITLE
List Fieldtypes from left to right

### ISSUE THREAD

**Issue by goellner** [statamic/ideas#384]
Its hard to find the correct fieltype, if the fields are sorted top to bottom, I think it's better UX, if they are from left to right. 
![Screenshot on 2020-11-09 at 15-40-02](https://user-images.githubusercontent.com/3986748/98555361-23774f00-22a2-11eb-8862-f5aa747b8c01.png)

**Comment by jackmcdade** [comment]
We used to have it left to right and folks were saying it would be easier if they were sorted in columns lol 🤔

**Comment by goellner** [comment]
i thought it was different a while back, this is maybe just a personal preference, hard to say

**Comment by jackmcdade** [comment]
You could add the following CSS to [customize your own control panel](https://statamic.dev/extending/control-panel#adding-css-and-js-assets):

```
.fieldtype-list {
    grid-template-columns: repeat(4, 1fr) !important;
    grow-auto-flow: row;
}

```
Result:
![image](https://user-images.githubusercontent.com/44739/98558700-bbaa0f80-2273-11eb-81ff-04ce51249526.png)

**Comment by goellner** [comment]
will do that, a UX designer just told me to maybe increase the column gap: 
![Screenshot on 2020-11-09 at 16-07-35](https://user-images.githubusercontent.com/3986748/98558889-43107680-22a6-11eb-9303-edd87707ab5a.png)

then it would be easier scannable as columns

**Comment by jackmcdade** [comment]
Oh yeah I like that, nice one!
