### ISSUE TITLE
Add "Text Only" as an option on the "Add Link" dropdown for Navigations

### ISSUE THREAD

**Issue by MikeHarrison** [statamic/ideas#387]
Hi,

I just got stuck for a while trying to work out how to add a "text only" item in a navigation. I did work it out eventually but I think having it as an option within "Link to URL" is a bit confusing.

I think it might be simpler to understand if in addition to "Link to URL" and "Link to Entry" in the dropdown under "Add Link" there was also "Text Only" (or something similar).

Below is a mockup of what I am proposing.

<img width="270" alt="Screenshot 2020-11-12 at 12 34 52" src="https://user-images.githubusercontent.com/6464063/98940829-7c81f580-24e3-11eb-8833-f6865aaaaf23.png">

Thanks!

**Comment by jackmcdade** [comment]
Added a little white ago 👍
