### ISSUE TITLE
Field Classes

### ISSUE THREAD

**Issue by crackAT** [statamic/ideas#388]
Hi, 

i want to add some styling to some fields in the edit mode of a collection entry but it is a little bit difficult, because there are only general field class names in the parent div and it is not possible to style special field "variables" easily. 

It would be great, if you can add custom class or a classname with the field variable to the parent div.

![image](https://user-images.githubusercontent.com/6299060/99070327-49f1fe80-25b0-11eb-86c9-7ef117b4efd2.png)

Thanks

**Comment by jackmcdade** [comment]
Good idea! In the next update each wrapper div will have a classname based on the handle: `publish-field__handle-name`.
