### ISSUE TITLE
Allow content without slug

### ISSUE THREAD

**Issue by robinvdvleuten** [statamic/ideas#390]
I'm building a website where I have a lot of content that is not displayed as a `page` itself, but embedded on multiple pages. These content entries have a similar title, but a variance in other fields. One of these content types is for example an agenda of gigs, where the title is the venue location. So this band can have multiple gigs on the same location (thus same title), but different dates. 

As the slug (and filename) is automatically generated from the title, I get a lot of duplicate slug errors. It would be nice to have some content to be marked as `non accessible through url` and have an UUID used for generating the filename.

**Comment by robinvdvleuten** [comment]
An entry for carousels is also weird to have slugs.

**Comment by Hesesses** [comment]
Vote for this, for example if slug is not set / disabled it would be autogenerated UUID
