### ISSUE TITLE
Right-justify counts in Listings (+ digit group separator?)

### ISSUE THREAD

**Issue by sauerbraten** [statamic/ideas#395]
To improve readability, counts, for example showing how many entries are in a collection on /cp/collections, should be right-justified in their columns.

Also, we have more than a million entries in one collection, so it would be nice to have those number using a (locale aware) digit group separator: 1,023,543 in US, 1.023.543 in German. (Maybe only use a group separator for numbers > 10000 only, since 9583 might still be more readable than 9,583?)

**Comment by jackmcdade** [comment]
This is done 👌
