### ISSUE TITLE
Improve content-api in multi-site installations

### ISSUE THREAD

**Issue by gefangenimnetz** [statamic/ideas#396]
We are running a multi-site installation for translations. I was under the assumption that the content-api would reflect the different sites in the results. However I experienced two issues:

1. `collection/entries` returns all entries, no matter in what site they have been created. Only way to tell them apart is to "work" (workaround/hack) with filters like `/entries?filter[url:contains]=en-us` That does not feel right to be honest.

2. One cannot get globals from a different site but the default. As far as I can tell `/globals` only returns the global set of the default page.

**Comment by jasonvarga** [comment]
You can do `?filter[site]=handle` to get entries in a specific site.

As for globals, you're right. It just gets the default at the moment.

**Comment by gefangenimnetz** [comment]
?filter[site]=handle works! Thank you @jasonvarga 
please feel free to close this issue/idea. I will open an issue about the globals in the cms repo.
