### ISSUE TITLE
Allow ability to hook into users blueprint

### ISSUE THREAD

**Issue by jelleroorda** [statamic/ideas#400]
What is quite neat in my opinion is the following snippet from the `Statamic\Http\Controllers\CP\Users\UsersController@edit` (with also code going along in the update method of course):

```php
$blueprint = $user->blueprint();

if (! User::current()->can('edit roles')) {
    $blueprint->ensureField('roles', ['read_only' => true]);
}

if (! User::current()->can('edit user groups')) {
    $blueprint->ensureField('groups', ['read_only' => true]);
}
```

Would it be possible to add an event to the `edit` and `update` method of the controller, so we can add extra fields that may be read-only for some users, and editable for others in the same way?

**Comment by jasonvarga** [comment]
Keep an eye on https://github.com/statamic/cms/pull/2983
