### ISSUE TITLE
Ask for overwrite assets

### ISSUE THREAD

**Issue by wm-simon** [statamic/ideas#401]
Please add a dialog for asking, if assets should be replaced or the new renamed, when they already exist.

**Comment by piljac1** [comment]
Yes please! +1

**Comment by rrelmy** [comment]
This would be very handy, we often get asked for it.

Personally I would also like to have a check if the file is identical and just ignore it, often we see the same asset uploaded multiple times

**Comment by paul-hph** [comment]
🙏
