### ISSUE TITLE
php please multisite broken

### ISSUE THREAD

**Issue by dwainscheeren** [statamic/ideas#403]
I got a fresh new installed Statamic project and I wanted to create a multisite out of it. I get the error 
![ss+(2020-12-08+at+05 06 28)](https://user-images.githubusercontent.com/3868853/101508302-c7264e80-3977-11eb-96a7-0fadc1616558.png)

**Comment by dwainscheeren** [comment]
When I try to use the command again I get an error `Command may have already been run. Did you update your config/statamic/sites.php file? `

**Comment by damcclean** [comment]
This bug has already been reported in statamic/cms#2802.

**Comment by jasonvarga** [comment]
Please report bugs to the actual repo. https://github.com/statamic/cms
