### ISSUE TITLE
Allow for managing non-content blueprints in the CP

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/ideas#408]
Say I create a `bacon` blueprint in `resources/blueprints` with all the fields etc. Inside an addon, or anywhere else, I can get that blueprint by doing `Blueprint::find('bacon')`.

However, if I wanted to go and update that blueprint with a new field or whatnot from within the Control Panel, I can't. My new blueprint doesn't show up at all.

![image](https://user-images.githubusercontent.com/19637309/102127953-0efc1880-3e45-11eb-8748-d29d3091902f.png)

Ideally the `bacon` blueprint would show under the 'Other' heading and you'd be able to edit it like any of the other blueprints.

I believe this was how it used to work in v3 prior to blueprints being refactored a while back. I'm happy to have a go implementing this if it's something the gents would be interested in.

Related: #644

**Comment by jackmcdade** [comment]
I would 100% merge a PR on this!

**Comment by damcclean** [comment]
Sweet!!!

**Comment by Skullbock** [comment]
Hey, tried to solve this in https://github.com/statamic/cms/pull/3963 :)

**Comment by duncanmcclean** [comment]
Handled in statamic/cms#8516
