### ISSUE TITLE
Using the config to determine supported FieldTypes in Forms

### ISSUE THREAD

**Issue by myleshyson** [statamic/ideas#409]
Currently it doesn't seem like there is a way to hook into [this line](https://github.com/statamic/cms/blob/10671666088c164f659a7c7f016928f9d5e4d299/src/Http/Controllers/CP/Fields/FieldtypesController.php#L36) to add a custom field to forms.

It would be nice if the array in that `supportedInForms` method was replaced with something like 
```php
 private function supportedInForms($fieldtype)
 {
     return in_array($fieldtype, config('statamic.forms.supportedFields'));
 }
```

For context, I'm trying to add a `Phone` field to a registration form that masks the input as the user types.

I think this is probably somewhat related to #355.

**Comment by albaur** [comment]
Is there already a timeline if and when this feature will bi done?

**Comment by jasonvarga** [comment]
There's no timeline at the moment. A pull request is an option.

You're free to use your own fieldtype directly in the yaml though. The only thing this feature is blocking is being able to choose your fieldtype through the UI.
