### ISSUE TITLE
Enable custom field types to not have a title

### ISSUE THREAD

**Issue by edalzell** [statamic/ideas#410]
Use is that we have created a button that exposes a "draft" url and when it's added to the fieldset it shows up like this:
<img width="271" alt="image" src="https://user-images.githubusercontent.com/6069653/102277741-91d0b200-3edd-11eb-9dd4-de8cd3185490.png">

Would be amazing if we could not have that `Drafts` title there.

Maybe a config on the field type?

**Comment by jasonvarga** [comment]
This is essentially #357
