### ISSUE TITLE
static caching to exclude pages using regex

### ISSUE THREAD

**Issue by JeremyDunn** [statamic/ideas#419]
Right now you can only use a wildcard to exclude URLs matching the last part of the URL. 
https://statamic.dev/static-caching#excluding-pages

It would be nice to use regex for exclude rules for better flexibility.

_I'd be happy to work on a PR for this if this is something others are interested in._

**Comment by duncanmcclean** [comment]
You're now able to create your own "excluder class" to determine which URLs should be excluded from the static cache. [See the docs](https://statamic.dev/static-caching#excluding-pages).
