### ISSUE TITLE
CP asset file browser would be better if it had the ability to go back one folder

### ISSUE THREAD

**Issue by nn-dmt** [statamic/ideas#420]
Hi,

Either going back one folder, or going up one directory in the hierarchy like most FTP clients have - right now, need to click asset link from menu again, clicking back does not force reload the page data.

Either a folder at the top named ".." to go up one level, or a back button, would be beneficial.

EDIT: The asset browser when making an entry does in fact have the ".." at the top of the folder structure to go back one level, but it doesn't seem to exist in the asset browser directly in the CP

**Comment by jasonvarga** [comment]
The dotted folder is there everywhere, as far as I can tell. If it's not, this might be a bug. Please open an issue in statamic/cms with more details on exactly where you're (not) seeing it.
