### ISSUE TITLE
Save current date on entry save as default

### ISSUE THREAD

**Issue by tofraweb** [statamic/ideas#423]
Hi, the users on the cp complain that they need to pick the current date (today) on every new entry save. Is there a way to save  the current data as default without the need to pick the date? The current date is populated in the field but when trying to save the entry, the 'date field is required' message shows up.

**Comment by damcclean** [comment]
Hi, this sounds like a bug rather than a feature request. Could you [create an issue](https://github.com/statamic/cms/issues/new?assignees=&labels=&template=bug_report.md&title=) on `statamic/cms` instead and close this one?

**Comment by tofraweb** [comment]
Will do that. Thanks for the quick response.
