### ISSUE TITLE
Update query string with CP entry listing filters

### ISSUE THREAD

**Issue by johncarter-** [statamic/ideas#426]
It would be great if we could have the query string updated with the filters when on a collection entry listing view in the CP. 

Having to type the search every time I go to an entry then back to the listing seems to be a good default, but maybe its just me.

**Comment by jasonvarga** [comment]
Basically #93 

Just a tip, you can create presets so at least it'll be a single click to get back to a search/filter(s) combo rather than having to manually redo it every time.

![image](https://user-images.githubusercontent.com/105211/103785064-c29d9600-5008-11eb-9e48-557b7c4084e0.png)

**Comment by johncarter-** [comment]
Thanks Jason.

It was more to do with a temporary, browser back button situation rather than something that I would want persisted to my user preferences.

**Comment by jasonvarga** [comment]
I understand. Just giving you a workaround until your actual request is done.

**Comment by johncarter-** [comment]
Gotcha. Thanks mate.
