### ISSUE TITLE
Automatically show single Collection/Global in Control Panel Navigation

### ISSUE THREAD

**Issue by sjclark** [statamic/ideas#429]
Default to linking directly to the Collection/Global when there is only one a single child item.

Had a chat to Erin - we both thought this was in V2? Seems to already work for Assets.

<img width="1000" alt="Screen Shot 2021-01-08 at 10 59 43 am" src="https://user-images.githubusercontent.com/4531017/103974726-87e15c80-51c6-11eb-8ae1-5bacaaddd08a.png">

**Comment by jasonvarga** [comment]
The index page is where you manage them, too. Creating new ones, deleting them, etc.

**Comment by sjclark** [comment]
I guess I didn't really mind how that stuff was structured under V2. It's very rare (for me) that I'm making a new collection or, global etc **independent** of having to be in other settings like Fieldsets etc. So i didn't really mind that stuff being buried away within settings.

But can understand the limitation above now.
