### ISSUE TITLE
FR: Option for users to only edit their own entries

### ISSUE THREAD

**Issue by bartrylant** [statamic/ideas#436]
This is a feature I miss and it has been a dealbreaker for me to use Statamic on a few projects.

Often I have a website with a news section, where multiple authors can post news entries. Right now, I only have two options:

- give a user permission to edit all the entries in the "news" collection
- give a user no permissions at all to edit any entry in the "news" collection

What I need (and use a lot with websites) is

- give a user permission to edit his own entries in the "news" collection, but not entries in the "news" collection by other authors

**Comment by johncarter-** [comment]
Think this is due to be released in 3.1.

I heard thatbis due to drop in the next week or so.

**Comment by damcclean** [comment]
Indeed. Like John says, you're in luck. It's gonna be part of 3.1. There's a pull request you can watch over here: statamic/cms#3053.

**Comment by bartrylant** [comment]
Great!
