### ISSUE TITLE
License validation: Please add .intra to dev-related TLD list

### ISSUE THREAD

**Issue by mmodler** [statamic/ideas#444]
> Does it use a dev-related TLD? .local, .localhost, .test, .invalid, .example, or .wip

License Validation:

Please add .intra to dev-related TLD list so we don't have to change our internal vm infrastructure using hosts like vm1.companyname.intra :)

.intra is no public TLD so it should be no problem?

Thank you!

**Comment by jackmcdade** [comment]
Done and done.
