### ISSUE TITLE
Bard field with no buttons

### ISSUE THREAD

**Issue by goellner** [statamic/ideas#446]
After deselecting all bard buttons, then the defaults are shown, since it is not saving anything in the fieldset config. 

Also a select/deselect all button would be nice in the fieldset builder.

**Comment by goellner** [comment]
just ran into this again today. i set up everything with bard, even if I don’t need to edit options. when a need for inline links comes up, i only have to enable it. and a button to deselect all, would speed things up a lot. i keep the remove formatting button most of the time as a workaround, but have to deselect all other options every time.

**Comment by jackmcdade** [comment]
We have this now, it's `inline` mode.
