### ISSUE TITLE
Option to hide focal point button for images

### ISSUE THREAD

**Issue by timojokinen** [statamic/ideas#448]
My team uses statamic as headless cms for our customers. 
Nuxt has recently introduced their image component which supports lazyloading, cropping, etc.. 
https://image.nuxtjs.org/

It also supports an automatic focal point feature via the gravity attribute when using cloudinary as a provider.
If we wanted to use this feature it would clash with statamics own implementation. The user could select a focal point in statamic but it would have no effect.

Therefore, it would be nice if we could toggle the focal point feature of statamic / hide the button when disabled, for the use with 3rd party image handling providers.

I can create a PR if this is something you would merge

**Comment by jasonvarga** [comment]
We'll accept a PR. You might also be able to work around it using some basic css.

**Comment by jasonvarga** [comment]
Will be in the next 3.0 release.
