### ISSUE TITLE
Ability to rename an assets folder

### ISSUE THREAD

**Issue by aerni** [statamic/ideas#449]
## Bug Description
You can't rename an assets folder in the CP. The action menu only allows deleting the folder.

## Extra Detail
<img width="613" alt="Bildschirmfoto 2020-11-20 um 15 59 50" src="https://user-images.githubusercontent.com/23167701/99814559-6e6a4f80-2b49-11eb-899b-181e57d31d1c.png">

## Environment
Statamic 3.0.29 Pro
Laravel 8.15.0
PHP 7.4.12
aerni/social-links 2.1.0
aerni/zipper 1.2.0
jonassiewertsen/statamic-livewire 2.1.2
spatie/statamic-responsive-images 1.4.0
visuellverstehen/statamic-classify 2.0.0

**Comment by malteriechmann** [comment]
I would really like to see this feature coming.

**Comment by harry-burk** [comment]
I would also like this :)
