### ISSUE TITLE
Ability to edit Blueprint from content screen

### ISSUE THREAD

**Issue by edalzell** [statamic/ideas#45]
When building a site there is a lot of back and forth between content and blueprints.

Would be super great if we could hop into the blueprint, add/change a field then close and be back at a refreshed content screen with the updated Blueprint.

**Comment by jasonvarga** [comment]
Use two tabs! 💡

**Comment by edalzell** [comment]
Problem with that @jasonvarga is that, at least in Safari, a page reload on the entry doesn't seem to load the updated blueprint very well.

**Comment by jasonvarga** [comment]
Wha..?

**Comment by jackmcdade** [comment]
Is this still an issue? Seems fine to me!
