### ISSUE TITLE
Forms: Filter Form Submissions

### ISSUE THREAD

**Issue by SarahSibert** [statamic/ideas#450]
When working with the form submissions it would be useful to be able to filter the results by the different fields so that they can be used in different ways.

Say for example I had a form that enabled a user to upload information about animal food.  If the users could choose between dogs and cats in a dropdown, it would be then useful to filter by dog and cat when using the results.

**Comment by duncanmcclean** [comment]
This has been added in Statamic 5, which we're hoping to release in the next few days/weeks.

**Comment by hmalaud** [comment]
Has it been added to the latest version?
`{{ form:submissions in="my_form" sort="custom_field:desc" }}` doesn't seem to do anything.

**Comment by duncanmcclean** [comment]
Oh, it looks like we only added the filtering/sorting to the Submissions listing table in the Control Panel, not the tag.

I've opened a PR to add that: statamic/cms#10826

**Comment by hmalaud** [comment]
Wow that was fast, thanks! It's working on my local solution, maybe you might want to add `group_by` etc. support as well so that it behaves exactly like a collection?

**Comment by duncanmcclean** [comment]
> Wow that was fast, thanks! It's working on my local solution, maybe you might want to add `group_by` etc. support as well so that it behaves exactly like a collection?

I haven't tested it myself, but it uses all the same stuff as the collection tag under the hood so I wouldn't be surprised if that PR also adds support for `group_by` too.

**Comment by hmalaud** [comment]
Indeed! I tried yesterday but must have missed something because I got it to work today. Many thanks!
