### ISSUE TITLE
Return alt data when using the content API

### ISSUE THREAD

**Issue by RobbertUpgraders** [statamic/ideas#452]
When using the content api, assets do not get an alt attribute send with them. It would be awesome if this was returned so we can supply our image tags with proper alt attributes.

**Comment by jasonvarga** [comment]
You can override what's returned to the api by overriding the method as described here:
https://statamic.dev/extending/augmentation#shallow-augmentation

Although having `alt` there by default is probably fine.

**Comment by RobbertUpgraders** [comment]
> You can override what's returned to the api by overriding the method as described here:
> https://statamic.dev/extending/augmentation#shallow-augmentation
> 
> Although having `alt` there by default is probably fine.

HI Jason, I did not know you could override this, I asked this on Discord but they said this could not be done. 

I have read that documentation but I am still unsure as to where I would place this in the statamic file structure. Could you point me into the right direction?

**Comment by jasonvarga** [comment]
There's a link in the section I linked you to. Here: https://statamic.dev/extending/repositories#custom-data-classes
