### ISSUE TITLE
[GraphQL] Query entries by slug and URI

### ISSUE THREAD

**Issue by goellner** [statamic/ideas#456]
Would be nice to be able to query entries by slug and URI. Next.js for example loves slugs/URIs and it needs quite some workarounds to get a map of the ID to URI to work nicely with next.js

This method is important for static site generation: 

https://nextjs.org/docs/basic-features/data-fetching#getstaticpaths-static-generation

**Comment by jasonvarga** [comment]
You can do it by filtering at the moment, but it's pretty lame.

```graphql
{
  entries(filter: { slug: "foo" }) {
    data {
      title
    }
  }
}
```

**Comment by jasonvarga** [comment]
Done. Will be in 3.1 alpha2.

```graphql
{
  entry(url: "/foo/bar") {
    title
  }
}
```

```graphql
{
  entry(collection: "pages", slug: "bar") {
    title
  }
}
```
