### ISSUE TITLE
Enable use of CC/BCC for webforms

### ISSUE THREAD

**Issue by taylorcammack** [statamic/ideas#457]
We have a number of sites where we would like to conditionally send a CC/BCC email. 

AFAIK there's two methods to do this, but neither are great:

1. Adding a hidden field on the webform and always sending a second email. Unfortunately doesn't appear to work (not send an email) if the CC field is empty, so we'd have to put in a superfluous address.

![Screen Shot 2021-02-03 at 5 07 34 PM](https://user-images.githubusercontent.com/2514935/106821226-597a6400-6642-11eb-983d-0ec5a2df2dee.png)

2. Adding the logic directly into the form.yaml, which uses the already built-in CC/BCC ability. But we can't edit it later without blowing it up.

![Screen Shot 2021-02-03 at 4 47 41 PM](https://user-images.githubusercontent.com/2514935/106821342-947c9780-6642-11eb-91bd-16b7c0177d16.png)

If this already exists in some form or fashion and I missed it, please let me know. Thanks!

**Comment by taylorcammack** [comment]
Follow-up: I didn't actually check to see if the second method would work if it was edited in the CP – the CC field stays the same, which makes sense. Obviously if you remove the whole item, you'd have to re-add the field, but not bad.

So, the request is, add a CC field in the CP or, if the email address field is empty, it doesn't send anything. 🙏🏼

**Comment by duncanmcclean** [comment]
Did this get implemented?

**Comment by taylorcammack** [comment]
Sorry, closed inadvertently 😬
