### ISSUE TITLE
Bard single block/inline mode

### ISSUE THREAD

**Issue by jacksleight** [statamic/ideas#458]
Sometimes I want to be able to let users apply inline formatting/links to "single line" fields, for example adding links to image captions or highlighting words in an article title. While I could make these full Bard fields with only the inline formatting buttons enabled, you can still hit enter to create new paragraphs, and the output HTML would contain paragraph elements that need to be dealt with.

While it is pretty trivial to either strip the `<p>` tags out or adjust the styling with CSS on the frontend, I think it would offer a more predictable/intuitive experience for the CP user if there was a way to prevent Bard from allowing line breaks and paragraphs in the first place.

When output the HTML would simply be a single block of inline content:

```html
This is <em>my caption</em>, here's <a href="#">a link</a> to some other content
```

**Comment by jackmcdade** [comment]
I've looked into this and honestly don't think it's possible. Bard is built on top of Prosemirror/TipTap and the document schemas don't seem to support fragmented strings. Given that it's pretty trivial to work around and possibly extremely complex to build as a feature, I don't think we'll be tackling this one. Sorry dude!
