### ISSUE TITLE
GraphQL first batch of missing stuff / ideas

### ISSUE THREAD

**Issue by goellner** [statamic/ideas#459]
Entries:

- query by locale to get only entries from specific locale
- if no locale is set, then the graphql endpoint should return the default locale. not mixed entries
- enable sorting in parameters. sort by date, field, asc, desc, 
- optional Drafts

Entry: 
- query by locale to get only entries from specific locale

Nav: 
- query by locale (currently no way to get other locale than the default one)
- nav entry type. link to entry or custom link, makes it easier in the frontend to switch cases

Taxonomy: 
- query by locale (currently no way to get other locale than the default one)

Assets:
- a way to get specific image transforms (when using imgix, thats not necessary though)
- idea: assets should always return an array, even if its limit 1. its easy to get the first index in the frontend. if the limit changes, the returned structure stays the same

Errors:
- I have no idea, what the common rule is, but I think it should not return php exceptions in the response
- got an exception in the response, when i queried a GlobalSet, but only gave the site and not the handle

CMS:
- Headless mode, to set custom frontend url. but still use Statamic routing setup. I think just replacing the cms url with the custom frontend url should be fine. should be changeable for multisite too

GraphQL Settings:
- option to disable certain endpoints like users and user. if there is no authentification for now, at least they should be configurable, so no one can fetch all the user information of a site. i think most will use it without auth anyway, as it will most likely be used read only anyway

**Comment by jasonvarga** [comment]
I'm not responding to every single item right now, but here are a handful:

- You can already filter (by site, or any field.) [See docs](https://github.com/statamic/docs/blob/f05affb0b1ec3065c357fe5de9ca0ac7f69c38d0/content/collections/docs/graphql.md#filtering)
   ```graphql
   entries(filter: { site: "foo" })
   ```
- You can already sort. [See Docs](https://github.com/statamic/docs/blob/f05affb0b1ec3065c357fe5de9ca0ac7f69c38d0/content/collections/docs/graphql.md#sorting)
   ```graphql
   entries(sort: "field")
  ```

- > if no locale is set, then the graphql endpoint should return the default locale. not mixed entries
  
  I disagree

- > Optional drafts

  It would be nice to for it to be smarter, I agree. We can probably make that happen.
  For now you can use a filter to discard drafts. `entries(filter: { published: true })`

- > a way to get specific image transforms

  You can add  a custom field to different types. The [example in the docs](https://github.com/statamic/docs/blob/f05affb0b1ec3065c357fe5de9ca0ac7f69c38d0/content/collections/docs/graphql.md#custom-fields) does exactly what you're asking.

- > assets should always return an array

  We already have the convention established that if its multiple you get an array, if it's one you get the thing. I don't want to change that.

- > I think it should not return php exceptions in the response

  Exceptions are only shown if you have debug mode enabled.

- > option to disable certain endpoints like users and user

  You can write authorization logic [see docs](https://github.com/statamic/docs/blob/f05affb0b1ec3065c357fe5de9ca0ac7f69c38d0/content/collections/docs/graphql.md#authorization). Just return false for User and Users query to disable them.

**Comment by goellner** [comment]
in some endpoints its available as `site` right away and in others I need a filter. That would be just good to have the same way for all endpoints I think.

And I guess it is also a common convetion to only return published entries by default.

everyhing else: thanks, i should have read the documenation 🙃

I think its in a great state already and I will set up a multisite example with. blog posts and taxonomies to test things out

**Comment by jasonvarga** [comment]
> And I guess it is also a common convetion to only return published entries by default.

Only published entries will be shown by default in the next release (either alpha5 or beta1, not sure yet) statamic/cms#3349

> option to disable certain endpoints like users and user.

As of 3.1 alpha 4, you have to opt into each resource. Everything is disabled by default for security. See statamic/cms#3289

I'm gonna close this now, and you can feel free to open individual issues.
