### ISSUE TITLE
Save entries without triggering events

### ISSUE THREAD

**Issue by stephanbouman** [statamic/ideas#460]
Sometimes you wish that the EntrySaved event does not exist. Lets make that (sometimes) happen. 

On some projects, I run extra functions that are hooked onto the EntrySaved event. I have written a function that adds some extra calculated data to the entries markdown that is needed in my Algolia search index (eg. AbsoluteUrl, image url, related username). To store the data, i use $entry->save() within my event listener. Which runs the event again and pulls me in an infinite loop. Now i hacked my way around, but it would be much better if i can supress the events while saving, creating or deleting entries. 

I'm thinking of $entry->silently()->save()

![image](https://user-images.githubusercontent.com/67788644/107111859-a41efa80-6853-11eb-8db0-bef6975e5513.jpeg)

**Comment by fkwakkenbos** [comment]
Like in Eloquent (Lavavel 8) https://laravel.com/docs/8.x/eloquent#saving-a-single-model-without-events
