### ISSUE TITLE
Improve IDE autocompletion support

### ISSUE THREAD

**Issue by morhi** [statamic/ideas#461]
By now there are many methods in the `statamic/cms` repository, which are missing proper return types to provide correct autocompletion for an IDE.

For instance if there is a `$set` being an instance of `\Statamic\Globals\GlobalSet` the `in` method will return `mixed|null`, so that I have to manually set it to `Statamic\Globals\Variables`.

So my question is, is there a task in the roadmap for this issue? Is there need for help to add the correct function return types?

**Comment by jasonvarga** [comment]
We have docblocks throughout the codebase, but not everywhere. Feel free to contribute a PR.
