### ISSUE TITLE
Actions Remain Persistent / Always Visible (When Scrolling Long Pages)

### ISSUE THREAD

**Issue by kerns** [statamic/ideas#462]
It would be very helpful if it was not necessary to scroll to the top of the page in order to save an entry, and that once the main action button was scrolled passed it would re-attach in an anchored position at the top of the window in a position that was always visible. This is a common and very widely-used solution.

The problem is demonstrated here as the Save button disappears from view.

https://user-images.githubusercontent.com/20254/107253229-675f2900-6a36-11eb-877a-3c6f072a720b.mov

**Comment by jasonvarga** [comment]
Thanks! This is essentially #108 though.
