### ISSUE TITLE
Content API: Exclude unpublished by default

### ISSUE THREAD

**Issue by fjahn** [statamic/ideas#469]
Currently, fetching entries via the Content API also returns unpublished Entries. You can easily filter for published entries only with a query like so: `endpoint?filter[published]=true`.

However, I believe it would be reasonable that unpublished Entries are hidden by default. The original behavior could be brought back with `endpoint?filter[published]=*` or something similar. **This would be a breaking change**. However, I think the change would prevent more bugs than the current behavior causes now.

**Comment by jasonvarga** [comment]
This is being addressed in statamic/cms#3317 for 3.1
