### ISSUE TITLE
Add option to show all field handles

### ISSUE THREAD

**Issue by steveooo1** [statamic/ideas#47]
You guys added the feature to see the handle of a field by clicking on the field. This is great!

I oftentimes want to see all handles of the fields so manually clicking them can be a bit tedious.
An idea would be to make following logic:

1. Single click on field name reveals the handle of this field
2. Double click on a field name reveals all the handles

If 1. or 2. is active, a single click would reveal the field names again.

**Comment by dougstjohn** [comment]
You could also consider a keyboard shortcut to toggle them.

**Comment by steveooo1** [comment]
Yeah. I wrote this logic for Craft CMS and there I use a keyboard shortcut that toggles between showing all field names and the handles.

**Comment by jackmcdade** [comment]
What shortcut did you use @steveooo1? I have this stubbed out but can't quite decide on the right combo heh

**Comment by steveooo1** [comment]
Well, we used `CMD+SHIFT+Z` but the `Z` is the initial of our company name, so....

Maybe `CMD+SHIFT+S`? We had some issues to find the right shortcuts because some shortcuts trigger different stuff on Safari, Firefox or Chrome on Mac... So it should be tested on the browsers that it is working...

**Comment by steveooo1** [comment]
`S` for `show`?

**Comment by jasonvarga** [comment]
I propose a solution:

`Statamic.$keys.bind('s h o w m e t h e h a n d l e s', this.toggleHandles)`

**Comment by steveooo1** [comment]
`Statamic.$keys.bind('A p a r e c i u m', this.toggleHandles)`

**Comment by dougstjohn** [comment]
Is `h` or `H` already being used?

**Comment by steveooo1** [comment]
@dougstjohn Well, `CMD+SHIFT+H` does history-related stuff in each browser I tested (Safari, Firefox, Chrome).

**Comment by steveooo1** [comment]
I mean, if there isn`t a suitable shortcut, the version to click or double click on the handle is still a good one.

**Comment by jasonvarga** [comment]
Cmd+H hides the window
Cmd+Option+H hides other windows
Cmd+Shift+H opens my history bar in Firefox

Maybe we add a way to define your own shortcuts.

**Comment by steveooo1** [comment]
@jasonvarga This is some brilliant idea! Maybe have a global shortcuts config file with the key binding and the command that it triggers! So everyone could define their own ones! This is great and would be great for additional shortcuts throughout the system!

**Comment by jackmcdade** [comment]
What if we just had it toggle all of em when you click one?

**Comment by jasonvarga** [comment]
That’s probably the best and simplest solution.

**Comment by steveooo1** [comment]
@jackmcdade Yeah, that will do ;)

**Comment by jasonvarga** [comment]
Closing in favor of #302
