### ISSUE TITLE
Text align in Bard

### ISSUE THREAD

**Issue by Joe2824** [statamic/ideas#470]
It would be beautiful to align text inside bard without any plugin.

**Comment by jasonvarga** [comment]
If you've used a plugin for this, please link it.

**Comment by thisJerem** [comment]
TipTap 2 will have it built in and will be very soon be released, see here : https://github.com/ueberdosis/tiptap/issues/547#issuecomment-780886732
@jasonvarga Is Statamic a sponsor of tiptap and have an access to the closed beta ?
Here is the "alpha" align plugin : https://www.npmjs.com/package/@tiptap/extension-text-align

**Comment by duncanmcclean** [comment]
Even when TipTap 2 is released, I imagine it will be a while before Statamic updates Bard to support it.

**Comment by thisJerem** [comment]
Indeed Duncan, but it can probably be easier than a big refactor - as they said at least :) https://github.com/ueberdosis/tiptap#faq-should-i-start-to-integrate-tiptap-1-or-wait-for-tiptap-2
Nevertheless you're right it will break for people who created custom plugins for Bard exclusively.

In the meantime, here is a working solution for V1 : https://github.com/ueberdosis/tiptap/pull/544#issuecomment-648065624

**Comment by jacksleight** [comment]
With the upcoming upgrade to TipTap2 this should be fairly simple to implement with the official text align extension (https://tiptap.dev/api/extensions/text-align).

**Comment by jonassiewertsen** [comment]
This is the PR if anybody wants to follow the status
https://github.com/statamic/cms/pull/6043

**Comment by jacksleight** [comment]
This one can be closed 👍
