### ISSUE TITLE
Let us the $min_characters to trigger search

### ISSUE THREAD

**Issue by thisJerem** [statamic/ideas#472]
It would be super cool if the private variable inside cms/src/Search/Comb/Comb.php at line 43 could be retrieve an environment variable or config var.

For what raison ?
For one of my client, in CP I have a lot of location which have a slug or a title with only 2 characters (small zipcode for departemental region in France).
My client could filter by value in this taxonomy but searching with zipcode on "75" for exemple to display only Paris results is really much more quick !

Solution : replace the value in the comb.php file by a key called "env(MIN_CHARS_SEARCH_TRIGGER, 3)" ?

**Comment by jasonvarga** [comment]
To be honest I'm not even sure what the point of that setting is. I'd rather just remove it completely.

**Comment by thisJerem** [comment]
Hi jason !

If it let the app to trigger the search from 1 character this is perfect :)

Thanks you!

**Comment by jackmcdade** [comment]
Done and done (in 3.1)!
