### ISSUE TITLE
Add Chunk

### ISSUE THREAD

**Issue by DrTrills** [statamic/ideas#475]
Based on the [discord convo](https://discord.com/channels/489818810157891584/489830552933761024/811653404988145694) about front end. The `Chunk` modifier is a great addition that should be added to core.

Here is the code for the chunk modifier:

```
<?php

namespace App\Modifiers;

use Statamic\Modifiers\Modifier;

class Chunk extends Modifier
{
    /**
     * Modify a value.
     *
     * @param mixed  $value    The value to be modified
     * @param array  $params   Any parameters used in the modifier
     * @param array  $context  Contextual values
     * @return mixed
     */
    public function index($value, $params, $context)
    {
        $chunkSize = array_get($params, 0);
        return $value->chunk($chunkSize)->all();
    }
}
```

And this would be some generic antlers syntax to make it work.

```
{{ collection:articles as="articles" limit="10" }}
  {{ articles chunk="2" }} 
    <div>
      {{ value }}
        <div>{{ title }}</div>
      {{ /value }}
    </div>
  {{ /articles }}
{{ /collection:articles }}
```

The code above would make it easy to output something like:

```
<div class="wrapper">
  <div class="group">
    <div>Entry 1</div>
    <div>Entry 2</div>
  </div>
  <div class="group">
    <div>Entry 3</div>
    <div>Entry 4</div>
  </div>
  <!-- etc -->
</div>
```

*Credit for the code and suggestion goes to: @mattrothenberg

**Comment by duncanmcclean** [comment]
Ah, that's a cool addition! 👍

**Comment by DrTrills** [comment]
Agree, I feel like a whole new world has opened up for my site :D

**Comment by jackmcdade** [comment]
I love this! Just gotta work out how to use `{{ chunk }}` instead of `{{ value }}` on the core side or else it'll hurt my brain.

BTW this can be simplified to:

```php
return collect($value)->chunk(Arr::get($params, 0))->all();
```

**Comment by mattrothenberg** [comment]
@jackmcdade What about something like this 👇 

```php
return collect($value)
  ->chunk(Arr::get($params, 0))
  ->map(function ($chunk) {
      return Array(
          'chunk' => $chunk
      );
  })
  ->all();
```

**Comment by jackmcdade** [comment]
@mattrothenberg :clap:

**Comment by mattrothenberg** [comment]
PR Incoming 😈

**Comment by duncanmcclean** [comment]
> PR Incoming 😈

Looks like Jack's already done it😂   https://github.com/statamic/cms/commit/849ae0ccb4a0fd3e5b6dab21054018f285b3aaf0

**Comment by jackmcdade** [comment]
Woops forgot to close issue. Thanks everyone! 😅
