### ISSUE TITLE
Form API endpoint and / or an extra form tag

### ISSUE THREAD

**Issue by afonic** [statamic/ideas#477]
Now that 3.1 is around the corner and with it the new Nav and Collection structure tree API endpoints I would like to request another endpoint for Forms or maybe a form tag that could be used with the to_json modifier.

## Usage case
Using something like a Vue component to handle generating and submitting the forms is pretty common. Right now I can't find an easy way to send the fields and form data to Vue through a prop. As I think this is a common usage scenario in many frontend cases, having this out of the box makes sense and might even help the community to create easy to use frontend form addons.

## Example
Right now I am using a custom tag like:
```
public function form()
{
    $formHandle = $this->params->get('name');        
    $form = Form::find($formHandle);
    $title = $form->title();
    $url = route('statamic.forms.submit', $formHandle);
    $fields = $form->fields()
        ->values()
        ->toArray();
    return json_encode(compact('title', 'url', 'fields'));
}
```

**Comment by duncanmcclean** [comment]
Is this the kind of thing you're looking for? statamic/cms#3271

**Comment by afonic** [comment]
Not bad. Let's hope it gets merged!
