### ISSUE TITLE
[FR] Allow definition of default behaviour of multisite publishing

### ISSUE THREAD

**Issue by benfurfie** [statamic/ideas#478]
In Statamic v2, when you publish a page or an entry in a multisite configuration, it automatically publishes all locales. If the locales didn't have customised content, it falls back to the default content.

In Statamic v3, you must publish each locale independently. While this obviously is useful for multi-lingual sites where you wouldn't want English appearing on a Spanish version of the site for example, it's a poor user experience for country sites that use the same language, but minor differences in content for each country.

Obviously, both use cases are valid approaches. It would be great if it was possible to configure in config/sites.php whether or not the locale should auto-publish.

Right now, we have a couple of sites that we want to upgrade from V2, but until the auto-publish approach is available, it's not possible as it would likely cause constant complaints from our content teams and likely result in people forgetting to publish the other regions, leading to unwanted 404s.

This could be something like:

**config/sites.php**
```
'sites' => [

    'default' => [
        'name' => 'International',
        'locale' => 'en_US',
        'url' => '/',
    ],

    'gb' => [
        'name' => 'Europe',
        'locale' => 'en_GB',
        'url' => '/gb/',
        'autopublish' => true,
    ],

    'es' => [
        'name' => 'España',
        'locale' => 'es_ES',
        'url' => '/es/',
        'autopublish' => false,
    ],

],
```

**Comment by duncanmcclean** [comment]
I agree, this seems like something that could be quite useful, especially for situations where it's essentially the same site, bar a few content changes (changing color to colour, etc).

**Comment by robdekort** [comment]
Great proposal imo. Best of both worlds. Easy configurable.

**Comment by jasonvarga** [comment]
My original idea was to _also_ support the v2 style where it cascades, but that would mean two sets of features. Hard to maintain. A headache.

Auto-publishing feels like a great solution. Good thinking!

It seems similar to how Craft has "entry propagation".

**Comment by duncanmcclean** [comment]
I've already started on a PR to implement auto-publishing, #3304. So far I've implemented auto-publishing for entries (planning to add for terms as well).

Right now, you configure auto publishing on a per-site basis. What are people's thoughts of that configuration being on a per-collection/per-taxonomy basis instead?

**Comment by robdekort** [comment]
I can imagine use cases where you'd want different things per collection. However it might be confusing for the editor. Personally I'd be fine with on/off for everything.

**Comment by duncanmcclean** [comment]
Okay, I'm probably going to implement it per collection instead because I can see there being cases where people might be annoyed by a per-site thing in the future.

**Comment by robdekort** [comment]
And you can always config all collections the same.  👍👍

**Comment by duncanmcclean** [comment]
> And you can always config all collections the same. 👍👍

Yeah exactly. Hopefully I'll have time to loop back to the PR at some point this week.

**Comment by stuartcusackie** [comment]
Yes, per-collection would be ideal for my current project.
