### ISSUE TITLE
Using a redis queue for [php please assets:generate-presets]

### ISSUE THREAD

**Issue by andrew-ireland** [statamic/ideas#480]
I'm currently testing out/learning the ins and outs of redis/horizon.

I've got Horizon up and running on my production server, and am using `php please assets:generate-presets` & `php please responsive:generate` on deploy (in Forge). When I check Horizon it seems like the spatie/responsive-images tasks are being sent to the queue, and that's working as expected :rocket:. When I run `php please assets:generate-presets` though, these Glide jobs are sent to the queue at all.

I have the following set in my .env
CACHE_DRIVER=redis # file default
QUEUE_CONNECTION=redis # sync default
SESSION_DRIVER=redis # file default

I may be missing something... but it seems like `genereate-presets` doesn't work with queues in V3. For sites with a lot of images it would be really handy if it did. I could be wrong, but based on other discussions I've seen I'm pretty sure this did work with queues in v2?

**Comment by jasonvarga** [comment]
The command itself doesn't queue. When you upload new assets, presets will be generated, and this happens through the queue.

The same is true in v2 in both cases.

However, we could make the command queueable. 👍

**Comment by andrew-ireland** [comment]
Being able to queue this command in production environments would be great. When not using Spatie's responsive images I tend to generate a lot of presets. No issues uploading them, but when generating a lot of presets the production server I've found it pretty resource intensive (I'm using a relatively low powered server).

**Comment by robdekort** [comment]
Oh yeah, it would be super nice if the command was queueable!
