### ISSUE TITLE
Pass closure to `where` in a filter/scope

### ISSUE THREAD

**Issue by edalzell** [statamic/ideas#487]
There have been several times I've had to make a tag, to "filter" a collection based on a more complex query than currently supported.

When I do this, I have to recreate many of the collection features, like `limit` and `as`, etc.

Would be much simpler if we could pass a closure to the `where` so we can handle it ourselves. The closure should receive the collection (or have it available). Not sure what it would return however.

**Comment by jasonvarga** [comment]
Closing in favor of #494
