### ISSUE TITLE
Add TermSaving event

### ISSUE THREAD

**Issue by fjahn** [statamic/ideas#488]
There is the [`EntrySaving`](https://statamic.dev/extending/events#entrysaving) event that allows to manipulate the entry data or prevent the saving in general. However, there is no matching `TermSaving` event, even though there is `TermSaved`.

The same goes for various other entities (for example, Asset Containers, or Forms). In my opinion, having these events can be useful in many different situations. Is there a technical reason for the missing Events, or is it simply an oversight?

**Comment by jasonvarga** [comment]
No technical reason really.

Someone requested the EntrySaving event, so we added it. Naturally, it would take more time to add everything else, and since no one requested it, we didn't want to spend time on unrequested items.

**Comment by fjahn** [comment]
I see, so I guess I would like to request the `TermSaving` event, then.

**Comment by duncanmcclean** [comment]
I don't think it would take massive amounts of work to add `*Saving` events to everything else and to add the `saveQuietly` method you also requested, #489.

I might have a go at some point if someone doesn't beat me to it 🙂

**Comment by duncanmcclean** [comment]
Can this be closed, now that statamic/cms#3379 has been merged?
