### ISSUE TITLE
Named slots for partials

### ISSUE THREAD

**Issue by johncarter-** [statamic/ideas#492]
It would be great to be able to do something like Blade component **named** slots when using partials.

I guess it would look like this:

```html
{{ partial:two-column }}
    {{ slot:sidebar }}
        <p>This goes in the sidebar!</p>
    {{ /slot:sidebar }}
    <p>Else we are just using a plain old slot, so stick this in the main column</p>
{{ /partial:two-column }}
```

```html
{{# resources/views/partials/two-column.antlers.html #}}

<div class="flex">
    <div class="w-1/4">
        {{ slot:sidebar }}
    </div>
    <div class="w-3/4">
        {{ slot }}
    </div>
</div>
```

Hopefully I am not missing something obvious which achieves something similar ( like section and yield 🤔 ).

**Comment by jackmcdade** [comment]
Nice idea! We do have section and yield tho, which would probably also solve the same thing.

<https://statamic.dev/tags/section>
<https://statamic.dev/tags/yield>
