### ISSUE TITLE
Support linking to Assets in Link fieldtype

### ISSUE THREAD

**Issue by jacksleight** [statamic/ideas#493]
The Link fieldtype currently supports linking to a URL or an Entry, it would be useful if you could also link to an Asset.

**Comment by jasonvarga** [comment]
Can you explain why/how you'd use this?

**Comment by jacksleight** [comment]
Yeah sure. I have a general purpose Button component that can be added as a set to Bard fields, the fields are just `text` and `link`. When output this component produces a button that links somewhere. These could link to an external URL or another page, so the current URL and Entry options are perfect for that, but I might also want to link to an asset such as a download or PDF document.

**Comment by jasonvarga** [comment]
Give this a shot: https://statamic.com/addons/rias/link-it

**Comment by jacksleight** [comment]
With the automatic updating of asset references coming in 3.2 I think this would be even more beneficial now.

To date I've been using a custom Link fieldtype that adds this feature, which has worked fine. However as only core fieldtypes are checked when updating asset references any values stored in a custom field wont be updated.

In 3.1.12 Bard was updated to allow linking to assets, so IMO it would make sense to add the same feature to Link fields.
