### ISSUE TITLE
PDFs don't preview on CP assets editor screens

### ISSUE THREAD

**Issue by skylennard** [statamic/ideas#495]
PDF files don't appear to offer a preview in the control panel assets screens.  This seems like it should be happening? I don't know if this is a bug or feature request, but also the date is being displayed wrong, so it could be both.

![image](https://user-images.githubusercontent.com/27147/112063231-4ce09b00-8b1e-11eb-900c-b77f6c3bcb29.png)
![image](https://user-images.githubusercontent.com/27147/112063287-641f8880-8b1e-11eb-933a-ca938c912576.png)

My setup is using a Digital Ocean S3 container disk, and the file is set to public permissions. The .meta/.yaml file for the file is set to private permissions, and the site does fine with navigating around the containers and displaying images, just no previews on PDFs.

**Comment by skylennard** [comment]
The code appears to be trying to embed the file with a <object> tag, but it doesn't appear to be working.

**Comment by jasonvarga** [comment]
We can only show previews for public containers. Is your container private? https://statamic.dev/assets#private-containers

**Comment by edalzell** [comment]
To show PDFs, you turn on the `use_google_docs` or whatever that setting is.

**Comment by jasonvarga** [comment]
This is doable already. Feel free to open a bug report. But make sure your container is public.
