### ISSUE TITLE
Override Roles & Permissions

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/ideas#498]
We're building primarily a Laravel app, with Nova and Statamic to manage it. In this app, we're using Spatie's helpful [Roles & Permissions](https://github.com/spatie/laravel-permission) package.

With this package, we have a couple of roles, like Developers and App Admins, which we'll use for the client. We can use these roles to lock down Nova, using its `gate` method in the `NovaServiceProvider`.

```php
/**
     * Register the Nova gate.
     *
     * This gate determines who can access Nova in non-local environments.
     *
     * @return void
     */
    protected function gate()
    {
        Gate::define('viewNova', function ($user) {
            return $user->hasPermission('Access Nova');
        });
    }
```

However, we'd like to be able to do a similar thing with the Statamic CP. 

Ideally we could have a role called something like `Access Statamic CP` and we could allow any users with that role to use the Control Panel, which currently they can't do unless we mirror the permissions to use Statamic's Roles and Permissions stuff which feels a bit icky.

Maybe there's a way we can already do this? I'd love to know.

**Comment by jasonvarga** [comment]
Did you try `$user->givePermissionTo('access cp')` ?

**Comment by duncanmcclean** [comment]
Ooh, I did not. Where should I add that, where-ever we assign the roles?

**Comment by jasonvarga** [comment]
Yes that's a method on the spatie package.

**Comment by duncanmcclean** [comment]
Ah nice, I'll give that a quick try on Monday if I get a chance. Thanks!

**Comment by duncanmcclean** [comment]
Closing as we seemed to have worked around this in the past year.
