### ISSUE TITLE
Make `Pages` collection available at the top level

### ISSUE THREAD

**Issue by 1stevengrant** [statamic/ideas#499]
In v2 the pages collection was always available at the top level in the CP

![](https://d.pr/i/832TGv+) 

I've had a couple of clients comment that having to go into collections each time is a bit of a faff. I've resolved this by using `cp.js` to append items to the nav.

That said, I also appreciate that not every site would have a `pages` collection, so not sure of the best way to handle by default.

**Comment by jasonvarga** [comment]
Looks like https://github.com/statamic/ideas/issues/74 - but I'm not sure why that's been closed.
