### ISSUE TITLE
Allow display names of fields to be localized

### ISSUE THREAD

**Issue by sauerbraten** [statamic/ideas#50]
It would be useful if our blueprints could have localized display names for their fields.

**Comment by studio1902** [comment]
Yes that makes a lot of sense. Since you can use multiple languages in the CP it's not pretty that field names aren't localised. Same goes for collection titles, taxonomies and asset containers. 

This is how Kirby does it in .yaml files. 

https://getkirby.com/docs/guide/blueprints/translations#labels-placeholders-and-help-text

**Comment by Gitsack** [comment]
Also looking forward to localized field values and instructions. This will be really helpful for a lot of usecases.

**Comment by pryley** [comment]
This would be particularly useful for multilingual forms.

**Comment by robdekort** [comment]
And multilingual starter kits! Still a lot of manual labour now to translate one and no way to include the translations.

**Comment by piljac1** [comment]
In the same order of ideas, it would also be useful to have localizable default values.

**Comment by mikemartin** [comment]
Ran into this one today when I needed to localise select options in a formset. As a workaround, I created 2 localized array fields in Globals to set my options for each locale:

```
<select name="{{ handle }}{{ multiple ?= "[]" }}" {{ multiple ?= "multiple" }} class="form-select block w-full pl-4 pr-10 py-3" :class="{ 'border-red': errors.{{ handle }} }">
    {{ unless multiple }}
        <option value>{{ placeholder }}</option>
    {{ /unless }}
    {{ if options }}
      {{ foreach:options as="value|label" }}
        <option value="{{ value }}" {{ if old|in_array:value or old === value }}selected{{ /if }}>{{ label }}</option>
      {{ /foreach:options }}
    {{ elseif handle == 'company_type' }}
      {{ foreach:company_types as="value|label" }}
      <option value="{{ value }}" {{ if old|in_array:value or old === value }}selected{{ /if }}>{{ label }}</option>
      {{ /foreach:company_types }}
    {{ elseif handle == 'region' }}
      {{ foreach:regions as="value|label" }}
        <option value="{{ value }}" {{ if old|in_array:value or old === value }}selected{{ /if }}>{{ label }}</option>
      {{ /foreach:regions }}
    {{ /if }}
</select>
```

**Comment by stephenmeehanuk** [comment]
It'd be useful to be able to translate the title and have the slug update as well. Playing with my first multi site today.

**Comment by motion-work** [comment]
What's the current state of that issue? Any plans to tackle that in the near future?

**Comment by joshuablum** [comment]
@motion-work It's on [our roadmap](https://statamic.com/roadmap) :)

**Comment by robdekort** [comment]
Tried to come up with a list for stuff that should be translatable. Can anyone think of any additions here?

- Display label
- Instructions
- Prepend
- Append
- Input label (toggle)
- Grid Add button label
- Replicator set title
- Replicator set instructions
- Bard set title
- Bard set instructions
- Array based values: checkboxes, radio, button group, select
