### ISSUE TITLE
Show field based on site

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/ideas#504]
I've having trouble with localizing fields. To explain my situation: I am building a multisite for a chain of restaurants and we want to add 'Locations' as a collection. Each site would have its own locations and each Location would have a County. The counties are different per site - Ireland has it's own counties, England has it's own counties.

So, I set up two separate select fields for 'County (IE)' and 'County (UK)', and I want to show one based on the current site chosen. There doesn't seem to be a site condition available by default so I have created a Site field. I have added the following conditions to each select field:

```
Show When 'site' 'equals' 'ie'
Show When 'site' 'equals' 'uk.
```

but I can't get these conditions to work. Any ideas? I think it would be easier if a site condition was available by default but if I have to do it this way then why is my conditional logic not working? I can see in the entry yaml that the field value matches my conditions, e.g.:

`site: ie`

I have managed a workaround for the moment - I've set up a regular select for IE and UK and based my county conditions on this field instead.

**Comment by jasonvarga** [comment]
You can use the custom javascript method:

https://statamic.dev/conditional-fields#custom-logic

```yaml
field:
  type: text
  if: 'onlyOnSite:ie'
```

```js
Statamic.$conditions.add('onlyOnSite', ({ params, store, storeName }) => {
    const siteInCondition = params[0];
    const siteOfEntry = store.state.publish[storeName].site

    return siteInCondition === siteOfEntry;
});
```

**Comment by stuartcusackie** [comment]
Interesting. Thanks. I made another post about my problem after writing this. This solution isn't great for me unless it hides the field from the entries table as well.
