### ISSUE TITLE
Invisible spacer field

### ISSUE THREAD

**Issue by skylennard** [statamic/ideas#506]
I have encountered many scenarios where I need a vertically-aligned set of fields in various places in the CP content management screens.

To accomplish this, I am able to add an HTML-type field wherever I need a spacer, but the only way to make the field invisible is to hard-code the fieldset/blueprint YAML with a "display: ' '" (display setting for only a simple space), which then results in an invisible horizontal spacer... just so long as I don't save the blueprint again in the CP.

Can we get a new spacer-type field that lets the field width be selected as usual and operates like this, or can we get the rule that title-cases the slug when the display is not provided, or is only a simple space?

Thanks!

**Comment by skylennard** [comment]
![image](https://user-images.githubusercontent.com/27147/114112978-7164a300-9892-11eb-8952-377eb7fae76e.png)
Here's a screenshot of my relevant Discord chats.

**Comment by skylennard** [comment]
In this example. I have 4 fields... the toggle (33%), the title (66%, conditional on toggle), the spacer (HTML type with " " display hard coded, width 33%), and the slug field.

When the toggle is off, the title and spacer are hidden, when the toggle is on, all the fields are shown. This results in correct horizontal alignment for the section as enabled by the toggle, based on the layout I used here.

**Comment by skylennard** [comment]
It would also be rad if the slug "spacer" was allowed to be duplicated, too!

**Comment by jasonvarga** [comment]
Would be a good one for #357
