### ISSUE TITLE
Toggle fields can't be defaulted to "on" in UI

### ISSUE THREAD

**Issue by skylennard** [statamic/ideas#509]
Toggle fields require a developer to hard-code the YAML definition for the field with a `default: 1` syntax to get the field to default in the "on" state.  This should be available in the Statamic CP UI so we can let content managers set this attribute.  Other fields should also have this added as appropriate.

**Comment by jasonvarga** [comment]
Basically https://github.com/statamic/ideas/issues/356

**Comment by skylennard** [comment]
Yaaaahhh... didn't discover that one until after I made this. I was looking specifically for toggles, I guess. Thx for playing @jasonvarga!

**Comment by jasonvarga** [comment]
It was fun!
