### ISSUE TITLE
Add whereDate method to the Query Builder

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/ideas#510]
Adding a `whereDate` method to the Statamic Query Builder would mean developers could do things like this:

```php
$start = \Carbon\Carbon::parse('10th April 2021');

return \Statamic\Facades\Entry::query()
  ->whereDate('paid_date', '>=', $start)
  ->get();
```

Laravel's database query builder includes `whereDate`, along with `whereDay`, `whereWeek`, etc. Review [Laravel docs](https://laravel.com/docs/master/queries#where-clauses)

![image](https://user-images.githubusercontent.com/19637309/114222896-0fc23880-9967-11eb-822c-cc70a5472a39.png)

**Comment by jasonvarga** [comment]
Will be in 3.3
