### ISSUE TITLE
Ability to group collections

### ISSUE THREAD

**Issue by DanielFerguson** [statamic/ideas#512]
G'day!

I'm currently building out a Statamic build and my list of collections are starting to grow quite rapidly. A fantastic organisational tool would be if I could group Collections into lists somehow.

In my head, it would go something like this, where grouped items would fall under the group title and items are indented, and collections which haven't been grouped (yet) live alongside the group titles on the top tier

# Example...

Tips [Group] [Level 1]
-- Trades [Collection] [Level 2 / Indented]
-- Analyses [Collection] [Level 2 / Indented]
-- Tips [Collection] [Level 2 / Indented]

News [Level 1]
-- Collection Name [Collection] [Level 2 / Indented]
-- Collection Name [Collection] [Level 2 / Indented]

Another Collection [Collection] [Level 2]
Another Collection [Collection] [Level 2]
Another Collection [Collection] [Level 2]

In my head, this wouldn't effect the way API routes are generated, it's purely a visual organisation tool for admins, editors and contributors.

**Comment by jasonvarga** [comment]
Will be included in the new nav builder in 3.4. https://github.com/statamic/cms/pull/6678
