### ISSUE TITLE
Dashboard Collection Widget: Allow selection of blueprint

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/ideas#515]
I have a pages collection with about 6 different blueprints, four of these are hidden from selection which is cool, but I have two options that my users should be able to create:

- Legal Document
- Page Builder

The dashboard collection widget currently auto-selects the 'Legal Document' blueprint as it is the first in the list, and the only way to prevent that is to hide the blueprint entirely, which isn't ideal.

Can we get a drop down on the dashboard collection widget to choose between allowed blueprints?

Thanks!!

**Comment by jasonvarga** [comment]
You can reorder blueprints. The first in the list will be used as the default. Did you try that? I may be misunderstanding the issue though.

**Comment by stuartcusackie** [comment]
That does the job perfectly, thank you!

**Comment by stuartcusackie** [comment]
Actually, now I have two page blueprints: 'Page Builder' and 'Simple Page'. As it stands, clicking 'Create Entry' will always create the default blueprint. It's not obvious that you can choose another page template unless you go through the collections menu.

**Comment by jasonvarga** [comment]
Can you show a screenshot of what you're talking about?

**Comment by jasonvarga** [comment]
Scratch that. Totally forgot we're in a thread talking about the dashboard widget. You're right!

🤦

**Comment by stuartcusackie** [comment]
Haha. No problem. I was sending screenshots there but I think you get what I mean now. It is indeed the dashboard widget I'm talking about. The dropdown is fine on the entry list page.

**Comment by stuartcusackie** [comment]
This one is still a pain and very hard to explain to clients that they shouldn't use the dashboard collection widget to create new entries.
