### ISSUE TITLE
Sortable and filterable form submissions

### ISSUE THREAD

**Issue by wm-simon** [statamic/ideas#516]
## Bug Description
It's not possible to filter the results.

## How to Reproduce
```
{{ form:submissions in="votes" sort="date:desc" }} // no effect
{{ form:submissions in="votes" vote:gt="3" }} // no effect
```

## Environment

**Statamic version:** 3.1.9

**PHP version:** 7.4

**Install method (choose one):**
- Fresh install from `statamic/statamic`

**Comment by duncanmcclean** [comment]
Duplicates of #450 and #465.

**Comment by wm-simon** [comment]
OK, thank you for your feedback. Do you see a chance to get this features added in the next weeks?
