### ISSUE TITLE
Custom Searchable?

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/ideas#519]
Currently, Statamic's search system only works with entries, terms, assets and users. However, I think it could be a smart idea to allow for developers to register their own 'custom searchables'.

**Use case:**

There's an e-commerce store, it has all of its orders stored as Eloquent models, whereas everything else (products & pages) are stored as entries.

A backend user of the e-commerce store may want to search for a certan order, maybe by it's order number. However, as the searchable are currently limited/hard coded in Statamic, the order would not be able to come up.

**Possible solution:**

When you define a search index, you can pick from `all` or be specific and do something like `collection:pages`.

```php
'default' => [
   'driver'      => 'local',
   'searchables' => 'all',
   'fields'      => ['title'],
],
```

In addition, if we wanted to support custom searches, like from an Eloquent model, maybe the developer could use a closure?

_I've not actually tested if a closure would work from a config file just yet...._

```php
'default' => [
   'driver'      => 'local',
   'searchables' => function () {
       return Order::all();
    },
   'fields'      => ['title'],
],
```

**Comment by jasonvarga** [comment]
Custom searchables is a good idea 👍 

You can see that `Searchables.php` is pretty dumb. A bunch of `if` statements.
https://github.com/statamic/cms/blob/bae6a753ecf985155e70aa6078214f3d229f9718/src/Search/Searchables.php
I bet we could let addon devs register their own. Something like this:

```php
Searchables::register('collection', function ($collection) {
    return $collection === '*' ? Entry::all() : Entry::whereCollection($collection);
});
```

The callback could receive the bit after the `:`. So if a user put `collection:blog` then it'd be `blog`.

Then also just slapping a closure right into the config like you've done could be an extra thing, if you wanna shove your own eloquent models in there.

> I've not actually tested if a closure would work from a config file just yet....

It'll work, but you won't be able to cache your config.

**Comment by jasonvarga** [comment]
Will be in 3.4.
