### ISSUE TITLE
{{ if validate|contains:required }} required{{ /if }}

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/ideas#524]
How about adding {{ if validate|contains:required }} required{{ /if }} to vendor/statamic/forms/fields/* as a default?

(https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required)

**Comment by jackmcdade** [comment]
Add that to what, exactly?

**Comment by j3ll3yfi5h** [comment]
With `php artisan vendor:publish --tag=statamic-forms` we can customize the field output. There is already e.g. {{ if placeholder }}placeholder="{{ placeholder }}"{{ /if }} as a default, why not adding {{ if validate|contains:required }} required{{ /if }} as a default too?

**Comment by jackmcdade** [comment]
We don't render any content because multi-lingual sites need to have control over all of the words on the site. Sorry!

**Comment by j3ll3yfi5h** [comment]
but the "required" HTML5 attribute isn't content?

**Comment by jasonvarga** [comment]
@jackmcdade he's talking about adding a `required` attribute to these files:

https://github.com/statamic/cms/blob/956656770dab5ff4201cf443369542b8c18f48f1/resources/views/extend/forms/fields/text.antlers.html#L1

**Comment by j3ll3yfi5h** [comment]
https://github.com/statamic/cms/pull/3592

**Comment by jackmcdade** [comment]
Ohh, I'm sorry, I read that not as an attribute but as content next to the label. Good idea — reopened.
