### ISSUE TITLE
Show the collection of an entry when mounting a collection

### ISSUE THREAD

**Issue by Eworm** [statamic/ideas#528]
This happened to me:

<img width="1229" alt="Schermafbeelding 2021-04-28 om 09 12 17" src="https://user-images.githubusercontent.com/511488/116362123-027bc980-a802-11eb-8eeb-dcfe2a0e3f9e.png">

Adding a column with the collection name would improve this screen.

**Comment by jasonvarga** [comment]
Done in https://github.com/statamic/cms/pull/6518
