### ISSUE TITLE
Accept default values on form fields

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/ideas#530]
I would like to add default text to a textarea, but it seems like the default value is not supported at the moment.

**Comment by jasonvarga** [comment]
It is, just not in the UI.

Add `default: whatever` to the yaml.

#356

**Comment by j3ll3yfi5h** [comment]
@jasonvarga I was asking für form blueprint fields – this works to? Didn't work for me

**Comment by j3ll3yfi5h** [comment]
does `{{ old }}` also contain the default value from the yaml-File?

**Comment by jasonvarga** [comment]
I didn't realize you meant the form feature. Just assumed you meant the form you see in the CP.

You can probably use `{{ default }}` in your html.

`<textarea>{{ old ?? default }}</textarea>`
