### ISSUE TITLE
Send form uploads as mail attachments

### ISSUE THREAD

**Issue by globalexport** [statamic/ideas#539]
Hi! 

It would be great if uploaded files of forms (contact etc.) were attachable to the mails.

Providing a checkbox in the form configuration could indicate whether the email should embed the uploaded files as attachments. This is necessary for including a confirmation email without attachments in one workflow.

The checkbox value could be investigated in the `handles` method of `statamic\Forms\SendEmails`.

If checked, something like this is sufficient to attach the files.
```
$email = new Email($this->submission, $config, $this->site);
$data = $this->submission->data();
if (isset($data['file'])) {
  if (is_array($data['file'])) {
    foreach($data['file'] as $f) {
      $email->attachFromStorageDisk('form-uploads', $f);
    }
  } else {
    $email->attachFromStorageDisk('form-uploads', $data['file']);
  }
}
Mail::send($email);
````

**Comment by jacksleight** [comment]
This would be great.

Another consideration is that if the asset container's disk is private nothing gets output in the email at all, which makes perfect sense but isn't super helpful. I think any upload stored in a private disk should probably be attached by default.

I would prefer to store all uploads in a private disk really, they're not something I like the idea of storing in `/public`, but at the moment that's the only option if the email recipient doesn't have CP access.

**Comment by jacksleight** [comment]
If anyone needs a workaround for this and doesn't mind hard-coding it you can remove the form's email configuration in the CP and use an event listener to send you own emails instead:

Here's an example listener that'll do the job (loosely based on my PR): https://gist.github.com/jacksleight/1bc2ca87640108fb5ced3d1be02f567a

**Comment by wm-simon** [comment]
Can be closed I think:
https://github.com/statamic/cms/pull/4726
https://github.com/statamic/cms/pull/6408
