### ISSUE TITLE
Suggestions for the new Structures

### ISSUE THREAD

**Issue by marflow** [statamic/ideas#54]
Some thoughts from a discussion on Discord regarding the Structures feature: 

Would it make sense to break up the the two kinds of structures? Since the **Collection Structure** is only available in the context of collections, why not define it during the set-up of a collection as well: Should this collection be orderable  > if toggle is on > do you want to allow entry hierarchy / nesting for this structure as well? (How deep?)

If set to yes, then all the structuring could happen in the "normal" collection list view: 
Like it was with pages in v2, we could push entries to the right (or left) to define them as descendants/ascendants of other entries. This single source of truth for the collection would simplify things compared to listing them under Collections and Structures as well.

For the **Navigation Structures**, maybe it would be easier to understand if it was called Navigation or Menu Builder? Like it is said in the docs those really do not change structures but the navs can be built to facilitate access to all types of content inside and outside of the site.

If you would like to show or enable collection menus in the builder as well, maybe those could have another background color and info like "The order and nesting of this nav is defined in the collection directly." And add a link "Go to collection now"?

Maybe a different UI could also help to distinguish the two kinds of Structures, but it might still be confusing if you could _Reorder_ a collection under _Collections_ but would not see any hierarchy in this collection listing (if it exists).

**Comment by jasonvarga** [comment]
Much of this has been implemented for beta 20.
