### ISSUE TITLE
Directly access grid values, if there's only one row

### ISSUE THREAD

**Issue by jarnalyrkar** [statamic/ideas#542]
I would love to be able to get the value directly in a grid fieldset, when there's only one row.
`{{ grid.value }}`

instead of having to use the loop-syntax:
```
{{ grid }}
  {{ value }}
{{ /grid }}
```

Would be consistent with how assets work if you only have one asset.

**Comment by jackmcdade** [comment]
You can do this with `{{ grid:0:value }}`.

**Comment by jarnalyrkar** [comment]
Thank you. Not as intuitive in my opinion, but whatever works I guess.

**Comment by jasonvarga** [comment]
If you only _allowed_ one row by using `max_rows: 1`, then it could be considered consistent

With assets, if you haven't set `max_files: 1`, but only select a single asset, it'll still be an array.
