### ISSUE TITLE
Allow addons to "register" field sets

### ISSUE THREAD

**Issue by edalzell** [statamic/ideas#546]
I'm converting a "site builder" site to an addon, so that updates etc are more easily handled.

As part of this site there are many fieldsets and blueprints. I know I can "publish" those into the correct spot, but when we change them, we'll have to go to every site and redo that publishing.

I would be amazing if an addon could "register" a fieldset so that the site can use it, without having to publish it, and then manage it manually.

Kinda related to https://github.com/statamic/ideas/issues/211

- [ ] addon fieldset shows up in fieldset listing
- [ ] can't edit addon fieldset
- [ ] can't delete addon fieldset

**Comment by edalzell** [comment]
Need to consider how we'd handle the fieldset listing/editing? You shouldn't be able to edit an addon fieldset, but viewing it should be fine, right?

**Comment by edalzell** [comment]
Should discovery be automatic, like views and config? Or manual, like tags?

**Comment by edalzell** [comment]
To disable editing/deleting, add a `v-if` here: https://github.com/statamic/cms/blob/3.1/resources/js/components/fieldsets/Listing.vue#L13

Add that to the fieldset when "registered"

**Comment by edalzell** [comment]
> Should discovery be automatic, like views and config? Or manual, like tags?

Not automatic, should be like tags & modifiers.

**Comment by edalzell** [comment]
Current plan:

```
Store the addon fieldset paths in the fieldsetrepository (like add($path)). Then in all(), go through all the paths. Going to add an editable boolean, that can be used in the Listing.vue to disable the deletion/editing
```

**Comment by duncanmcclean** [comment]
Looks like this has already been implemented: https://github.com/statamic/cms/pull/6588
