### ISSUE TITLE
Use browser to display PDF previews

### ISSUE THREAD

**Issue by edalzell** [statamic/ideas#547]
Currently the google viewer is used to preview PDFs.

However if you have a private asset, it doesn't work as the asset is not displayable.

Browsers can display PDFs natively, could you put that in an iframe so we can preview private PDFs?

**Comment by jasonvarga** [comment]
Nope. If it's private, it's not web accessible so it can't be on a URL.

**Comment by devlas-cl** [comment]
Is it possible to preview a pdf natively? I have tried with an addon called [Pdf Thumbnailer](https://statamic.com/addons/insight-media/pdf-thumbnailer), but without success :C, does anyone know of an alternative? my assets are public,
