### ISSUE TITLE
Allow blueprints to be extended with additional fields

### ISSUE THREAD

**Issue by morhi** [statamic/ideas#550]
I want to create an addon, which extends a given blueprint with additional fields. For instance, think about another SEO extension, because we don't have enough yet, which adds a "SEO" tab to a `pages` blueprint. AFAIK you can achieve this by

1) Publishing a fieldset which is then imported into the blueprint manually
2) Ensure fields are set in the Blueprint programmatically

However, these methods will save either the reference of the fieldset or the fields themselves into the blueprint. Now, I only want to extend an existing blueprint with fields of another non-existing blueprint, to make sure, that a specific blueprint (like `pages`) has the fields that I want it to have, no matter what the developer/user does or does not.

So, speaking of a SEO addon, you could add a SEO tab without having the user to do anything. These fields won't appear in the blueprint editor and they won't be saved to the blueprint file.

**Comment by aerni** [comment]
You can extend blueprints already with events like [EntryBlueprintFound](https://statamic.dev/extending/events#entryblueprintfound). You can make sure to not add the fields to your blueprint file by only extending the blueprint when `$event->entry` is `null`. There is one drawback, however; the blueprint will only be extended on existing entries. If you are creating a new entry, the blueprint won't be extended yet.

Check this issue for reference: https://github.com/WithCandour/statamic-aardvark-seo/issues/93

**Comment by jasonvarga** [comment]
Here's a naive solution, but seems to work okay.

```php
Event::listen(function (EntryBlueprintFound $event) {
    if (! Str::contains(request()->url(), '/blueprints/')) {
        return; // On any blueprint editor page, don't add the field.
    }

    $event->blueprint->ensureFieldPrepended('foo', ['type' => 'text']);
});
```

**Comment by aerni** [comment]
Ha, you're smart! Thanks!

**Comment by morhi** [comment]
👍  That's also what I use currently 😅  More specifically I use

```php
    public static function extend(Blueprint $blueprint, Blueprint $extend)
    {
        // This is a workaround to prevent the extended contents to be saved to the blueprint file
        // when the user updates the blueprint in the control panel. Also, this function should not
        // be run when the script is running in console (from a CLI command).
        if (Str::contains(request()->path(), '/blueprints/' . $blueprint->handle()) || app()->runningInConsole()) {
            return;
        }

        /** @var Blueprint $blueprint */
        $contents = array_merge_recursive(
            $blueprint->contents(),
            json_decode(json_encode($extend->contents()), true)
        );

        $blueprint->setContents($contents);
    }
```
