### ISSUE TITLE
Hide certain templates from users

### ISSUE THREAD

**Issue by JayGeorge** [statamic/ideas#556]
It would be neat if there was a way to hide templates from users.

E.g. I want editors to be able to create a page and maybe select 'legalise' as a template, but they shouldn't be able to select other templates like "contact" or "home"

**Comment by jasonvarga** [comment]
This has been asked for a number of times, and we usually give the same response.

If you only want a specific set of templates to be selectable, just use a select field.

```
handle: template
field:
  type: select
  options:
    - page
    - legalize
```

If you add a new template in the future that should be selectable here, it makes sense think "oh I should add it to that field".

If you add a new template that has nothing to do with that section, you're probably not going to think "oh I should exclude it from that field".

That way, you aren't unintentionally giving your clients the ability to screw up your site.
