### ISSUE TITLE
Call a modifier on a tag (example ucfirst on a trans: tag)

### ISSUE THREAD

**Issue by freshface** [statamic/ideas#557]
This does not work:

```{{ trans:labels.read_more | ucfirst }}```

Would be nice to call string modifiers on the trans tag

**Comment by jasonvarga** [comment]
This is because it's actually a "Tag". You can only modify variables.

I'd be fine with a PR to add an `ucfirst="true"` param to the tag itself.

**Comment by jackmcdade** [comment]
In 3.3 you can now do this:

```
{{ {trans:labels.read_more} | ucfirst }}

```
