### ISSUE TITLE
Optionally specify addon when generating files using Please

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/ideas#565]
Right now, you can't use Please's command line to generate 'things' for addons, you can only use `php please` to generate things for sites.

**How it works for sites currently**

Currently, for sites, you can generate things like actions, fieldtypes, tags like so:

```
php please make:action ActionName
```

This will usually give you `app/Actions/ActionName.php` or whatever you need to make it work.

**A current workaround**

You can kinda workaround this for now...

1. Generate like you would a site `php please make:action ActionName`
2. Move `ActionName.php` into your addon's `src/Actions` directory
3. Change the namespace and class name inside `ActionName.php`

**How it could work**

My suggestion would be to provide an optional parameter for make commands so developers could specify the addon they wish to create a desired 'thing' for.

```
php please make:action ActionName --addon=doublethreedigital/something-really-cool
```

This command would generate the 'thing' as normal and automatically place it in the right place (`src/Actions` for actions, `src/Fieldtypes` and `resources/js/components/SomethingFieldtype.vue` for fieldtypes, etc you get the idea)

**Comment by jasonvarga** [comment]
That exists. There's an addon argument.

**Comment by duncanmcclean** [comment]
😅 Whoops, should have looked.

**Comment by jesseleite** [comment]
On top of what Jason suggested, you can also make extra things via `make:addon`...

![image](https://user-images.githubusercontent.com/5187394/120236069-735f3880-c229-11eb-9dab-46cf603d902b.png)

**Comment by duncanmcclean** [comment]
> On top of what Jason suggested, you can also make extra things via `make:addon`...
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/5187394/120236069-735f3880-c229-11eb-9dab-46cf603d902b.png)
> 
> 

Ah that's cool, also never knew that was possible haha
