### ISSUE TITLE
Fixed structure for all sites in a multisite

### ISSUE THREAD

**Issue by rrelmy** [statamic/ideas#566]
I am a bit confused and might not be able to formulate my idea right now but I will try.

We have a page with english as primary locale and 10+ other locales.
The page has 1 home, 4 main pages with around 8 sub-pages each (total about 46 pages).

I can not get my head around how to best progress with the structure of the content or if there are bugs that are my problem.  
In the primary locale the structure looks good but in other locales I have multiple issues

- Structure is flat (subpages at top level)
- Not all pages are shown in the tree view, but the list view shows them
- I have cases where 2 localized pages with diffrent IDs but the same origin and slug
- Pages with date time in the filename show up in the content directory `2021-06-01-1300.foobar.md`

**Comment by rrelmy** [comment]
Our customers regularly are able to create pages like this.
Not sure how

<img width="922" alt="Duplicate_IDs_‹_Asylum_Info" src="https://user-images.githubusercontent.com/442683/121549702-6226e080-ca0e-11eb-96bc-dec50bdc8835.png">

**Comment by jonassiewertsen** [comment]
I came across this as well. This seems to be the case if you:

1. Open an entry OR edit an existing one. 
2. Klick on the toggle on the right side to show a translation (which does not exist yet)
3. DON'T save. 

If saving, it will be saved correctly.
if you just switched to a new language but did not save it, an entry with a date will be saved.

**Comment by jonassiewertsen** [comment]
The second part would belong in Statamic issues I guess.

**Comment by jasonvarga** [comment]
I just came across this issue and it sounds like you're reporting a bug.

To me this is an unclear feature request. Please either open a bug report on the cms repo if you're still having an issue, and/or reopen a new idea repo with the actual feature request.
