### ISSUE TITLE
`GlobalSet->get(...)` should augment data

### ISSUE THREAD

**Issue by edalzell** [statamic/ideas#569]
I have a global field that is an `Entries` field. When I do `$global->get('my-entry')` I get back an `id`. Would be great if this data was augmented.

I tried `augment(...)` and `->value(...)` but neither worked.

**Comment by duncanmcclean** [comment]
Did you try `->augmentedValue('...')`?

**Comment by jasonvarga** [comment]
That ☝️

**Comment by edalzell** [comment]
Thanks @duncanmcclean
