### ISSUE TITLE
Modifiers + Blade

### ISSUE THREAD

**Issue by almas1992** [statamic/ideas#57]
```php
{{ Statamic\Modifiers\Modify::value($content)->striptags()->backspace(1)->ensureRight('!!!') }}
```
I think that modifiers  functionality in blade template not perfect like it in Antlers templates。There is the package call [Blade Filters](https://github.com/thepinecode/blade-filters) ，I think that package will be make modifiers  have same functionality in blade template .

**Comment by jackmcdade** [comment]
Will be part of 3.3. :)
