### ISSUE TITLE
Make {{ current_url }} available in form emails

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/ideas#572]
If you're using the same form on different entries, it would be nice to know, where the client filled it out:

- Skill 1 – get-in-touch-Form
- Skill 2 – get-in-touch-Form
- Skill 3 – get-in-touch-Form

**Comment by duncanmcclean** [comment]
Right now you could probably do this with a hidden text field and just do something like this in your template:

```
<input type="hidden" value="{{ current_url }}" name="form_url">
```
