### ISSUE TITLE
Wordpress-ish Hooks and Filters

### ISSUE THREAD

**Issue by michaelr0** [statamic/ideas#577]
Hi There,

I'm aware of Laravel's Events, but does Statamic have anything like the Filter functionality found in Wordpress? or if there would be interest in trying to PR that functionality into Statamic?

Thanks.

**Comment by duncanmcclean** [comment]
What sort of functionality do you see being available via 'filters' that's not already available?

**Comment by michaelr0** [comment]
Hey Duncan, 

I'm fairly new to Statamic so I haven't explored all of it, but so far I haven't come across "Filters" functionality, I suppose the closest I've seen so far is modifiers? Is there something I have missed? I wonder if it has been staring me in the face?

The general use case would be much like Wordpress and have the option for something to be "hooked into" and be able to modify it prior to the final output. I'm not sure about any examples I could give where I'd need that kind of functionality to modify core functionality, but it would probably be useful for Addon's to have a "standard" way of allowing overrides or adjustments to sections of the functionality.

**Comment by jasonvarga** [comment]
Modifiers sound close to it. 

```
{{ title | upper }}
```

Or, perhaps a view composer could be useful. For example, when loading the `my-template` view, you could add a `custom_title` which takes `title` and uppercases it:

```php
View::composer('my-template', function ($view) {
    $title = $view->getData()['title']; // 'My Page'
    $view->with('custom_title', strtoupper($title));
});
```
```
{{ custom_title }} // MY PAGE
```

Feel free to open another issue if/when you have an actual use case and we can give you better direction.
