### ISSUE TITLE
Ability to override part of imported fieldset

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/ideas#578]
## Use Case

We have a taxonomy blueprint which imports two fieldsets. Both provide a Bard field, which we use as a content builder.

![image](https://user-images.githubusercontent.com/19637309/121875980-f475ff80-cd00-11eb-8bb3-cf19d26ea86b.png)

In our case, on the bottom Bard field, we'd like to override the 'Display name' of the field (to something like `Editor (below)`).

We'd also like to add some conditions so the field is only shown in certain circumstances.

## Possible implementation?

This is currently our content builder fields:

```yaml
-
    import: content_builder
-
    import: content_builder_below
```

Maybe we could do something like this to override the field's display name?

```
-
    import: content_builder
-
    import: content_builder_below
    field:
        display: 'Editor (below)'
```

## Current workaround

A workaround for this would be to copy the field from the fieldset and update the name/add the conditionals.

Although, this could cause problems when a set is added to the fieldset and isn't updated on this blueprint, they'd be out of sync.

**Comment by jasonvarga** [comment]
Another workaround is to import the individual fields instead of the whole fieldset. You can override the config for individual fields now.

**Comment by duncanmcclean** [comment]
> Another workaround is to import the individual fields instead of the whole fieldset. You can override the config for individual fields now.

How would I do that?

**Comment by jasonvarga** [comment]
When you click `Link Existing` in your blueprint builder, you get this stack. Use "Link a single field" instead of "Link a fieldset"

![image](https://user-images.githubusercontent.com/105211/122119187-e5717900-cdf6-11eb-8ba1-212f11aefb9e.png)

**Comment by duncanmcclean** [comment]
Back to this now - my fieldset only has a single field - it's a Bard field used for the content builder. 

Ideally I wouldn't have to have two fieldsets - one for the main content builder and one for the 'below' content builder (which are the same apart from handles & display names).

**Comment by duncanmcclean** [comment]
Ah yeah, I see what you mean now. Sorry for the delay in responding.
