### ISSUE TITLE
Provide email link generator in bard text editor

### ISSUE THREAD

**Issue by juliawarnke** [statamic/ideas#579]
Currently:
When i want to insert an email link in my bard text editor, i have to type `mailto: test@mail.com` in the url field.

Proposal:
Add another possibility with an `email address field`, where the user only has to type the email address. The correct email link will then be generated.

Why:
We have to assume, that the user does not know anything about how an email link works. With an email field, the task of adding an email link in the text editor would be easy and does not require html knowledge.

![statamic_provide_email_address_link_generator](https://user-images.githubusercontent.com/44929138/122002507-2004f280-cdb2-11eb-8047-cfb0b70dd546.png)

**Comment by jonassiewertsen** [comment]
This would be really helpful!

**Comment by FrittenKeeZ** [comment]
Adding telephone (`tel:`) to that list would be welcome as well
