### ISSUE TITLE
Revise New Collection Wizard

### ISSUE THREAD

**Issue by jackmcdade** [statamic/ideas#58]
Statamic 3's wizards were intended to streamline the creation of "container" level things, like collections, taxonomies, and structures. Over time and as features were added, they kept picking up settings and "one more thing"s until they've become almost more complicated than the kitchen sink edit/configure screens they were protecting you from.

I'm working through the UX from scratch again to slim down each wizard's responsibilities and look for ways to speed up development workflow. Here's my conclusion and would love feedback if anyone has any.

## Collection Wizard

I think the wizard should have the fewest number of clicks and decisions necessary to create a collection and allow you to start stubbing out entries. That means it should only have the required fields — those that are necessary to determine the file-level patterns.

### Required fields

- Title
- Handle (generated off Title)
- Enable Dates
- Enable Hierarchy (Structure) or Sequence (flat) ordering

It's reasonable to also decide future/past date behavior at the time of enabling dates, but as those settings can be changed at any time without consequence (nothing to rename in templates, etc), we can leave them for later.

### Remove these fields

- Date Behavior
- Sort order
- Blueprints
- Taxonomies
- Route Pattern
- Mount to an Entry
- Structure
- Default Template
- Default Status
- Default Layout
- AMP

You will still be able to change these settings _after_ you finish creating the collection. But if the defaults are good enough for now, you're done. This will also affect how you create and manage Structures. That too will be simplified, but let's not worry about it in the scope of this effort.

### Added bonus
Why not make the workflow faster and automate some future steps? I plan to add the ability to scaffold matching blueprints and templates based on the collection name. This will save time, pre-configure the collection, and help establish common naming patterns.

### Screenshot
<img width="910" alt="new-collection-wizard" src="https://user-images.githubusercontent.com/44739/71291853-b2edd980-2341-11ea-9869-9c5b9eb2dec4.png">

**Comment by mikemartin** [comment]
I agree, the current wizard felt more like advanced settings. On the first or last step of the new wizard, you might want to include a link for power-users like “Need advanced settings?”

**Comment by jackmcdade** [comment]
Yep exactly. The last step will have the following affordances:

- Create your first entry
- Continue to advanced settings
- Create another collection

**Comment by mikemartin** [comment]
It’s worth considering the different audiences that might be going through these wizard steps and what settings they care about. Here’s some off the top of my head:

1) Developer - Wants to quickly setup everything. Scaffolding definitely helps with this. 
2) Content Editor - Wants to create a new collection but not get into the technical bits. They might have a page that allows them to mount a collection. 
3) Headless Editor - Just wants a simple content repository. No front-end templates necessary. You could compare the workflow to setting up a content repo with Prismic.

**Comment by jackmcdade** [comment]
Yep, and I think this covers those 3 cases pretty well. If we default the scaffolding to being unchecked, you don't need to anything further.

**Comment by mikemartin** [comment]
Scaffold front-end resources feels like a lower-priority item that you might find on the final step.

**Comment by jackmcdade** [comment]
Yes, but it's basing the name off the `handle` so the thought was you would be seeing the blueprint/template names change in real time. 

However, that's not really necessary. Good point.

**Comment by jasonvarga** [comment]
Good changes!

Regarding picking whether it's dated or ordered up front, we probably did that because it would affect filenames.

Order is a non-issue now, since it's either in a structure or in the collection's yaml file.
Date - how about we just support entries without a date in a dated collection? Like, they get filtered out where appropriate perhaps.

@mikemartin says:

> Content Editor - Wants to create a new collection but not get into the technical bits. They might have a page that allows them to mount a collection.

I don't think a content editor would/should ever be creating collections. Seems like a developer task to me. My 2c.

**Comment by JonKaric** [comment]
@jasonvarga Speaking as someone whos clients are the sole content-editor:

They'd all benefit if they could create collections easily by themselves, _if_:
- The developer could choose a set layout(s), template(s) & blueprint(s) for the client to choose from. 
- The wording was defined by the developer (eg: so they could guide the user on creating an SEO-friendly URL structure) 

V3 collection creation is so much more client-friendly but I feel like it still can't decide between being a client feature or a dev feature.

**Comment by philipboomy** [comment]
I have noticed I often forgot to add permissions to a user when I create a new collection or tax so I am wondering if its possible to add some reminder/directly link to modal etc when creating a new collection/tax?

I have seen I am not the only one as this was discussed in Discord for another CMS

**Comment by jackmcdade** [comment]
Ah that's a very real bit of UX right there. We've talked about having some kind of setting for "Apply to all new collections" kind of setting – what do you think about that?

**Comment by philipboomy** [comment]
So on the user role you would have this setting "Apply to all new collections added after creating this role" ?

Not bad idea.

What about having a tab/toggle with user roles in the collection wizard?

**Comment by jackmcdade** [comment]
How would that work though? We don't currently have an affordance for applying roles outside of the permissions screen.
