### ISSUE TITLE
Add context to fieldtypes

### ISSUE THREAD

**Issue by aerni** [statamic/ideas#584]
It would be super useful to have access to the context within a `Fieldtype.php` on which the Fieldtype was loaded. This comes in handy if you only need a Fieldtype to display some data but not writing anything. A simple example is a Fieldtype that displays the ID of an Entry or User. A more advanced example is if you needed to display some data from an external API. But to do the API call, you need access to some data on the Entry.

**Comment by duncanmcclean** [comment]
Ive had to do this before, ended up diving into the Vuex store in my fieldtype Vue component instead.

**Comment by aerni** [comment]
Yeah, diving into Vuex is what I had to do a few times too. But there's not everything in there you might need. And it gets really messy if you have to make an ajax call back to Statamic just to get what you need.

But I'll gladly look at what you came up with.

**Comment by duncanmcclean** [comment]
This what I'm doing [inside one of my addon's fieldtypes](https://github.com/doublethreedigital/simple-commerce/blob/2.3/resources/js/components/Fieldtypes/ProductVariantFieldtype.vue#L58):

```js
return Statamic.$store.state.publish.base.values.items[this.namePrefix.match(/\[(.*)\]/).pop()].product[0]
```

For context: in the blueprint, there's a grid field called `items` with a `product` field and a `variant` field. In the above code, it's getting the value of the `product` field. (it has `max_items: 1` set).

To simplify this use case, without using a Grid you can do something like this:

```js
return Statamic.$store.state.publish.base.values.another_text_field
```

**Comment by jasonvarga** [comment]
You can do `$this->field->parent()` to get the `Entry` when editing or `Collection` when creating.

**Comment by aerni** [comment]
Very nice! Totally missed that one. Thanks Jason!!
