### ISSUE TITLE
My first Statamic Experience

### ISSUE THREAD

**Issue by merijnponzo** [statamic/ideas#586]
Hi There,  working on my first statamic project in progress

https://creativedatastudio.ponzoblocks.nl/

+ Coming from Wordpress i can def. say that my repo is way cleaner.
+ The blueprints works fantastic, just like ACF but better
- There should be a price between Free and 259 dollars, since I have to sum up some addons as wel
It's difficult for me to sell Statamic to my smaller clients. 
So since I consider this project as a fav. for my friend, and i use SpinupWP with git push to deployment I added this to my .gitignore file to manage dev. and production.

```# STATAMIC
# Ignore CMS content
content/collections/blog/*
content/collections/expertises/*
content/collections/pages/*
content/collections/usps/*
content/globals/*
content/navigation/*
content/taxonomies/categories/*
content/taxonomies/labels/*
content/trees/*

# Ignore CMS media
public/assets/
````
etc. This feels a bit hacky though. I'd rather see seperated folders between my content documents, and my content structures.

And I'd rather don't see any blue-prints or field-sets within my production environment, just like strapi.
Only change or add blue prints within your local development!

- I had some problems with simple thinks like populating data, for example to dump all of the info of a taxonomy.
Using {{title}} didn't returned the taxonomy page title (within blog/categories/index.antlers.html)

Since {{slug}} was giving me the current taxonomy slug i wanted to match the slug with the object from my taxonomy list.
But then you get:
```
{{ taxonomy from="categories" }}
 {{ slug === slug }}
```
Which is obiviously not going to work.
I ended up reluctantly using:
```
{{ taxonomy from="categories" }}
 {{ current_uri | segment:3  === slug }}
 ```
Yes i admit I miss wordpress 'get_queried_object()' to simply spit out all of the data, on a current page.

- I used Twig before and you can easily set variables.  This could have solved my problem as well.
```
{{ set pageslug = slug }}
{{ taxonomy from="categories" }}
 {{ pageslug === slug }}
```
However, I cannot find how to set variables.

These are my experiences I wanted to share with the Statamic dev team.

Great Work!

**Comment by morhi** [comment]
Hey!

I don't really get what you mean by

> I'd rather see seperated folders between my content documents, and my content structures.

Could you explain it differently?

Check out https://statamic.dev/modifiers/as#content to store the taxonomies in a different variable, so that the slug won't be overridden.

Also make sure to use https://statamic.dev/tags/dump#content to see the available variables in the current context.

**Comment by merijnponzo** [comment]
Hi, I mean that the content and the content structure should  be seperated at all times.

Now, within the content/collections folder i find:
pages.yaml ( structure of page with fields)
pages (folder with static created pages / documents)

In my opinion all of the structure files should be moved to another folder
or I would rather see the content created documents within storage or something

**Comment by morhi** [comment]
Oke, I think I got. You can seperate the storage locations using `config/stache.php`. This is the config that I use:

```php
    'taxonomies' => [
        'class'     => Stores\TaxonomiesStore::class,
        'directory' => base_path('resources/taxonomies'),
    ],

    'terms' => [
        'class'     => Stores\TermsStore::class,
        'directory' => base_path('content/taxonomies'),
    ],

    'collections' => [
        'class'     => Stores\CollectionsStore::class,
        'directory' => base_path('resources/collections'),
    ],

    'entries' => [
        'class'     => Stores\EntriesStore::class,
        'directory' => base_path('content/collections'),
    ],

    'navigation' => [
        'class'     => Stores\NavigationStore::class,
        'directory' => base_path('content/navigation'),
    ],

    'globals' => [
        'class'     => Stores\GlobalsStore::class,
        'directory' => base_path('content/globals'),
    ],

    'asset-containers' => [
        'class'     => Stores\AssetContainersStore::class,
        'directory' => base_path('content/assets'),
    ]
```

**Comment by merijnponzo** [comment]
Ahhh fantastic, thank you
;-)
