### ISSUE TITLE
Use hashing to prevent long filenames on fully cached sites.

### ISSUE THREAD

**Issue by jeremydouglas** [statamic/ideas#587]
The issue [Full Cache Query String Crashes](https://github.com/statamic/cms/issues/3210) has been solved by not doing a full cache. Would it work to hash the URL to prevent long filenames?

- Create a simple hash `$urlHash = md5($url)`
- Look for the cache file `if(file_exists('static/' . $urlHash))`
- Output the file contents
- Otherwise generate the output...and then save it to that same dir `'static/' . $urlHash`

**Comment by jasonvarga** [comment]
We're already doing this since 3.1.25.

https://github.com/statamic/cms/pull/3864
