### ISSUE TITLE
`locales` tag should indicate if the content exists in the locale

### ISSUE THREAD

**Issue by edalzell** [statamic/ideas#588]
Right now there's no easy way to build a switcher that DOESN'T show up when the content hasn't been localized.

Would be great if there was a `not_localized` variable available.

**Comment by edalzell** [comment]
implementation, see this code:

```php
        if (! $localized = $data->in($locale)) {
            return null;
        }
```

use that.

**Comment by AndreasSchantl** [comment]
This would be great! Personally, it would be great to have a fallback to the homepage of the other localizations too!
Another way would be to make the locales tag countable. Something like ``{{ locales | count > 2 }}`` doesn't work as of right now.

**Comment by aerni** [comment]
@edalzell I believe that this is exactly how the locales tag works as of now. The data only includes locales of localized content. If a particular page does not exist in a locale, there won't be any data for that locale on that page.

[This PR](https://github.com/statamic/cms/pull/4665) makes sure to support the exact opposite. It will let you show all locales even if an entry hasn't been localized.

**Comment by jasonvarga** [comment]
I was also confused by the wording of this issue.

I think he's requesting that if the entry only exists in one locale, he wants to output nothing.
Right now, it still outputs the single locale.
So if you had a language selector, you'd only have one option - the one you're already on.

**Comment by jasonvarga** [comment]
In statamic/cms#4665 you will be able to achieve what you're asking by doing this:

```
{{ if {locales:count self="false"} }}
  {{ locales self="false" }} ... {{ /locales }}
{{ /if }}
```

(The `locales:count` tag already existed, but now you can use the `self="false"` param.)

And just to clarify this:

> Would be great if there was a not_localized variable available.

If it's not localized, it already won't appear in the loop.

**Comment by jasonvarga** [comment]
Actually, you won't need the condition at all.

```
{{ locales self="false" }} ... {{ /locales }}
```

That'll output nothing if there are no localizations.

I thought I'd need to keep the empty loop for backwards compatibility, but until the new `self="false"` param, there was no way to get an empty loop.
