### ISSUE TITLE
Ability to modify the query used in listings (entries, etc)

### ISSUE THREAD

**Issue by jasonvarga** [statamic/ideas#591]
Some users have asked to be able to customize what's shown on the entry listing in the CP.
For example, being able to only see entries you've created and hide entries created by other users.

We can override the EntryPolicy's `view` method to prevent them from seeing the entry if they were to visit its URL, but it's still listed.

We should let users customize the query. Maybe being able to throw a closure in a service provider. Something like this:

``` php
EntryIndexQuery::modify(function ($query) {
  $query->where('author', User::current()->id());
});
```

A policy wouldn't work for the listing because we'd need to retrieve all the entries and filter them in PHP, which would screw up pagination etc.

**Comment by fjahn** [comment]
Using Laravels service container, you can extend or even modify the query without changing Statamic's code. See [this answer to my own question](https://github.com/statamic/cms/discussions/4836?sort=old#discussioncomment-1727164) for details.
