### ISSUE TITLE
Control Panel: Customize the notification for saving entries

### ISSUE THREAD

**Issue by fjahn** [statamic/ideas#592]
I would love if I could set a flexible, custom notification text when an entry is saved. Right now, the message is always 'Saved':

<img width="223" alt="Bildschirmfoto 2021-07-06 um 10 36 28" src="https://user-images.githubusercontent.com/74260729/124569283-19fcb180-de46-11eb-82ca-8042086ad781.png">

I would like to be able to set this within a `EntrySaving` event. I have briefly read through the code and I believe that these are the steps required to accomplish this:

- Refactor the entry saving process so the success notification text gets returned by the controller, and not defined in the frontend.
- Add a new property `notification` to `EntrySaving`. This property can be set by any `EntrySaving` listeners. It could be prefilled with the default value ('Saved').
- When `Entry::save` is called, return the `EntrySaving` event after it was passed through the listeners.
- Refactor `EntriesController` so it returns that notification, instead of the default one.

**Comment by jackmcdade** [comment]
What would you want it to say? 🤔

**Comment by fjahn** [comment]
Well, you could use this for all sorts of things, but the reason why this idea came up for me is the following:

I have some entities that contain Videos that get generated on-the-fly. Every time one of those entities gets saved, the videos have to be re-generated (this happens in a background job on the EntitySaved event). Since the generation takes a while, users will get an E-Mail notification once it is done. When an entity is saved that triggers video generation, I would like to have a different success message that tells the user they will be notified once it is done.

I have thought about simply replacing the translation message, but this would change *all* 'Saved'-Notifications, while I only want it to change for specific entities.

**Comment by jasonvarga** [comment]
I'm not sure this will really be possible.

What happens when multiple listeners return a message? There can only be one.

**Comment by jackmcdade** [comment]
Maybe could push a separate toast message though so it would show saved, and then "email scheduled" or something similar.

**Comment by fjahn** [comment]
Thanks for the responses!

> I'm not sure this will really be possible.
> What happens when multiple listeners return a message? There can only be one.

I would implement this by not actually returning a string in the listener, but having a property *in the event object* in which the message is stored. However, I agree with you that there is a problem when multiple listeners want so set this value, because event listeners usually do not have any ordering defined (although there is one, of course). While my suggestion is not an ideal solution, it would work perfectly well as long as you only have one listener that changes the message. If there are multiple, you could also just append another message to the existing one (which I would probably do if my suggestion was implemented).

Having said that, Laravel actually handles listeners that return values pretty well (which is not documented, as far as I know): In [Dispatcher::dispatch](https://github.com/laravel/framework/blob/d9b43ee080b4d51344b2e578aa667f85040471a2/src/Illuminate/Events/Dispatcher.php#L253), all responses get accumulated in an array and returned to the caller. **So you could also just as well let the listeners return the message that should be shown** (and join the responses together). However, I dislike this solution because it is not as explicit and scalable as having a property in the event instance. What if there is another value you want to return in the listeners as well?


> Maybe could push a separate toast message though so it would show saved, and then "email scheduled" or something similar.

For my use case that would work too. However, this also is not currently possible. Am I correct?

However, my suggestion would be more flexible. For instance, developers could also implement custom saving behavior where the success message needs to be customized depending on the content of the fields the user submitted.

**Comment by jasonvarga** [comment]
Happy to see what you come up with in a PR 👍

**Comment by fjahn** [comment]
My previous PR was closed, but I would like to give this PR another shot, since I still need it (but got caught up in other projects in the meantime). I would like to go through your suggestion in more detail to make sure my next PR can be merged. I would implement this feature in the following way now:

* Add a facade `Toasts` that has a `push` method that accepts an object of class `Toast`.
* `Toast` contains a string for the message, as well as an enum for the type of message (i.e. whether to show a tick or an X next to the message).
* On every outgoing request, fetch all toasts from the `Toasts` facade and attach them to the response using a middleware.
* On the client side, read out the toasts from the response and present them to the user. I have not checked the code yet, but I assume there is a way to do this in a centralized fashion.

**Is this plan okay for you?**

**Comment by jasonvarga** [comment]
Sounds good! (Sorry, didn't notice this message on the PR)
