### ISSUE TITLE
Dictionaries

### ISSUE THREAD

**Issue by dmgawel** [statamic/ideas#597]
Thank you for sharing the updated [Roadmap](https://statamic.com/roadmap). I absolutely love the direction you've taken with Statamic 3!

I would like to offer a small suggestion based on the "Next up" section. It seems that we're going to get new first-party fieldtypes: "iTunes Category, Language, Country, and Color Swatches". I understand and share that need. Creating a select field for all the countries is not the best experience :D However, I think that some of the problems new first-part fields are meant to solve, could be solved by the concept of Dictionaries, without creating new field types. Let me explain.

**How would Dictionaries work?**

1. Dictionary would be a map of keys and labels.
2. Users would be able to define their Dictionaries.
3. Statamic would provide some built-in Dictionaries (Countries, etc.)
4. Dictionaries could be assigned as Options for Select, Checkbox, Color and similar fields.

IMO that would be a very flexible and powerful addition to Statamic :)

**Comment by jackmcdade** [comment]
I love this idea!

**Comment by dmgawel** [comment]
Resolved by https://github.com/statamic/cms/pull/10380 :-)
