### ISSUE TITLE
Respect content type when doing static caching

### ISSUE THREAD

**Issue by SenseAndImage** [statamic/ideas#601]
Currently the full caching strategy (static caching) will always create html files and write them to public/static. Together with server rewrite rules this results in awesome fast websites (SSG for cheap).

Unfortunately the file driver does not care what the content type of the route is and will always create HTML files. I propose to  allow the file driver to write files as specified in the route’s `content_type` param.

That way we would be able to create JSON files as API endpoints or sitemap.xml.

```
// The Sitemap route to the sitemap.xml in routes/web.php
Route::statamic('/sitemap.xml', 'sitemap/sitemap', [
    'layout' => null,
    'content_type' => 'text/xml'
]);
```
^^^ The above is currently not working and will create a `sitemap.xml_.html` file. The only way to get this to work is to exclude the route in `static_caching.php`

BTW: antlers.xml (explicit content type in file name) will also be ignored by the static caching strategy (https://github.com/statamic/cms/pull/3855).

Also see [Full measure static caching - Don't cache pages where content type is not text/html #2287]( https://github.com/statamic/cms/issues/2287)

**Comment by edalzell** [comment]
Another use case, podcast feed. I'd love to cache it as it's very slow to generate, but iTunes needs content to be XML.

**Comment by jasonvarga** [comment]
I haven't looked into but maybe you could find an event to hook onto and when you visit sitemap.xml it writes it public/sitemap.xml, for example. Then hook onto another event for deleting it.

**Comment by duncanmcclean** [comment]
This has been made possible in v5. Although, it'll only be possible when using half-measure cashing (we can't make it work with full-measure due to the nature of how it works). 

We're hoping to release Statamic 5 in the next few days/weeks.

**Comment by aerni** [comment]
Could we make the static cache smart enough to fall back to half measure for XML even if full measure is enabled? I've got an extensive sitemap that requires lots of resources and like to cache it. But I'd still like to use full measure for everything else.
