### ISSUE TITLE
Link to assets from nav?

### ISSUE THREAD

**Issue by dgedwards13** [statamic/ideas#607]
We have a list of links in our footer that we'd like to convert to a navigation, but we need to link to a couple of assets from these links. Currently, there's only the option to link to entries or external links. We can add the full URL to the asset as a link in the nav, but this isn't a very user-friendly option for our content editors, who aren't very tech-savvy. If there was a stop in the UI to find and select (or upload) an asset and link directly to it from the navigation setup, that'd be pretty useful.

**Comment by j3ll3yfi5h** [comment]
How about using a replicator with two sets, one with a Link-Field and one with an Assets-Field? Perhaps in a global?

**Comment by jackmcdade** [comment]
This is coming in 3.2.
