### ISSUE TITLE
Laravel (Horizon, Telescope, Nova etc) links and permissions.

### ISSUE THREAD

**Issue by michaelr0** [statamic/ideas#609]
Something I pondered with https://github.com/statamic/cms/pull/4074, https://github.com/statamic/cms/pull/4075 and https://github.com/statamic/cms/pull/4076 is that there are likely more possibilities (such as Laravel Spark etc) and that the little links section might become too crowded for all of them.

Would it be worth having Telescope, Horizon, Nova etc (if installed) show up as well (or instead) in the left hand sidebar, under their own menu, or even under tools (or within Utilities?)

Something like.
![Sidebar](https://user-images.githubusercontent.com/54159303/127937461-2ad78934-de96-484c-8b2a-5cdb7f0585c4.png)

And perhaps have permissions as well?
![Permissions](https://user-images.githubusercontent.com/54159303/127935381-11e7f2b7-b03f-4872-995c-090daae4a31e.png)

So that one could easily use Statamic to control access to those utilities, by simply updating the gate method in the appropriate `ServiceProvider`

```php
    /**
     * Register the Telescope gate.
     *
     * This gate determines who can access Telescope in non-local environments.
     *
     * @return void
     */
    protected function gate()
    {
        Gate::define('viewTelescope', function ($user) {
            return $user->can('access laravel telescope');
        });
    }
```

**Comment by michaelr0** [comment]
Something like.

![Sidebar](https://user-images.githubusercontent.com/54159303/127935331-e9ddd242-1101-4f4f-a2bc-9223c70f36ab.png)

And perhaps have permissions as well?
![Permissions](https://user-images.githubusercontent.com/54159303/127935381-11e7f2b7-b03f-4872-995c-090daae4a31e.png)

So that one could easily use Statamic to control access to those utilities, by simply updating the gate method in the appropriate `ServiceProvider`

```php
    /**
     * Register the Telescope gate.
     *
     * This gate determines who can access Telescope in non-local environments.
     *
     * @return void
     */
    protected function gate()
    {
        Gate::define('viewTelescope', function ($user) {
            return $user->can('access laravel telescope');
        });
    }
```

**Comment by jasonvarga** [comment]
Looks like you've created https://statamic.com/addons/handmadeweb/statamic-laravel-packages which I'd consider a solution to this, along with the header icons you've PR'd into core.

**Comment by michaelr0** [comment]
> Looks like you've created https://statamic.com/addons/handmadeweb/statamic-laravel-packages which I'd consider a solution to this, along with the header icons you've PR'd into core.

Ok, no worries, Thanks :)
