### ISSUE TITLE
FR: hide underscore partials from "Template" field

### ISSUE THREAD

**Issue by austenc** [statamic/ideas#61]
![image](https://user-images.githubusercontent.com/575421/71593385-0b1a9d80-2af1-11ea-9637-bbbf7d4c5a3f.png)

It would be nice to have view files prefixed with an underscore automatically hidden from the template list. 

For example, `_logo.antlers.html`. Probably not something you want a client setting their template to!  Perhaps the layout and errors pages could be hidden automatically too?

**Comment by jasonvarga** [comment]
If you only need a subset of views to be selectable, just make a select field with those options.

**Comment by jackmcdade** [comment]
Actually I think this is a good idea. We can have a few settings on the fieldtype to disable the behavior.

**Comment by jasonvarga** [comment]
Ya me too, just giving a workaround for now.

**Comment by austenc** [comment]
Thanks for the suggestions and comments guys!

**Comment by jackmcdade** [comment]
Added in https://github.com/statamic/cms/commit/09e770a323037df8128db89dd37a3e426c60b2fc
