### ISSUE TITLE
Support / documentation for Prettier or other code formatter

### ISSUE THREAD

**Issue by jonathanstanley** [statamic/ideas#610]
Currently, auto-formatting of template code with prettier is hard to read.
```html
<div>
  {{bard}}{{partial:partials/example1}} {{partial:partials/example2}}
  {{partial:partials/example3}} {{partial:partials/example4}} {{/bard}}
</div>
```
[see demo](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D5jABGAhgE7oC+FBADmTJsQDZJ2kPMDOA9HAB7EAtjSZwAjFQAEteoxZsOTHvyEi4AJikz2c1rK68Bw0QGYtwBbssGVxuABZz3EuSqpuWPCAA0ICDQZoTmRQMlIIAHcABTIEYJRmCOIAT2DfQlJiMABrOBgAZTowTCgAc2QYUgBXOF84QUI4dHQmgBliMqriUrgAMQhSQWIYBjLkEGIqmAgfEAALGEEmAHU5zHhOIrh8uPWcdeTxsE40kBLOOHYozNKh5AAzLlqQACtOPgAhTJy8-KE4VolOAPJ6+N58fIlUqiACKVQg8BBSmebAupHGCyWsxopBKMGWmHQMDmyAAHAAGXw4iAXZaZGjjHFwNHYYG+ACO8Pg1388QmnAAtFA4E0mrNSHBOZgJddunckI9kb4LoJMBVqs9OFDYVzgQrQSAYMRCASiSSkOpfJViJgmFCAMIQQTykDMgCssyqFwAKsb4oqLr5sDUAJJQFqwfJgXEBACC4fyMGSoiRFyoQA)

preferably, it should look more like this
```html
<div>
  {{bard}}
    {{partial:partials/example1}}
    {{partial:partials/example2}}
    {{partial:partials/example3}} 
    {{partial:partials/example4}} 
  {{/bard}}
</div>
```

Perhaps this is something like [glimmer](https://github.com/prettier/prettier/issues/4908).  Another code formatter would be fine too.  just would prefer that all the code style stays consistent and not need to be done by hand.

**Comment by jackmcdade** [comment]
Statamic doesn't auto-format code at all – we leave that up to the developer and their IDE.

**Comment by jonathanstanley** [comment]
If there is any code formatter that "works" with antlers templates, I would be interested to know it since prettier doesn't work.

**Comment by jackmcdade** [comment]
I think a FR would best be on the `https://github.com/prettier/prettier` repo perhaps?
