### ISSUE TITLE
Get password reset link for a user in the CP

### ISSUE THREAD

**Issue by rrelmy** [statamic/ideas#617]
I would like to have the option back to generate a password reset link in the user overview of the CP.

On staging environments we almost always disable email sending globally in the project, so the password reset mails are not delivered. So the only way (without searching through email logs) is to set a password and send it directly to the person which is not ideal.

Being able to copy the text like in the user creation process would be ok too.

**Comment by wesort** [comment]
I have the exact same usecase as @rrelmy.  

Workaround: manually change the password > Share with the user > Ask user to change the password immediately.
