### ISSUE TITLE
Assets: Global Rules/Validation + CP Default Rules 

### ISSUE THREAD

**Issue by benlilley** [statamic/ideas#619]
Recently we had a content editor accidentally upload a large .psd file directly into the CP via the Assets screen. This mean that all the individual field validation rules were ignored. This made me think of a couple of suggestions:

- It would be nice to be able to set default/global validation rules for uploads that apply to the CP
- Groups or sets of rules that can be shared across fields, so I could set validation rules for 'Large Images' or 'Videos' apply it to certain fields without having to copy/paste or update rules across all uses of the field after the fact.

Very much a nice to have, obviously not a big issue.

**Comment by stuartcusackie** [comment]
I would go further to say that this is somewhat of a big issue. If you've ever tried processing a 20mb image with glide and generating reponsive sizes / fallbacks you might see a website grind to a halt for a while, and possibly crash a server / require a restart.

Also, are PHP validation rules what we need here? In an ideal situation I would catch the large file size with JS validation before sending it to the server.

Just some thoughts.

**Comment by jasonvarga** [comment]
That's a good idea too. To stop the large file getting to the server in the first place. 👍
