### ISSUE TITLE
Make Statamic User work like Laravel User

### ISSUE THREAD

**Issue by edalzell** [statamic/ideas#623]
There are instances when I want to use a collection of Statamic Users instead of Laravel users, like here:

```php
Notification::send($users, new $notificationClass($payload));
```

If you pass in a collection of Statamic Users, you get this: 
<img width="1267" alt="CleanShot 2021-08-13 at 10 16 21@2x" src="https://user-images.githubusercontent.com/6069653/129396278-5f272a60-0f9b-4979-85ee-0a7db1379831.png">

Would be amazing if Statamic could be morphed into a Laravel user (or "pretend to be").

**Comment by jasonvarga** [comment]
> Would be amazing if Statamic could be morphed into a Laravel user (or "pretend to be").

We don't use eloquent so models don't make sense. Our user class complies with the appropriate contracts laravel uses.

Looks like the notification fake (not notifications themselves) assumes it's dealing with models so getKey (a model method) is used.
