### ISSUE TITLE
An isPublished() function on the entry class

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/ideas#625]
This functionality is likely to already exist but I'm having trouble finding any documentation on it, and I can't see any clues in the codebase.

I know how to make queries to find published entries:
`->where('published', true)`

But what about this situation...

My articles have an Entries relationship field to allow for a 'related_article'. The user can select a single article entry with it. I want to ensure that the chosen article is in fact still published before I display it on the front end. I was hoping to do something like this in blade:

```
@if($related_article->isPublished())
{{-- show related article --}}
@endif
```

And it would be ideal if this function checked that both the 'published' toggle was enabled in the control panel AND the date field is not in the future.

**Comment by duncanmcclean** [comment]
Would checking the [`status`](https://github.com/statamic/cms/blob/3.1/src/Entries/Entry.php#L513) method work for your use case?

**Comment by stuartcusackie** [comment]
Trying to figure this out. Currently I'm getting:
`Call to undefined method Statamic\Fields\Value::status()`

**Comment by duncanmcclean** [comment]
Try like this instead...

```blade
$relatedArticle->raw()->status() === 'published'
```

**Comment by stuartcusackie** [comment]
Raw returns a string I'm afraid:
`Call to a member function status() on string`

**Comment by duncanmcclean** [comment]
Hmm, you'll be getting the `Value` object from the augmentation stuff. I imagine `raw` then is the ID of the entry, so something like this should work...

```php
\Statamic\Facades\Entry::find($relatedArticle->raw())->status() === 'published'
```

I'm not sure if there's a way to clean it up so you don't need that extra `Entry` lookup but I've never used augmentation outside of in Antlers. But anyways, that should hopefully do the job!

**Comment by stuartcusackie** [comment]
Thank you. I'm sure your snippet will work, but I was using the blade directive incorrectly.

The augmentation actually removes the related article automatically when it's status is unpublished, so I didn't need to check the published status at all. I just needed to update my blade directive to make sure it wrapped around the $related_article attribute.

I was doing this:
```
@data($page)
  {{-- Main article stuff --}}
@enddata

@if($related_article)
{{-- Related article stuff --}}
@endif

When I should have been doing this:
@data($page)
  {{-- Main article stuff --}}

  @if($related_article)
  {{-- Related article stuff --}}
  @endif
@enddata
```

Good to know about the status() function though. I missed it in the docs.

**Comment by duncanmcclean** [comment]
You probably didn't miss it - it might have never been there 🙈  Where were you looking?

**Comment by stuartcusackie** [comment]
Just googling it really. I find it easier than navigating the statamic docs. I also checked the discord but the search on that isn't great.

**Comment by stuartcusackie** [comment]
More on this here:
https://github.com/statamic/ideas/issues/625

**Comment by jasonvarga** [comment]
Duncan's advice on using `raw()` would get the ID of the entry.
If you instead use `value()`, it should return an `Entry` instance.

Then you can do `$entry->published()` which returns a boolean.
