### ISSUE TITLE
An easy way to detect live preview?

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/ideas#626]
This probably already exists but I can't figure it out. I've seen mentions of `if:live_preview` in the docs but I've no idea how to access this in blade.  `$live_preview` doesn't exist and I can't see anything similar when dumping all PHP defined vars.

So can we can get an easy way to detect live preview in Blade so that I can tell analytics to ignore these requests?

**Comment by duncanmcclean** [comment]
Yeah, `live_preview` is the variable to check...

However, there's currently a bug where it's not being output 😓  see statamic/cms#4013

**Comment by stuartcusackie** [comment]
Ah! I found that article but I thought they were talking about something more sophisticated.

No big deal for me anyway. I'll keep an eye on that thread. Thanks!

**Comment by duncanmcclean** [comment]
(Jason, I know you're watching - this can be closed now 😉)
