### ISSUE TITLE
Possibility to add a class to input fields

### ISSUE THREAD

**Issue by ranuss** [statamic/ideas#630]
I think the title should describe my needs. 😃

**Comment by duncanmcclean** [comment]
What's your use case?

**Comment by j3ll3yfi5h** [comment]
@ranuss You mean in your frontend?

`php artisan vendor:publish --tag=statamic-forms`
and have a look at `/resources/views/vendor/statamic/forms/fields/*`

**Comment by ranuss** [comment]
We use RSCSS and wan't to be able to select elements by their class names.

**Comment by duncanmcclean** [comment]
You're talking about in the CSS, correct? Most fieldtypes already include classes you can use, like `input-text` for a text field. They also have IDs you can target for specific fields, like `field_title`.

**Comment by jasonvarga** [comment]
Are you talking about the front-end? In the control panel? Please be more specific about your request.

**Comment by ranuss** [comment]
I am talking about the front-end. Something like `{{ fields }}{{ field class="input" }}{{ /fields }}` would be nice. (This is a reduced example...)

**Comment by jasonvarga** [comment]
You have complete control over the html of those fields.

https://statamic.dev/tags/form-create#prerendered-html
