### ISSUE TITLE
Question: What happens if the file doesn't exist when using the Glide tag?

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/ideas#633]
Just wondering if I need to reinforce my code and run filesystem checks (File::exists()) before using the glide tag.

A couple of things I'm concerned about:
- User deletes asset but entries refer to it - Will this ever happen or does the cascade check for files?
  - Or, an image goes missing from filesystem for some other reason.
- Does the glide call produce a full 404 error or does it still return a url to a missing image? Ideally the latter would be true. You don't want a whole page to 404 just because of a missing image.

Sorry, I'm not sure if this question should be addressed to League Glide or Statamic. Seems a bit of both?

**Comment by jasonvarga** [comment]
If you have an assets fieldtype and there's an invalid asset path still in it, it'll get filtered out.

If you use a glide tag to point to an invalid or missing image, it'll still output a URL, but if you visit that URL it'll 404.

**Comment by jackmcdade** [comment]
Also, as long as you're running 3.2, when you delete assets all references to them will be removed.

**Comment by stuartcusackie** [comment]
Thank you. This is exactly all the information I needed.
