### ISSUE TITLE
Dynamic Rendering of form fields does not include the default value for text fields.

### ISSUE THREAD

**Issue by abinadi** [statamic/ideas#637]
I have only looked at text fields, but currently the template is this:

    <input type="{{ input_type ?? 'text' }}" name="{{ handle }}"{{ if placeholder }} placeholder="{{ placeholder }}"{{ /if }}{{ if old }} value="{{ old }}"{{ /if }}{{ if validate|contains:required }} required{{ /if }}{{ if character_limit }} maxlength="{{ character_limit }}"{{ /if }}>

It would be nice to include the default value as well. Something like:

    <input type="{{ input_type ?? 'text' }}" name="{{ handle }}"{{if default}} value="{{ default }}"{{/if}}{{ if placeholder }} placeholder="{{ placeholder }}"{{ /if }}{{ if old }} value="{{ old }}"{{ /if }}{{ if validate|contains:required }} required{{ /if }}{{ if character_limit }} maxlength="{{ character_limit }}"{{ /if }}>

Since you have the option to include the default value in the CP, why not include it in the dynamic rendering of text fields? It makes sense to me. I haven't checked if other field types have the same issue, but defaults for those would probably be good as well.

**Comment by jasonvarga** [comment]
No arguments here.

**Comment by j3ll3yfi5h** [comment]
@abinadi Ah, that is new. 💡

BTW: Your suggestion has a duplicate value attribute.

**Comment by jackmcdade** [comment]
Added in https://github.com/statamic/cms/pull/4323.
