### ISSUE TITLE
Aggregate Fieldtype

### ISSUE THREAD

**Issue by aerni** [statamic/ideas#638]
I'm building a fieldtype that acts as a wrapper for multiple fields. One of the reasons is to save the data in a separate array.

I want this:
```md
seo:
  title: 'A title'
  description: 'Description'
```

… not this:
```md
title: 'A title'
description: 'Description'
```

My fieldtype looks the same as the [SeoProFieldtype](https://github.com/spatie/statamic-responsive-images/blob/main/resources/js/ResponsiveFieldtype.vue) and [ResponsiveFieldtype](https://github.com/spatie/statamic-responsive-images/blob/main/resources/js/ResponsiveFieldtype.vue).

The problem with this approach is that the `syncable` property on the `publish-field` component doesn't work as expected. It just works for the wrapper fieldtype itself but not for the fields within. I could imagine that there are other issues with this approach as well.

My proposal is a new aggregate fieldtype that can wrap multiple fields. This might be connected to the [UI Fieldtype](#357) idea.

**Comment by aerni** [comment]
I just realized that this could probably also be done with fieldsets. Fieldsets already serve as a wrapper for multiple fields. You could add an option to save the data of the imported fieldset in its own key. Similar to the prefix option.

The only drawback with this approach is that you lose the capabilities of a true fieldtype with its PHP file.

**Comment by aerni** [comment]
I dug a little deeper. If you wanted the `sync` feature to work on each field, we'd need to make sure, that each field is pushed to the `localizedFields` array in the store. Probably also need to change some other things.

https://github.com/statamic/cms/blob/6d1ebe950ca397e98b0a20ef4c9a6dfd6b21ec25/resources/js/components/publish/Field.vue#L182-L184

The same "only top-level fields can be localized" issue goes for Bard, Replicator, and Grid fieldtype. Might be connected to this: https://github.com/statamic/ideas/issues/439

**Comment by aerni** [comment]
Similar if not the same idea: https://github.com/statamic/ideas/issues/210

**Comment by jasonvarga** [comment]
The top level fields issue is a complicated one.

We don't have a good way to know if you want to override just a nested key(s) or the whole thing.

**Comment by aerni** [comment]
Yeah, I figured. Another beefy idea on your table. Fun.

**Comment by duncanmcclean** [comment]
Just came across this issue... it's now possible using the [Group fieldtype](https://statamic.dev/fieldtypes/group).
