### ISSUE TITLE
Supporting URL fragments for login redirects

### ISSUE THREAD

**Issue by joseph-d** [statamic/ideas#639]
With reference to the "Protect" feature described at https://statamic.dev/protecting-content#protecting-an-entry I would like to suggest that this feature be improved to support URL fragments in redirects.

For example, if an unauthenticated user visits a protected page `http://localhost/user/settings` then the URL is automatically changed to like `http://localhost/login?redirect=http://localhost/user/settings` and then when the user is logged in they are automatically redirected to `http://localhost/user/settings`

However, if an unauthenticated user visits a protected page with a URL fragment such as `http://localhost/user/settings#billing` then although the initial URL on the login page is  `http://localhost/login?redirect=http://localhost/user/settings#billing` the fragment (ie: `#billing`) is not carried through for the actual redirect so the user ends up just being redirected to `http://localhost/user/settings` instead which damages UX a little bit.

This would be useful both for pages where the `#` fragment is being used as a traditional scroll anchor but also for the now much-more-common use case of URL fragments for tabbed pages.

**Comment by jasonvarga** [comment]
Unfortunately this wont be possible as web servers don't get the url fragment. It's a client-side only thing.
