### ISSUE TITLE
Ability to "extend" the User class

### ISSUE THREAD

**Issue by edalzell** [statamic/ideas#64]
Building Charge I'd like to enhance the existing `User` type, the way you do in Laravel (like w/ Cashier adding  `use Billing` to the `User` model.

**Comment by jasonvarga** [comment]
Enhance to do what with it?

**Comment by edalzell** [comment]
Like in cashier, I’d like to do $user->subscribe(...)

**Comment by jackmcdade** [comment]
Closing this as it's a very vague request that's been open for almost 2 years. Let's focus on what you'd need to extend specifically and it'll be more actionable. ❤️

**Comment by edalzell** [comment]
Well like I said, be able to extend the the User to add methods to it

**Comment by edalzell** [comment]
Two ways to tackle:

1. have a config and use that when it gets `new`ed, like Cashier does it
2. use the Container then folks can re-bind it

Thoughts?

**Comment by edalzell** [comment]
It's already coming from the container so this is already possible

**Comment by edalzell** [comment]
Example User:

```php
<?php

namespace App;

use Statamic\Auth\File\User;

class CustomUser extends User
{
    public function foo()
    {
        return 'bar';
    }
}
```

And in the `AppServiceProvider`:

```php
    public function register()
    {
        $this->app->bind(User::class, CustomUser::class);
    }
```

**Comment by edalzell** [comment]
The user is already grabbed from the container, so this is already possible.

Example:

`CustomUser.php`:

```php
<?php

namespace App;

use Statamic\Auth\File\User;

class CustomUser extends User
{
    public function foo()
    {
        return 'bar';
    }
}
```

`AppServiceProvider`:

```php
    public function register()
    {
        $this->app->bind(User::class, CustomUser::class);
    }
```
