### ISSUE TITLE
Blueprint and Fieldset Namespacing

### ISSUE THREAD

**Issue by jasonvarga** [statamic/ideas#644]
It's been requested that addons can register fieldsets (statamic/cms#4086) and register groups of blueprints (statamic/cms#3963). As these are in the same ballpark, we wanted to make sure these features could be added in a way that is consistent and makes the most sense.

Here's the proposal we've come up with.

## Blueprints

You can add a blueprint "namespace", which lets you throw custom blueprints into a directory and have them be displayed in the Control Panel so you can edit them.

For instance, maybe an addon wants to provide some blueprints.

```php
Blueprint::addNamespace('myaddon', 'My Addon', '/path/to/addon/blueprints');
```

```
path/to/addon/blueprints/
|-- product.yaml
|-- order.yaml
```

Just like views, a user can override these by using a `vendor` directory. If you were to save an addon's blueprint, it would be written to this location.

```
resources/blueprints/
|-- vendor/
    |-- myaddon/
        |-- product.yaml
```

(We usually have little shortcuts for addons to register things, and there will probably be something like that here)

You may also omit the path argument, which will just make the files available within the `resources/blueprints` folder directly, without a `vendor` subdirectory.

For example, you might have a custom section where you can edit Eloquent models through the control panel.

```php
Blueprint::addNamespace('commerce', 'Commerce');
```

```
resources/blueprints/
|-- collections
|-- commerce
    |-- product.yaml
    |-- order.yaml
```

## Fieldsets

Similar to above, you can register a namespace that'll contain fieldsets.

```php
Fieldset::addNamespace('myaddon', 'My Addon', '/path/to/addon/fieldsets');
```

```
path/to/addon/fieldsets/
|-- stuff.yaml
|-- morestuff.yaml
```

Again, you can override the fieldsets in the `vendor` directory:

```
resources/fieldsets/
|-- vendor/
    |-- myaddon/
        |-- stuff.yaml
```

You can use them within blueprints or fieldsets with the namespace prefix syntax:

```yaml
fields:
  -
    import: 'myaddon::stuff'
  - 
    field: 'myaddon::morestuff.fieldname'
```

Maybe in some cases it makes sense to allow users to override a fieldset, and in some cases it doesn't.
You can mark a specific fieldset as "not editable" by adding a key. This will prevent it from being shown
in the Fieldsets listing (where you can edit fieldsets), but it will be shown in the blueprint builder (where
you can import fields).

```yaml
editable: false
```

Speaking of the listing, it will be reworked so that fieldsets are organized into namespaces, like the current
blueprint listing. 

You will see fieldsets listed under the namespace headers, with your regular fieldsets
under a "My Fieldsets" header. If there are no additional namespaces, it won't look any different
from what you see today.

**Comment by edalzell** [comment]
Love this!

**Comment by edalzell** [comment]
Fieldsets done in https://github.com/statamic/cms/pull/6588

**Comment by ryanmitchell** [comment]
Blueprints done in https://github.com/statamic/cms/pull/8516

**Comment by duncanmcclean** [comment]
Closing as this has been implemented for both blueprints & namespaces:

* Fieldsets: https://github.com/statamic/cms/pull/6588
* Blueprints: https://github.com/statamic/cms/pull/8516
