### ISSUE TITLE
Allow cross-site linking of entries in Multisite.

### ISSUE THREAD

**Issue by tao** [statamic/ideas#646]
I'm working on a book publishing website, we want to create news articles in English with a link to the German book.

We are using an Entries field in the Blueprint, and when we try select a book it only shows you the English books... currently it seems like there is no option for selecting the site in the Stack Selector modal.

**Comment by jasonvarga** [comment]
I was waiting for this to appear.

This is how it was originally, then people said "why is it showing entries from other sites?".

So, we'll need to make whether or not you see entries from other sites on the field configurable.

**Comment by tao** [comment]
Lol. It's kind of nice how the default collections view works: where it defaults to showing entries from `site:en` only but you can filter by another site if you really want to. We've just added a link in the markdown content for now but might be useful feature in the future.

**Comment by aerni** [comment]
I've also got a footer that should link to entries of both sites. Currently, I'm unable to create this navigation structure as I can't select entries from the other site, e.g., I can't select entries from goUnity in the goMagazin site.

![CleanShot 2023-12-19 at 14 14 01@2x](https://github.com/statamic/ideas/assets/23167701/eb3bba53-4e25-4039-9fde-c66845b2bd85)
