### ISSUE TITLE
Eyedropper tool on the color picker

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/ideas#651]
Just found myself wanting to sample a color while in live preview mode, but it seems this isn't part of the Statamic color picker?

I can use the browser dev tools but it takes a few clicks to convert / copy / paste. It would be nice if the color picker had a built in eyedropper.

**Comment by jasonvarga** [comment]
I imagine it's probably not possible, since JS would need to be able to see things outside of the browser. Probably some sort of security issue.

Anyway, it would be a feature of the color picker package we use. https://github.com/Simonwep/pickr/issues/225
