### ISSUE TITLE
Add editing of HTML source

### ISSUE THREAD

**Issue by FrankPeters** [statamic/ideas#658]
In version 2 it was possible to edit the HTML of a bard field and this was used by our client a lot. However in version 3 it's only possible to view the HTML but not edit it. 

Please consider adding this possibility again so that we can edit simple things like adding a class on an anchor or paragraph etc.

**Comment by jasonvarga** [comment]
Unfortunately I don't think that'll be possible because of how it's using CodeMirror under the hood.

You could add a set to your bard field with a plain text input that could be used to allow adding html.
