### ISSUE TITLE
Statamic V3: Using the header meta noindex?

### ISSUE THREAD

**Issue by Jars-of-jam-Scheduler** [statamic/ideas#659]
Hi,

Would you think sending the header meta noindex to clients would be a good thing to prevent Google from indexing all the URLs beginning by /cp? In order to impede the admin URLs to be shown in the Google search results.

Note that robots.txt doesn't fulfill this goal (it only prevents the contents from being indexed, not the URL, according to Google's docs).

Thank you!
Best regards,

**Comment by jackmcdade** [comment]
You're in luck — we already do it!

https://github.com/statamic/cms/blob/3.2/resources/views/partials/head.blade.php#L4
