### ISSUE TITLE
Extend Bard tool bar with soft-hyphen button

### ISSUE THREAD

**Issue by SirNovi** [statamic/ideas#660]
Soft-Hyphens can be a very useful tool in responsive web design. This is especially true for languages with many long words. For example german or dutch, where we string words together to form new words. 

Hence, it would be very nice if Statamic came with the ability to add a soft-hyphen (\&shy;)  button to its tool bar.

**Comment by jackmcdade** [comment]
I've never seen a soft-hyphen used in an editor before, it's very difficult to represent or know that it's there visibly, and can be used to obscure malicious URLs. I think this is really one of those things that's a done-by-hand thing in HTML.
