### ISSUE TITLE
Date: difference for humans modifier

### ISSUE THREAD

**Issue by robdekort** [statamic/ideas#665]
I recently added a modifier to make human readable date differences:

So `{{ date | diff_for_humans }}` would return something like: `3 months ago`.

This is all the modifier does:

`return $value->diffForHumans();`

Would that be a welcome addition to core? Let me know and I'll make a PR for the cms and the docs.

**Comment by jasonvarga** [comment]
Try `| relative` 😀

**Comment by robdekort** [comment]
NO WAY

**Comment by robdekort** [comment]
I searched and searched the docs. Asked on Discord. WHY DIDNT YOU TELL ME BEFORE 😂

Anyways. Awesome!
