### ISSUE TITLE
Select related entries/pages via tree view

### ISSUE THREAD

**Issue by skoontastic** [statamic/ideas#666]
When selecting a related collection entry or page, it would be great to have the option of selecting the entries via the tree view:
![CleanShot 2021-09-28 at 13 34 22](https://user-images.githubusercontent.com/585102/135147349-626567f8-b074-4575-9df2-7e300da7ed42.png)
![CleanShot 2021-09-28 at 13 34 49](https://user-images.githubusercontent.com/585102/135147642-ae30df8e-9ec3-46ac-9c07-6e31334b7f9a.png)

**Comment by skylennard** [comment]
I would also like to ask if we can add the ability to put other fields in the non-tree view... it would be nice to have more than just title and slug to go by, and there's plenty of real estate for it!

**Comment by skoontastic** [comment]
Maybe a toggle, like on the regular collection view:
![CleanShot 2021-09-28 at 13 59 37](https://user-images.githubusercontent.com/585102/135149312-04ba37f5-7754-4901-b911-e9d87de356cd.png)

**Comment by ryanmitchell** [comment]
This would be amazing. It would also be great to only show the children of a certain entry, eg in the screenshot above you could select "High school" when setting up the field, and then it would only allow you to choose "Language Arts" and "Science".

**Comment by duncanmcclean** [comment]
Note to self - related: #4187

**Comment by artemverbo** [comment]
@duncanmcclean thank you, this was a very useful addition. However, found that if the Entries field is on the Asset blueprint, the tree view would show as empty (in our case, we have a "categories" tree as a collection which are assigned to both entries and some assets). Is that supposed to work for Assets too?

**Comment by duncanmcclean** [comment]
> @duncanmcclean thank you, this was a very useful addition. However, found that if the Entries field is on the Asset blueprint, the tree view would show as empty (in our case, we have a "categories" tree as a collection which are assigned to both entries and some assets). Is that supposed to work for Assets too?

Sounds like a bug. Can you please open a bug report?
