### ISSUE TITLE
Addon Service Provider bootAddon method

### ISSUE THREAD

**Issue by jasonvarga** [statamic/ideas#668]
When creating an addon that has some extra functionality, you'll want to be careful to wrap it in Statamic::booted so it's only executed when Statamic is ready for it.

```php
public function boot()
{
    parent::boot();
  
    Statamic::booted(function () {
        // do something.
        // maybe with config('myaddon') which wouldn't be ready until statamic booted it.
    });
}
```

Since that's a bit messy, we could just add a sugar method for devs to use instead of `boot`.

```php
public function bootAddon()
{
  // do something
}
```

Then you don't need to `parent::boot()` _or_ wrap stuff in `Statamic::booted()`

Statamic could call the `bootAddon` method after it's done.

**Comment by jesseleite** [comment]
Not to mention, `make:addon` could stub out an empty `bootAddon()` method for them 👍
