### ISSUE TITLE
Add ability to link to entries via ID

### ISSUE THREAD

**Issue by fjahn** [statamic/ideas#677]
In my projects, I frequently add a custom tag that works similar to the [Link Tag](https://statamic.dev/tags/link), except with this one, you reference the link via an entry's ID, not via its slug:

```
{{ link_id to="5a604e6f-c973-4030-9a99-ae9f19d0f9cf" }}
```

This has two benefits over linking using the slugs:

1. It is more robust, since users can change the slugs without breaking anything.
2. The link can simply be localized to make Multi-Site setups can localize the links even if the slugs are different.

Since I use it a lot now, I though maybe other users could benefit from this as well. Instead of adding a separate tag, we could extend the existing link tag:

```
{{ link to_entry="5a604e6f-c973-4030-9a99-ae9f19d0f9cf" }}
```

The parameter `to_entry` could also be named `id` or something similar.

Here is the implementation I am currently using:
<details>
<summary>LinkId.php</summary>

```php
<?php

namespace App\Tags;

use Statamic\Contracts\Entries\EntryRepository;
use Statamic\Sites\Sites;
use Statamic\Tags\Tags;

class LinkId extends Tags
{
    function __construct(
        public Sites $sites,
        private EntryRepository $entryRepository
    ) {
    }

    /**
     * The {{ link_id }} tag.
     *
     * @return string|array
     */
    public function index()
    {
        $id = $this->params->get('to');

        $entry = $this->entryRepository->find($id);

        if (is_null($entry))
            return '';

        $currentSiteHandle = $this->sites->current()->handle();
        $localizedEntry = $entry->in($currentSiteHandle);
        if (!$localizedEntry->published())
            $localizedEntry = null;

        $entry = $localizedEntry ?? $entry;

        if ($this->params->bool('absolute', false))
            return $entry->absoluteUrl();
        else
            return $entry->url();
    }
}
```
</details>

**Comment by jasonvarga** [comment]
The native `link` tag also supports IDs.

```
{{ link id="123" }}
```
