### ISSUE TITLE
Add `alias` support to `taxonomy` tag

### ISSUE THREAD

**Issue by edalzell** [statamic/ideas#686]
Current workaround:

![image](https://user-images.githubusercontent.com/6069653/139135999-b0b07048-8e43-4d6f-8962-d701bb4437cf.png)

**Comment by ryanmitchell** [comment]
I think you can use `as="xxx"` from looking at the tag code, is this what you mean?
Its not referenced in the docs.

**Comment by jasonvarga** [comment]
Yeah, use `as`. Just like the `collection` tag. The param is missing from the docs though.

```
{{ taxonomy:topics as="stuff" }}
    <ul>
    {{ stuff }}
        <li>{{ title }}</li>
    {{ /stuff }}
    </ul>
{{ /taxonomy:topics }}

```
