### ISSUE TITLE
Enter key should 'submit' nav item

### ISSUE THREAD

**Issue by edalzell** [statamic/ideas#688]
When adding a nav item, there's a submit button. Would be super great if hitting `Enter` triggered the submit button.

**Comment by jasonvarga** [comment]
Isn't enter a bit odd on its own? I would only really expect enter to work when you're inside a form with some text fields.

You can press cmd+s though.

**Comment by edalzell** [comment]
> Isn't enter a bit odd on its own? I would only really expect enter to work when you're inside a form with some text fields.

That's exactly what it is though? A form w/ some fields...and a submit button?

**Comment by jasonvarga** [comment]
![](https://media.giphy.com/media/GKjO1Ej9uH9rG/giphy.gif)

(You can press shift+enter)

It's the same as the regular publish form, because that's what it is, technically.
