### ISSUE TITLE
Make it possible to customize the location for roles

### ISSUE THREAD

**Issue by flemssound** [statamic/ideas#689]
It would be nice to configure the storage location for the roles in the stache.php.

According to the documentation they are always stored under resources/users.
I can adjust the location of the users here without any problems.
https://github.com/statamic/cms/blob/3.2/config/stache.php#L84

**Comment by jasonvarga** [comment]
You can change them here: https://github.com/statamic/statamic/blob/a08a0a3c8264dfca6bd293fb66809df6e44ecdcb/config/statamic/users.php#L26-L27
