### ISSUE TITLE
Add optional rel field for Bard Links

### ISSUE THREAD

**Issue by jeremydouglas** [statamic/ideas#700]
Currently `nofollow` links on Bard is either all-in or all-out. 

It would be helpful to be able to specify this on a per-link basis. Using a text input would allow setting `nofollow`, `sponsored`, etc. As an example:

![image](https://user-images.githubusercontent.com/113216/141510982-d71c8706-f086-4743-8279-3caf43b7b6a9.png)

**Comment by FrittenKeeZ** [comment]
I was thinking sort of the same thing, but instead of having `link_noreferrer`, `link_nooperner` and `target_blank` a toggle with `true/false`, change it to be a radio of `true/false/external` so internal links and assets are left as they are, but external links default to open in a new window with proper SEO `rel` value.

**Comment by simonridley** [comment]
@jeremydouglas did you implement a solution yourself in the end?

**Comment by tadekrzewuski-lc** [comment]
This would be super useful. Is there an example implementation anywhere?

**Comment by FrittenKeeZ** [comment]
We ended up doing it ourselves using the `jacksleight/statamic-bard-mutator` package:
```php
Mutator::html('link', function ($value) {
    $href = $value[1]['href'] ?? null;
    if (URL::isExternal($href) && !Str::startsWith($href, ['mailto:', 'tel:'])) {
        $value[1]['rel'] = 'external noopener';
        $value[1]['target'] = '_blank';
    }

    return $value;
});
```

**Comment by tadekrzewuski-lc** [comment]
Thanks, this is helpful! I also found a way by using https://jacksleight.dev/docs/bard-texstyle/attributes but it feels a bit clunky as it's being set in a separate button in the toolbar... and to get this you need the pro version. I'll see if I can achieve this directly in the link button in Bard.
