### ISSUE TITLE
Query 'sub' fields using the query builder

### ISSUE THREAD

**Issue by ryanmitchell** [statamic/ideas#701]
I would love to be able to do queries like:

```
Entry::query()->where('my_replicator.0.my_field', 'one')->get()
```

or

```
Entry::query()->where('my_replicator->0->my_field', 'one')->get()
```

I'd also be more than happy to work on it if someone can point me in the right directions

**Comment by jasonvarga** [comment]
That would be a JSON where clause. Your second example.

https://laravel.com/docs/8.x/queries#json-where-clauses
