### ISSUE TITLE
Allow non-email/multiple fields to be unique for each user

### ISSUE THREAD

**Issue by hmalaud** [statamic/ideas#702]
Currently, Statamic enforces each user to be created with an unique email. In the case of a website using pseudonyms, that would be nice to be able to make this field the unique one, or even have both fields be unique.
E.g. creating user with email john@doe.com with pseudo value "john" would make it impossible to create another user with the same email (as of now) AND with "john" as a pseudo. 
That is mainly useful when you want to let users create their profile on their own.

**Comment by jasonvarga** [comment]
Are you saying that `john@smith.com` isn't allowed to exist if `john@doe.com` already does?

**Comment by hmalaud** [comment]
No, more like if you're registering to any forum now, you have to fill in your email that must be unique (what Statamic does right now) and choose a unique pseudo/name that will be shown in the forum (what Statamic doesn't allow right now).

**Comment by jasonvarga** [comment]
Okay so your pseudonym would be a separate field they'd type in. You want that to be unique.

In that case, we already have a validation rule for that.

``` yaml
-
  handle: pseudonym
  field:
    type: text
    validate: 'unique_user_value:{id}'
```


Needs to be documented though. https://github.com/statamic/docs/issues/516

**Comment by hmalaud** [comment]
Ah nice, thanks! Is there any way to have an additional more specific error then? (right now with `unique_user_value` it will always be "this email has already been taken"
I can then update the doc if you'd like :)

**Comment by jasonvarga** [comment]
Yes, in `resources/lang/en/validation.php`, down in the `custom` array, you can add custom messages.

```
'custom' => [
  'pseudonym' => [
    'unique_user_value' => 'This pseudonym has been used by someone else.'
  ]
]
```

https://laravel.com/docs/8.x/validation#custom-messages-for-specific-attributes
