### ISSUE TITLE
Augmentation for Tags returning a Value

### ISSUE THREAD

**Issue by aerni** [statamic/ideas#705]
I've got a Tag that returns a `Statamic\Fields\Value` and would like to use augmentation on the returned value. It would be great if Tags would behave like variables if in fact they simply return a value.

**Comment by jasonvarga** [comment]
It does that already. I made a tag that returns a Value, and when I did `{{ my_tag }}`, the augmented value was output.

Does your Value object have the right fieldtype attached to it?

Can you provide more details?
