### ISSUE TITLE
Add callback before View renders

### ISSUE THREAD

**Issue by aerni** [statamic/ideas#706]
Is it possible to add something like a`beforeRender` callback to `Statamic\View\View`? Similar to the `Cascade::hydrated()` callback added here: https://github.com/statamic/cms/pull/4359

I use the `Cascade::hydrated()` callback to add additional data to the context. This does mostly what I need it to do. But there are cases where a View adds additional data to the cascade in the `gatherData()` method, e.g. in the [NotFoundHttpException](https://github.com/statamic/cms/blob/35a71e4b31ba3b2060d889dcb208d34a2d32859a/src/Exceptions/NotFoundHttpException.php#L22-L29).

So the final context data can be different to what's available in the `Cascade::hydrated()` callback. I need a way to have the last say before the context gets added to the page.

**Comment by aerni** [comment]
I found that Laravel already provides a way to do so:

```php
\Illuminate\Support\Facades\View::composer('*', function ($view) {
  $view->with('foo', 'bar');
});
```

The view in this callback has all the data from the context and additional data from Statamic's views available.

**Comment by jackmcdade** [comment]
Bingo! 🙌
