### ISSUE TITLE
Allow limit on {{ slider }}

### ISSUE THREAD

**Issue by michaelmannucci** [statamic/ideas#710]
The `{{ slider }}` tag is really helpful for pagination since it contains a lot of content and logic that you don't need to make yourself... but it's hard coded to list the next 10 pages. It would be great to be able to do something like `{{ slider limit="5" }}` in order to list the next 5 pages instead of 10 (for example).

**Comment by duncanmcclean** [comment]
The `{{ slider }}` tag?

**Comment by michaelmannucci** [comment]
Yes.

```
{{ paginate }}
{{ slider }}
Stuff
{{ /slider }}
{{ /paginate }}
```

`{{ slider }}` loads 10 pages automatically.

**Comment by jasonvarga** [comment]
https://github.com/statamic/cms/pull/5001 addresses this.

You'll be able to lower it to a minimum of 3 in that slider window. (One on each side)

**Comment by eklektos-io** [comment]
Is this for the next update or it should work right away?

**Comment by jasonvarga** [comment]
Next update. 3.2.29
