### ISSUE TITLE
Closures in search.php config file could be changed to match advice on config caching.

### ISSUE THREAD

**Issue by sunscreem** [statamic/ideas#721]
At present the docs suggest [using closures](https://statamic.dev/search#transforming-fields) for transformers when setting up a search. 

This prevents the use of `php artisan config:cache` or `php artisan optimize` which is recommend by Laravel [in their docs](https://laravel.com/docs/8.x/deployment#optimizing-configuration-loading) as you can't cache closures in config files.

Would be great to see an alternative approach.

**Comment by jacksleight** [comment]
It is now possible to workaround this with computed values.

Before:

```php
'fields' => ['title'],
'transformers' => [
    'title' => function ($title) {
        return ucfirst($title);
    },
],
```

After:

```php
'fields' => ['title_ucfirst'],
```
```php
// AppServiceProvider.php
Collection::computed('pages', 'title_ucfirst', function ($entry) {
    return ucfirst($entry->title);
});
```
