### ISSUE TITLE
Toggle switch field: show symbol instead of "true" in the entries listing

### ISSUE THREAD

**Issue by zehfred** [statamic/ideas#724]
It would be nice to show a symbol like ✅ or similar instead of "true" when showing toggle fields in the entries listing.

<img width="1151" alt="Screenshot 2022-01-05 at 21 39 39" src="https://user-images.githubusercontent.com/1191865/148364685-af5802b5-85ae-458c-b820-c8205cd1a89f.png">

**Comment by jasonvarga** [comment]
Sorta a duplicate of #101
