### ISSUE TITLE
Dynamic folder name for asset field type

### ISSUE THREAD

**Issue by j3ll3yfi5h** [statamic/ideas#725]
It would be nice, if we could use a dynamic folder name with the asset field type:
Maybe something like `folder: {slug}`, to keep the asset container tidy and e.g. assets/entries together.

**Comment by j3ll3yfi5h** [comment]
Good point. Currently I'm using `read_only: true` on the slug field to prevent this... 🤔

**Comment by j3ll3yfi5h** [comment]
How about using `folder: {id}` instead?

**Comment by j3ll3yfi5h** [comment]
Hi @jasonvarga! I'm trying to implement this requested behavior with an `EntryCreated` (create folder structure) and an `EntryBlueprintFound` (update folder paths) event listener. I have the problem, that with the first opening of the publishform of an entry, there isn't a uuid until its first save (and there isn't a folder with the same uuid).

Any idea, how I could trigger uuid generation earlier, right before the `EntryBlueprintFound` listener is triggered? Or how I could set the uuid manually and pass id to the `EntrySaving` listener?

**Comment by jasonvarga** [comment]
Not sure. The ID is generated when the entry actually gets created.
