### ISSUE TITLE
AVIF support (read: Update Glide)

### ISSUE THREAD

**Issue by espenlg** [statamic/ideas#729]
In version 2.1.0 Glide added support for AVIF (ref https://github.com/thephpleague/glide/releases/tag/2.1.0).

Could you consider updating the Glide version in Statamic?

**Comment by jackmcdade** [comment]
We're still running Glide v1 so at this time it won't be possible to simply update the version. Glide v2 uses Flysystem 2, which would be a completely breaking change at this time. We'll need to upgrade both of these packages at a major version release to do it properly.

**Comment by espenlg** [comment]
Affirmative. I was not aware the change in Glide involving Flysystem 2 🙈  Keeping fingers crossed it will be implemented at some point in the future 🤞

**Comment by jackmcdade** [comment]
Supported in 3.3 if you're running Laravel 9 🤘

**Comment by espenlg** [comment]
Awsm! Looking forward to try it out 👏
