### ISSUE TITLE
Sort by x, then by y

### ISSUE THREAD

**Issue by michaelmannucci** [statamic/ideas#740]
It would be great to be able to sort by one criteria, and then by another, similar to what is mentioned [here](https://statamic.com/forum/258-sort-by-custom-field-and-then-by-date).

Looks like this doesn't work anymore. My case is I'd like to sort by the manual ordering I did in the CP, and then alphabetically for the rest.

**Comment by jasonvarga** [comment]
You can do that. If it's not working for you, please open a bug report at github.com/statamic/cms

**Comment by michaelmannucci** [comment]
What is the proper syntax to sort by my manual ordering first (like the tree) and then by alphabetical after? So I can test if it works?

**Comment by jasonvarga** [comment]
`sort="order|title"`
