### ISSUE TITLE
Edit user profile

### ISSUE THREAD

**Issue by wm-simon** [statamic/ideas#753]
Right know it's possible to add custom fields for the user registration. 
After the registration, it's not possible for users to edit their profile data, like email, phone, image, etc... anymore.

Something like a `{{ user:edit }}` function would be really helpful.

**Comment by duncanmcclean** [comment]
In v2, there was an addon called [Profiler](https://statamic.com/addons/silentz/profiler) which did just that but I don't believe it's been ported to v3 yet. 

Currently, you could probably do this yourself with a custom controller which would update the current user's information. Shouldn't be that hard to do.

**Comment by ryanmitchell** [comment]
Another option is make a form which stores no entries, and sends no emails, then listen for the FormSubmitted event to update the logged in user.

**Comment by wm-simon** [comment]
https://github.com/statamic/cms/pull/6400
