### ISSUE TITLE
Ability to add custom svg in custom fieldtype

### ISSUE THREAD

**Issue by edalzell** [statamic/ideas#755]
Would be loverly if we could have our own fieldtype icons.

**Comment by jasonvarga** [comment]
You can. Add `protected $icon = '<svg>...</svg>';`

If you provide an `<svg>` tag, it'll use that rather than looking up the icon.

**Comment by jackmcdade** [comment]
And in the docs: https://statamic.dev/extending/fieldtypes#fieldtype-icon
