### ISSUE TITLE
Add someway to specific a target when using Link fieldtype

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/ideas#764]
It would be nice if there was a way to specific a target, like `_blank` when using the Link fieldtype.

## Use Case

![image](https://user-images.githubusercontent.com/19637309/157641157-08312e00-24ed-44b4-bd69-4c01b84e245c.png)

We're letting the client use the Link fieldtype to specify both internal & external URLs for cards to point to. However, for links that go out with our site, it would be nice to have the option for them to open in a new tab.

**Comment by jasonvarga** [comment]
Can't you have a separate field?

**Comment by duncanmcclean** [comment]
I guess we could do but would it not make sense to have it in the one field with the link itself? Although, I guess that would probably be a pain..

**Comment by duncanmcclean** [comment]
Yeah, that's a fair point. Its easy to workaround and probably a pain to implement..
