### ISSUE TITLE
Option to show unpublished entries on the frontend when logged in

### ISSUE THREAD

**Issue by robdekort** [statamic/ideas#767]
It seems this feature got silently removed. According to https://github.com/statamic/cms/issues/4248 it caused confusion for users. I thought this was the default behavior in most CMS'es though. Maybe it's nice to bring it back as an option.

**Comment by jasonvarga** [comment]
As you pointed out, it was intentionally removed.

There's too many moving parts that contributed to the confusion.

Among other things, if you visit the draft page directly, you'd see it. But you wouldn't see it in other listings. That's weird.
But should you show all drafts in all listings? What if your listing tag explicitly says to exclude drafts, but you see them? You'd be wondering why. Most of the time when I'm working on a site, I'm also logged in. So you'd have to remember to log out or use another browser or private session.

Live Preview exists, so we suggest to use that feature to preview your drafts.

**Comment by robdekort** [comment]
Right. I get it. Didn't think of all that. It opens a big can of worms. 🪱

**Comment by mikemartin** [comment]
@jasonvarga Thanks. Can you share a direct link to a live preview page? Maybe it would be worth adding a share action to next to the responsive fields in live preview.

**Comment by jasonvarga** [comment]
Not yet, but the changes to how Live Preview works in 3.3 opens up the possibility to add a generic "preview" link feature so you can share a draft with someone.
