### ISSUE TITLE
Allow taxonomy term fields to use any handle

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/ideas#777]
I use a custom 'Taxonomy Terms' field on my collection instead of the default method (setting the collections from within the taxonomy panel), because I need to set a 'Max Count' and add the field to a particular field set, rather than showing it in the sidebar.

I had a bit of trouble with this approach and entries were not being related to terms correctly. I figured out that I must use the pluralised version of the taxonomy (e.g. 'categories') for the field handle. I was using previously using the handle 'event_category'. In my case this handle makes much more sense in the code.

Can the taxonomy tag be updated so that any handle can be used?

**Comment by jasonvarga** [comment]
If you want to taxonomize the entries, the field has to match the handle of the taxonomy.

I'm not following your reasoning for needing a different handle.
You're free to customize and move the field to a different section in the blueprint.

**Comment by stuartcusackie** [comment]
It's just that it took me quite a bit of time to figure out that the handle had to match the taxonomy exactly. It's not mentioned in the docs.

If my taxonomy relationship is singular then a handle of 'category' makes more sense than 'categories'. Also, when I have lots of fieldsets I tend to prefix each field, but that approach isn't compatible in this case (e.g. I was using a handle of 'event_category' as some* of the entries in my 'posts' collection represent events).

The 'taxonomies' property of the yaml file holds the 'categories' value already so I was wondering why the handle had to be 'categories' too. There's probably a good reason for this but if it were possible to use any handle then I think it would make things more intuitive and I could avoid problems like this in future.

No worries if you want to close this.

**Comment by jasonvarga** [comment]
We'll try to make this clearer in the docs. I swear this was explained, but you're right, I can't see it. Maybe it got left off in a rewrite somewhere. 🤔 

It's not that it has to be the "pluralized" version... it just needs to match the taxonomy.
