### ISSUE TITLE
Add evident solution to add asset alt text.

### ISSUE THREAD

**Issue by stefankempf** [statamic/ideas#780]
The alt text of assets is treated with too little attention for my taste. When I upload an asset and publish the article, I don't need to add an alt text. I sometimes don't even get the option shown to enter the text. In my builds I have started to add a separate text field for alt to have it required since imo this is an important a11y and I see quite a lot of my users who simply ignore the alt text. I have the following two ideas:

1. show an input field during initial upload, where the alt text can be stored. Then at least, the user sees the alt text input once.
2. have an option to make an alttext required (hope I didn't oversee it). If a user tries to publish an article containing images without alttext, show an error warning (for example: "alt text not set") like the usual  required warning. Maybe add a link to open the image detail stack, where the alt text can be set.

**Comment by jasonvarga** [comment]
Please add to #496
