### ISSUE TITLE
Make titles optional too

### ISSUE THREAD

**Issue by aerni** [statamic/ideas#784]
Can we make an entry's title optional? The slug already has that functionality. 

I have a collection of orders and simply want the title to be the entry's ID. I tried to use the new title format feature. But it doesn't work for the ID because an entry doesn't have an ID until it was saved the first time.

A title only really makes sense for frontend-facing collections. If you don't have a route and slug, you likely don't need a title either.

**Comment by jasonvarga** [comment]
Titles are already able to be optional. That's the title format feature. If you can't use the ID open up an issue explaining that in more detail.

**Comment by aerni** [comment]
Ha, never mind. I tried again, and it works now as expected for whatever reason. One of those days …
