### ISSUE TITLE
Generate multiple glide sizes at once

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/ideas#786]
One of my websites requires a lot of image manipulations. With over 20 images on one page, each requires an original, a mobile version, 2 x retina images, and a jpeg fallback for older browsers. That's over 100 manipulations for a single page which can take a couple of minutes and cause php timeouts when the glide cache has to be rebuilt.

So I was wondering, can the performance of the glide tag be improved? I am guessing this, but I assume that each time I use the glide tag the following happens:
1. Retrieve remote image file
2. Apply manipulation

Would it speed things up if the glide tag retrieved the remote file only once and the applied all five of my manipulations required for each image? This way the file doesn't have to be re-retrieved each glide call. I'm not sure if this would make a difference. Perhaps the file is only retrieved once anyway?

So, as a blade user, I would imagine this could look something like:
`Statamic::tag('glide:generate')->src($source)->manipulations($multiArrayOfGlideSettings)`

Just a thought. Thanks for reading.

**Comment by duncanmcclean** [comment]
Not sure if it does exactly what you need but have you seen the [Responsive Images](https://statamic.com/addons/spatie/responsive-images) addon?

**Comment by stuartcusackie** [comment]
I have tried that but the field that comes with it is really complex and not something that I would let my users near. Maybe there's another way to use it and I might try again someday.

I'm trying to build a custom blade component instead but struggling with performance currently.

**Comment by AndreasSchantl** [comment]
You don't have to use the responsive fieldset if you mean that by too complicated for your users.

Also, make sure to check that you have the image caching turned on in the ``assets`` config file. It's also not a bad idea to define the sizes in there, so the images can be created upon upload with a background job.

**Comment by stuartcusackie** [comment]
Just tried out the Responsive Images addon again. Works pretty well. Almost exactly what I need, apart from a few bugs and a lack of retina image support.

**Comment by jasonvarga** [comment]
It's absolutely a good idea for us to retrieve the image one time instead of each time, though.

**Comment by stuartcusackie** [comment]
I'm struggling to see how this would work now because enabling the glide cache changes things completely. With the glide cache enabled images are pre-manipulated, in which case my suggestion might work fine, but when the glide cache is disabled each size is only manipulated when requested, in which case my suggestion might be unnecessary and impossible to implement.

I'll leave this closed but let me know if you want me to re-open.

**Comment by jasonvarga** [comment]
Even when you enable the cached mode, the first request would take ages. Your suggestion would at least avoid having to re-read the original image for each variation. But yes, when using cache you'd only see a benefit the first time.
