### ISSUE TITLE
Query Builder: Add `->when` method

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/ideas#787]
It could be useful if the Statamic Query Builder had a `when` method so you can do certain parts of a query if something evaluates to `true`.

## My Use Case

In my use case, I'm trying to filter the posts returned by my entry query depending on if any categories are specified in the request.

```php
$allPosts = Collection::find('blog')
            ->queryEntries()
            ->where('published', true)
            ->when($request->get('category'), function ($query) use ($request) {
                return $query->whereTaxonomyIn(Arr::wrap($request->get('category')));
            })
            ->orderBy('date', 'desc')
            ->get();
```

However, right now, as the `when` method doesn't exist, I'm having to do this:

```php
$allPosts = Collection::find('blog')
            ->queryEntries()
            ->where('published', true);

        if ($request->get('category')) {
            $categories = collect($request->get('category'))->map(function ($categorySlug) {
                return "blog_category::{$categorySlug}";
            })->toArray();

            $allPosts = $allPosts->whereTaxonomyIn($categories);
        }

        $allPosts = $allPosts
            ->orderBy('date', 'desc')
            ->get();
```

## In Laravel's Query Builder

![image](https://user-images.githubusercontent.com/19637309/165102642-8d8f8d32-51f8-4336-b3f4-9affd3693bdc.png)

https://laravel.com/docs/9.x/queries#conditional-clauses

**Comment by jasonvarga** [comment]
We have it already.

https://github.com/statamic/cms/blob/8d4c9b4102a9c250b1049f63652aa675e8ec551f/src/Query/Builder.php#L554

<img width="710" alt="image" src="https://user-images.githubusercontent.com/105211/165197585-fd12cf28-0fee-4864-847e-cc627777ca2f.png">

**Comment by duncanmcclean** [comment]
Oh weird... It 100% wasn't working when I tried the other day - it's possible that we were on an old version of Statamic though.
