### ISSUE TITLE
Headless Live Preview without Page Reload

### ISSUE THREAD

**Issue by Buffalom** [statamic/ideas#788]
Until you implemented a first-party live preview for headless sites we used a Statamic fork for our websites which included a working live preview. Instead of reloading the iFrame however, it was using `window.postMessage()` to tell the frontend to refetch the data.

After upgrading to your first-party live preview we found two pain points that reloading the page introduces:

1. If the frontend is not super-fast it is very annoying to make small changes because it might take 1 second for the changes to be reflected.
2. The scroll position is not preserved anymore.

Do you think a live preview option to tell it to use `window.postMessage()` instead would be something you would consider implementing or at least reviewing in the core.

**Comment by duncanmcclean** [comment]
The scroll position issue is a bug - see statamic/cms#5564. Unsure about the rest.

**Comment by Buffalom** [comment]
That's correct and of course, this would not solve the scroll position for the traditional way the live preview operates.
