### ISSUE TITLE
Statamic version of Mailables

### ISSUE THREAD

**Issue by edalzell** [statamic/ideas#79]
I'm building an addon right now and I'd like to take advantage of Laravel's Mailables. The issue is that standard Laravel code looks like this:
```php
return $this->from('example@example.com')
                ->view('emails.orders.shipped');
```

...and `view` assumes a Blade template.

Would be super sweet if either `view` worked magically w/ Antlers templates or there was a `->antlers()` thingie I could pass a Statamic template into.

**Comment by jasonvarga** [comment]
It does work with antlers templates. What’s the issue?

**Comment by jasonvarga** [comment]
All good then?
