### ISSUE TITLE
Disable image preset generation on upload?

### ISSUE THREAD

**Issue by klickreflex** [statamic/ideas#804]
Statamic always generates all image presets defined in `assets.image_manipulation.presets`  on upload. 
This is nice if all your images are required in any preset available,  but it can quickly blow up disk space when dealing with lots of images in many different formats, where. not every image is required in every format/preset.

I usually have a bunch of image presets that are used in some components, but many other components have custom glide settings and are only ever displayed in this variant. 

Another scenario might be using `preset 1` only in `component A`, and `preset 2` only in `component B`. So `preset 1` is never needed for an image used in `component B` and `preset 2` is never needed for an image used in `component A`, yet all defined variants are generated and stored on disk forever (or until `please glide:clear` is run).

It would be cool if we could just disable the automatic generation of presets upon upload with a config option. (`SAVE_CACHED_IMAGES` has no effect on this behavior).

**Comment by Alpenverein** [comment]
Would be interesting for me too. We had a first test of our new system with a bigger group of our future editors. When they started to write articles and uploaded images, the system became slower and slower and finally stopped working/responding. I found out, that the reason was the calculation of all the different image presets....

So: Yes please!

**Comment by klickreflex** [comment]
@jesseleite This is great news, thanks 🙏 
Once merged, where would I set `glide_warm_presets: false`? I can't find any new config in https://github.com/statamic/cms/pull/6040

**Comment by klickreflex** [comment]
Oh nice, thanks for explaining @jesseleite
