### ISSUE TITLE
Feature Request: Users Listing Screen Filters

### ISSUE THREAD

**Issue by DGeoWils** [statamic/ideas#808]
Currently on the users listing screen there is no ability to filter, only search. 

I'd like to be able to add filters similar to other listing screens.

Perhaps default filters would include role and user groups. 

I'd also like to be able to filter on any custom fields I add to the User blueprint as well.

Interestingly, in the extending docs, there is wording that would imply this is possible (https://statamic.dev/extending/query-scopes-and-filters)

> For example, an author filter might be appropriate for the entries listing but not users

Thank you!

**Comment by DGeoWils** [comment]
This was fixed with v3.3.18 - Thanks!

**Comment by jesseleite** [comment]
This is coming in v4 🎉

See: https://github.com/statamic/cms/pull/7668 and https://github.com/statamic/cms/pull/8001
