### ISSUE TITLE
Multiple Publish Dates

### ISSUE THREAD

**Issue by Buffalom** [statamic/ideas#814]
It could be useful to support a start and end publish date. For instance for a survey-page which should be available from x until y.

Perhaps even n-number of dates could be supported? Something timeline-like as follows:

- Entry is not visible.
- Date x: Entry is now visible but not listed.
- Date y: Entry is now listed.
- Date z: Entry is not visible anymore.

However, I have not yet found a good use-case for the latter. A start and end date would be sufficient for me currently.

**Comment by bernhardberger** [comment]
Theoretically you could use a DateRange for that stuff, but I just found out this bugs out at least in 3.4 and can't even be saved..
