### ISSUE TITLE
Adding #findOrFail on the different reposities

### ISSUE THREAD

**Issue by MariusSpring** [statamic/ideas#817]
Hey!

I am missing being able to use "findOrFail" one different repositories such as for taxonomy terms and collection entries. Like the "fail" method, it will take an id, however, will render the custom 404 page if the item was not found. This can be achieved pretty easily:

```php
public function findOrFail(mixed $id)
{
  if (! $entry = $this->find($id)) {
    return redirect()->to('/404', 404);
  }

  return $entry;
}
```

Then in controller:

```php
public function show(mixed $id) {
  $entry = Entry::findOrFail($id);
  
  return (new View)->template('entry')->with($entry->toAugmentedArray());
}
```

Also consider adding the following methods:

- findBySlug(mixed $slug)
- findBySlugOrFail(mixed $slug)

**Comment by duncanmcclean** [comment]
We've added the `findOrFail` method in Statamic 5, which we're hoping to release in the next few days/weeks.
