### ISSUE TITLE
Blade: add view data support/helpers for blade layout components

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/ideas#822]
I've been trying to figure out the easiest way to get $page, $site and globalsets (e.g. $social) to all of my blade components.

View composers work pretty well, as outlined in [this issue](https://github.com/statamic/cms/issues/5596). The problem with this approach is that we are re-querying global sets and it seems to be adding to page load times. Ideally I would like to be able to access the variables that were already processed and provided to the view.

With this in mind, I came up with [this solution](https://github.com/stuartcusackie/statamic-blade-view-data). It's a simple package that extracts $page, $site and all global sets from the view's data and then passes them to a singleton on the service container. This way I can access all of these variables from a facade within any component without additional queries or having to remember to pass Statamic vars to my blade layout components.

I'm just wondering if we could get similar functionality added to Statamic itself? Perhaps some additional facade functions:
- \Statamic::page()
- \Statamic::site()
- \Statamic::globalSet('handle')

UPDATE: Not only is this strategy handy for Blade Layouts, it is also gives Laravel Livewire easy access to all of the augmented data. Currently using my package for a Livewire infinite loading component.

**Comment by stuartcusackie** [comment]
I stumbled upon something when using the SeoPro addon. The $__data variable which contains all Laravel view data is fully populated when using template inheritance, but when using a blade component view the $__data variable is missing all Statamic vars.

Can we get all Statamic vars added to the $__data when in Blade components? Is the possible? I have no idea.

**Comment by jesseleite** [comment]
There's some good ideas in here. Renaming title to better reflect the purpose of this 👍

**Comment by stuartcusackie** [comment]
Perhaps a new **ViewData** Facade that initialises and accesses a singleton class similar to the way [my package](https://github.com/stuartcusackie/statamic-blade-view-data/blob/main/src/StatamicBladeViewData.php) does.

I think an ideal process would be:
- Create the singleton at an appropriate point (not sure where is best in Statamic's codebase)
- Initialise the singleton's view data once Statamic has done it's processing on $page, $site and $globals (again, I don't know where this happens)
- Add a 'ViewData' Facade to interact with the singleton.

Then everything would be accessible from anywhere like so:
```
\ViewData::page()
\ViewData::site()
\ViewData::globalSet('handle')
```

**Comment by edalzell** [comment]
I solved something similar recently @stuartcusackie by doing this:

```php
Cascade::hydrated(fn ($cascade) => $cascade->set('campaign', $campaign));
```

You could pass in whatever you want there. That is called whenever Statamic hydrates the cascade.

**Comment by jasonvarga** [comment]
You can inject the cascade into your components using a view composer.

```php
use Facades\Statamic\View\Cascade;

View::composer('components.*', fn ($view) => $view->with('cascade', Cascade::instance()->toArray()));
```
```blade
{{ $cascade['title'] }}
{{ $cascade['myglobal']->field }}
etc
```

Or you could even inject them as separate variables.

```php
View::composer('components.*', function ($view) {
    foreach (Cascade::instance()->toArray() as $key => $value) {
        $view->with($key, $value);
    }
});
```
```blade
{{ $title }}
{{ $myglobal->field }}
etc
```

**Comment by jesseleite** [comment]
>Does calling the cascade facade re-augment everything or is it all processed just the once? Just wondering about performance hits from calling the facade multiple times.

A `View\Cascade` instance is populated with request/entry/term data whenever Statamic returns a view. We use the realtime facade in core, so that instance is stored in the service container as a singleton. If an addon tries to get the `Facades\Statamic\View\Cascade::instance()` using that realtime facade, you're accessing the same instance that was already populated, so performance should not be affected 👍 

>The SEO addon had a problem with [getting the context](https://github.com/statamic/seo-pro/issues/224). That seems to be solved yesterday but I worry about similar problems from other addons.

It's more a limitation with how data is passed and scoped when using blade layout components. It took a little while to find the right fix, but `Cascade::instance()->toArray()` makes it quite painless for addon devs. Maybe we can add an example to the docs.

**Comment by stuartcusackie** [comment]
Confirmed. This seems perfect after my initial tests. I'll close this for now and come back to it if I come across any issues.
