### ISSUE TITLE
Allow Custom GraphQL Fields on all Entry Types

### ISSUE THREAD

**Issue by Buffalom** [statamic/ideas#830]
It would be nice if custom GraphQL fields could not only be added to the EntryInterface but also the type of every blueprint (e.g `Entry_Pages_Page`).

Similarly for assets, collections and so on, but the entries seem the most useful to me.

What do you think?

**Comment by jasonvarga** [comment]
You can already do this. Just pass `Entry_Pages_Page` instead of `EntryInterface`.

**Comment by Buffalom** [comment]
Ah wow, I genuinly thought I had tried that and it hadn't worked. Thanks for your reply.
