### ISSUE TITLE
Parse antlers written in field values when outputting them in a blade template

### ISSUE THREAD

**Issue by jacksleight** [statamic/ideas#833]
I couldn't figure out if this was a bug or intended behaviour, so thought here was the best place to post it.

You can use antlers in a number of text based fieldtypes by toggling the `antlers` option, but at the moment these aren't parsed when outputting them in a blade template. Maybe the assumption is you wouldn't be using antlers at all (even in field values) if you're using blade templates? But I think it could still be useful.

I had a look at the code and the fix for this might be as simple as changing this line:
https://github.com/statamic/cms/blob/0c8f5a15e829311bfa40a1fd55a190c594a2fdaa/src/Fields/Values.php#L54

To this:

```php
return $value instanceof Value ? $value->antlersValue(Antlers::parser(), []) : $value;
```

That works, but I have no idea if it might have any other implications.

Alternatively maybe field values with antlers in could be parsed in blade via an `antlers` modifier or something?

**Comment by jackmcdade** [comment]
You're not intended to use Antlers inside Blade at all. Should should be doing stuff like `{{ $now }}` or `{{ Statamic::modify($now)->format('Y') }}`.

**Comment by jacksleight** [comment]
I mean antlers in a field value (eg.text or bard), not in a template file. If for example a CP user wanted to output something dynamically in their content.

**Comment by jacksleight** [comment]
Closing as https://github.com/statamic/cms/pull/6489 provides a way to do this:

```blade
{{ Statamic::modify($page->content)->antlers() }}
```
