### ISSUE TITLE
Remove empty Bard text

### ISSUE THREAD

**Issue by aerni** [statamic/ideas#836]
It's always bothered me that Bard outputs text nodes without any content. Often, clients aren't diligent with making sure that there are no empty paragraphs anywhere in the Bard field. In reality, articles mostly end up with an empty paragraph at the bottom. This leads to extra space in the frontend layout.

My first thought was to conditionally hide the text in the template if it is empty. However, Bard augments the text to HTML, making it tricky to test if it's empty. *Hello, custom regex modifier.*

I'm suggesting removing any empty text from the Bard augmentation altogether. I've already got a working prototype. This might be a breaking change, though. So maybe introduce it as an option to the Bard field.

What are your thoughts?

**Comment by jasonvarga** [comment]
I think stripping _trailing_ empty paragraphs would be fine.

Empty paragraphs _between_ other parts could be seen as intentional.

**Comment by aerni** [comment]
I agree. Where would you strip it? Before saving so it never makes it to file or when augmenting?

**Comment by jasonvarga** [comment]
On save.

I'd think of it like a text editor that strips trailing whitespace when you hit save.

**Comment by aerni** [comment]
So you'd already want to strip it in Vue on save?

**Comment by jasonvarga** [comment]
In the `process` method on the PHP side would be fine.

**Comment by aerni** [comment]
Ok perfect. Will PR.

**Comment by aerni** [comment]
Would you accept a new Bard fieldtype option that lets the user decide if empty paragraphs should be stripped? Like `remove_empty_paragraphs: true` or something. It would keep the current behavior by default, but you can opt-in to remove all empty paragraphs. Including paragraphs at the beginning, between, and the end.

Or we could simply strip empty paragraphs at the end by default. And add the option to strip all paragraphs if a user wants to.

**Comment by jasonvarga** [comment]
How about `remove_empty_paragraphs` with values of `false` (do nothing), `true` (remove all), and `trim` (just the first and last)

The config field could be a select with those values, and with cast booleans. Like here: 

https://github.com/statamic/cms/blob/7ad1b343896d935b0ef3eec770dcbfa47f60fbe0/src/Http/Controllers/CP/Fields/FieldsController.php#L119-L124

**Comment by aerni** [comment]
You reading my thoughts. Creepy. I was just going to suggest this. Will PR.
