### ISSUE TITLE
Delete attached files when form entry gets deleted

### ISSUE THREAD

**Issue by wm-simon** [statamic/ideas#837]
When you have a form with attached files, they get saved to the assets. That's fine, because now you can open the entry in the cp and see the attached files as well. 

When you delete the form entry, the attached files are not deleted and it is not possible to make a difference between files from deleted and not deleted entries. It would be good to have the possibility to change this, that the attached files gets deleted with the form entry.

**Comment by jesseleite** [comment]
Neat idea, though we'd have to be careful with this. Since assets can technically be used and reused anywhere, we'd probably need a way to check if the asset is used anywhere else before deleting, offering a confirmation message, etc.

**Comment by duncanmcclean** [comment]
This will be addressed in Statamic v5. You'll be able to use the "Files" fieldtype for file uploads which shouldn't be stored on the server.
