### ISSUE TITLE
Add selectable forms config option

### ISSUE THREAD

**Issue by aerni** [statamic/ideas#841]
I've got a replicator with a form set that lets my client choose the form to display on any given page. However, certain forms shouldn't be selectable. It would be great if we could optionally add the forms that should be selectable to the form field config. Similar to how you can add options to a select field.

**Comment by jasonvarga** [comment]
Couldn't a simple `select` field work just as well here? It stands to reason that if you're trying to exclude forms, you could just as easily list the ones you want selectable.

**Comment by aerni** [comment]
Yeah, you're right. Sure. That's what I'm doing right now. I just thought it might be nicer to still have the dynamic nature of the form fieldtype. But I guess it would be more of a `disallowed` options list and show all other forms except the ones selected.

**Comment by aerni** [comment]
Ah no, I remember the issue with the select field. It's that it doesn't augment to a form. And I need augmentation on the frontend.

**Comment by jasonvarga** [comment]
Ah fair enough

**Comment by morhi** [comment]
maybe it would be helpful for other relationship fields as well, that you can mark certain items (like forms or collections) as not selectable or as hidden?

**Comment by ryanmitchell** [comment]
Maybe you could add query_scopes (https://github.com/statamic/cms/pull/8456/files#diff-65991befe757c3572bc64584dd243cf0f210d15d322db0bce20731aebdbfb219) to the form field type now its supported elsewhere?
