### ISSUE TITLE
Ability to reorder terms within the Terms fieldtype

### ISSUE THREAD

**Issue by jacksleight** [statamic/ideas#844]
Although you can't sort taxonomy terms globally, when you add them to an entry using the Terms fieldtype they are stored in the order you add them, which is useful if you want a convention where the first one is considered the "primary" term for example.

However, if you've added a bunch of terms and then change your mind about the primary one at the moment you'd have to remove them all and then re-add to put them in a new order. I'd be great if you could simply drag and drop the badge list in the field UI.

**Comment by jasonvarga** [comment]
That just feels like a bug. I think they were draggable at some point. Can you open an issue on cms instead?

PS. As a workaround, if you edit the blueprint field to use the stack selector instead, it'll be draggable.

**Comment by jacksleight** [comment]
Turns out it's not even a bug!

You can do it already, it's just that there's no cursor to indicate you can move them so I hadn't tried 😂 . Sorry about that.

I could PR a quick cursor class addition?
