### ISSUE TITLE
Add an `EntryLoaded` event

### ISSUE THREAD

**Issue by jacksleight** [statamic/ideas#851]
I'd like to add some supplement data to an entry every time it's loaded, and this involves reading some values from the entry first. The `EntryBlueprintFound` event kind of works as a workaround for this, but you can only read raw values from the entry during that event, if you try to get augmented values it creates an infinite loop.

A separate `EntryLoaded` event would be really useful.

**Comment by jasonvarga** [comment]
You should find this PR interesting. It does what you want. https://github.com/statamic/cms/pull/6179

**Comment by jacksleight** [comment]
Yeah! I guess that'd allow for the same end result, and would probably be a cleaner solution overall.

Only reason I thought an event might be handy is I only want to compute the value once (it's output multiple times), but actually it'd be pretty trivial to use blink or something in the computed callback.
