### ISSUE TITLE
Show blueprint badge in tree view

### ISSUE THREAD

**Issue by FrittenKeeZ** [statamic/ideas#854]
It would be really nice if blueprint would be shown as a badge when viewing a collection tree, so you know what kind of page you're dealing with.
Similarly, it would be nice if the blueprint was shown by default in the top of the sidebar, unless you've manually added a field for it in the blueprint.

**Comment by mmodler** [comment]
Here my idea how it could look like (from my duplicate issue):

![grafik](https://github.com/statamic/ideas/assets/1906217/efd16d46-96fc-4c6e-b6d9-e824e01ca19b)

I would only show blueprint titles if there are two ore more blueprints. And we can add this information to the page create/edit view, too.

A layout alternative would be the style of entries fieldtype:
![grafik](https://github.com/statamic/ideas/assets/1906217/fc6f2d72-df8c-4f5a-bf77-c97393fb9937)

I like to hear your thoughts before working on it seriously. Thanks!

**Comment by mmodler** [comment]
@FrittenKeeZ See https://github.com/statamic/cms/pull/9413
