### ISSUE TITLE
Add single asset/folder actions to grid view

### ISSUE THREAD

**Issue by jacksleight** [statamic/ideas#859]
It'd be useful if you could access the single asset/folder actions from the grid view. Not all actions are available in bulk mode, and you can't access folder actions at all from grid view, so you have to toggle to list view to rename/delete folders.

I started playing around with a possible solution, can PR it:

https://user-images.githubusercontent.com/126740/189182683-3d158edc-166a-4b56-b35e-cd512a3b5efc.mp4

You can still select the items as normal.

**Comment by jasonvarga** [comment]
Makes perfect sense, and what you screencasted looks like what we'd probably do.

**Comment by jacksleight** [comment]
Great! I'll do a PR.
