### ISSUE TITLE
Let the starter kit installer run custom commands

### ISSUE THREAD

**Issue by robdekort** [statamic/ideas#863]
I would love it if I can run some custom commands after my starter kit installed. The logic I could do myself. But I'd need a place to hook into the installer. I'm thinking of stuff like:

- Do you want to overwrite your `.env` with the example from this Starter Kit?
- Do you want to star the repo?
- Config: do you want to include users in git?
- Config: do you want to include form submissions in git?

**Comment by ryanmitchell** [comment]
This would be great. Maybe specifying a new key in the YAML which references a class and method? eg

`after_install_hook: \App\Hooks\MyHook::handle`

Then that class would get the console instance as an argument so it could continue to request input etc.

**Comment by robdekort** [comment]
That sounds perfect!

**Comment by ryanmitchell** [comment]
@robdekort heres a draft PR - let me know what you think: https://github.com/statamic/cms/pull/6757

**Comment by robdekort** [comment]
That is amazing. I'd love to check it out. It'll be after the weekend though.
