### ISSUE TITLE
No grouping in form blueprints possible

### ISSUE THREAD

**Issue by globalexport** [statamic/ideas#864]
There is no way to group elements of a form at the moment. 

Why is this important? 
It is sometimes necessary to logically break a form into different segments. 
As an example, it could be helpful to explain a group of form elements altogether.
Another useful case would be the creation of a stepped form wizard.

**Comment by ryanmitchell** [comment]
You can add `Statamic\Fieldtypes\Section::makeSelectableInForms();` in your AppServiceProvider.php file, which then makes the section field type available to forms, which you can use to split or group form fields.

You can call the same method on any field type to make it available to form blueprints.

**Comment by globalexport** [comment]
Cool, I did not know this. Is this documented somewhere?

**Comment by ryanmitchell** [comment]
Yeah it is: https://statamic.dev/forms#the-blueprint

**Comment by globalexport** [comment]
Thank you! My bad. :)
