### ISSUE TITLE
Toggle visibility of Replicator/Bard Sets

### ISSUE THREAD

**Issue by samburgers** [statamic/ideas#867]
Would be great to have the ability to control replicator set visibility with a show/hide toggle. When toggled off, editors would no longer be able to create new sets, but could still see and edit existing sets. This would be very useful for deprecating legacy sets while still having them in the content flow.

<img width="751" alt="Screen Shot 2022-09-19 at 8 30 20 am" src="https://user-images.githubusercontent.com/1476939/190930625-a7670726-998d-4b14-8ed1-6b0dfb5ff874.png">

**Comment by duncanmcclean** [comment]
Another thing I've needed recently (slightly related to this) would be adding conditionals for Replicator/Bard fields....

We want to use the same 'content builder' fieldset everywhere but there's cases where we only want one of the blocks to be useable on a certain page(s).

**Comment by j3ll3yfi5h** [comment]
Or sets, which should only be available once...
