### ISSUE TITLE
Add a `{{ glide:data }}` tag that returns the generated image as a data URI

### ISSUE THREAD

**Issue by jacksleight** [statamic/ideas#869]
I have a glide preset that generates a very small (2px x 2px gif) version of each uploaded image, which I would like to embed in the page HTML as a data URI, to be used as a placeholder while the image is loading. Something like:

```html
<img style="background-image: url('data:image/gif;base64,R0lGODlh...')"
```

At the moment it's not possible to get the image as a data URI from the glide tag, but I think this would be a useful addition. For example:
```antlers
{{ glide:data src="octopus.jpg" preset="placeholder" }}
```
```
data:image/gif;base64,R0lGODlh...
```

I've written an implementation in a custom tag that works in theory, but `generateImage()` is private so it doesn't work in reality, and I'd rather not duplicate all that code:

```php
class Glide extends StatamicGlide
{
    public function data()
    {
        $item = $this->params->get(['src', 'id', 'path']);

        return $this->generateGlideDataUri($item);
    }

    private function generateGlideDataUri($item)
    {
        $path = $this->generateImage($item);
        $cache = GlideManager::cacheDisk();

        try {
            $source = $cache->read($path);

            return 'data:'.$cache->mimeType($path).';base64,'.base64_encode($source);
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
        }
    }
}

```

**Comment by jasonvarga** [comment]
Cool idea.
