### ISSUE TITLE
Ability to publish the login view to local app so you can style it all custom like

### ISSUE THREAD

**Issue by jackmcdade** [statamic/ideas#87]

**Comment by skylennard** [comment]
Would this also solve my need to hide "...or login with email", from https://github.com/statamic/cms/pull/3013#issuecomment-747645972?

🍻

**Comment by duncanmcclean** [comment]
You should be able to do this by adding your own stylesheet that'll be loaded inside the CP (and it's auth pages). There's docs on that over here: https://statamic.dev/extending/control-panel#adding-css-and-js-assets

**Comment by skylennard** [comment]
Rad, thx x 10^6 Duncan!

**Comment by skylennard** [comment]
PS. I thought, to be sure, that it was going to be possible to disable the ability to do this functionality, though... as a security footprint reduction method? Just CSS'ing it out might keep out the regular users, but maybe not the pesky burglars.

**Comment by jasonvarga** [comment]
You can use CSS to hide things - you can't really add things. So, it's fine 😄 We can't stop everything.

**Comment by duncanmcclean** [comment]
Can't you already do this by creating the view in `resources/views/vendor/statamic/cms/whatever-it-is`, copy in the existing code and start changing things? Maybe I'm misunderstanding this issue 😅

**Comment by jonassiewertsen** [comment]
The blog needs a restyling, but besides that, you'll find a short blogpost on how you already can customize your views as you do like them:

https://jonassiewertsen.com/blog/how-to-customize-statamic-views
