### ISSUE TITLE
Index form fields array by handle

### ISSUE THREAD

**Issue by jacksleight** [statamic/ideas#872]
Would it cause any problems if the augmented form fields array was indexed by handle instead of numerically?

I've seen a couple of people ask how to retrieve a specific field's `display`, `instructions` or other config values when they're _not_ looping through the array, and at the moment I don't think(?) it's that straightforward.

This is obviously risky as order may change:

```antlers
{{ fields:2:display }}
```

This works but is pretty verbose:

```antlers
{{ fields | where:handle:email }}
    {{ display }}
{{ /fields }}
```

This would be much nicer:

```antlers
{{ fields:email:display }}
```

**Comment by jacksleight** [comment]
Doh! 🤦‍♂️

Is there a better way?

Maybe a `key_by` modifier would be useful. Then if people aren't looping the fields they could do:

```antlers
{{ fields_assoc: fields | key_by:handle }}
```
```antlers
{{ fields_assoc:email:display }}
```

**Comment by jasonvarga** [comment]
Good idea. We can whip up a simple modifier (I've already just tested that locally)

```antlers
{{ rekeyed = fields | key_by('handle') }}

{{ rekeyed:second:display }}
```

**Comment by jasonvarga** [comment]
See https://github.com/statamic/cms/pull/6763
