### ISSUE TITLE
A way to set action field default values based on the items selected

### ISSUE THREAD

**Issue by jacksleight** [statamic/ideas#881]
When specifying action fields it can be useful to know what items you're working with, in order to set default values on the fields. But at the moment the `Action::fieldItems()` method doesn't have any access to this information.

I've run into this issue myself with a custom action, but I think it also prevents https://github.com/statamic/ideas/issues/337 from being possible, which would be a really nice enhancement.

Possible approaches could include:

* Pass `$items` to `fieldItems()`
* Include `$items` in the action context
* Add an `autoApply($items)` method like filters have, where you can set the field defaults
* Something else?

**Comment by jasonvarga** [comment]
This will be available in 3.4.

Within fieldItems you can use $this->items.
