### ISSUE TITLE
Add laravel-vite asset support to the Vite tag

### ISSUE THREAD

**Issue by joshkrz** [statamic/ideas#882]
The Vite tag currently dosen't support Laravel Vite assets as shown here: https://laravel.com/docs/9.x/vite#blade-processing-static-assets.

Proposed Usage
`<img src="{{ vite asset='resources/images/logo.png' }}">`

**Comment by duncanmcclean** [comment]
Hey!

It looks like this has been implemented recently - see statamic/cms#7477.
