### ISSUE TITLE
Make assets from sendet forms openable

### ISSUE THREAD

**Issue by wm-simon** [statamic/ideas#887]
The assets from sendet forms could not be opened right know. You have to go the assets and search for the files. That's to complicated.
It would be nice, if assets could be open directly from the form entry.

![image](https://user-images.githubusercontent.com/3351449/196877949-3473d36d-bc57-4c11-bf67-246cff97211f.png)

**Comment by duncanmcclean** [comment]
Related: statamic/cms#6501
