### ISSUE TITLE
Back to top button on CP Edit forms

### ISSUE THREAD

**Issue by mikemartin** [statamic/ideas#894]
I've thought about making the sidebar sticky but perhaps the most elegant solution would be a super simple back to top button.
 
 To take it a step further, maybe a combo button with:
 1. Save (Most users want to scroll to top to save)
 2. Back to top

<img width="1594" alt="Screen Shot 2022-10-27 at 8 58 47 pm" src="https://user-images.githubusercontent.com/414211/198256850-15165998-2b8c-403a-8eda-dcb7d98a5067.png">

**Comment by jackmcdade** [comment]
Got a different, better idea in the works :)
