### ISSUE TITLE
Asset grid mode drag and drop move

### ISSUE THREAD

**Issue by gabikasb** [statamic/ideas#899]
Authoring experience would skyrocket by making use of [drag and drop API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API) in `js/components/assets/Browser/Browser.vue` (?).
IMHO no Vue library necessary

**Comment by jasonvarga** [comment]
Drag and drop to do what?

**Comment by jackmcdade** [comment]
Closing this as the idea or benefit isn't very clear. Feel free to reopen with more info anytime!
