### ISSUE TITLE
Commands: make:addon should generate more boilerplate

### ISSUE THREAD

**Issue by jasonvarga** [statamic/ideas#90]
- `resources/js/addonname.js`
- `webpack.mix.js` compiling addonname.js into dist/js
- `package.json` with just enough to compile assets
- The `ServiceProvider`'s should have a `$scripts` array pointing at addonname.js
- `.gitignore` with `node_modules` and `vendor`

**Comment by damcclean** [comment]
I wonder if there could also be a parameter on `php please make:addon` to copy over a basic PHPUnit & Testbench test suite. 

Although, this may want to be implemented after/alongside this issue to improve the overall state of testing for addons, statamic/cms#1184.
