### ISSUE TITLE
Ability to create a new entry from a publish form

### ISSUE THREAD

**Issue by jacksleight** [statamic/ideas#900]
When you're scaffolding out a new site structure and creating a whole load of pages in one go it would be handy to be able to create new entries directly from the open entry's publish form.

The Blueprint could default to the current entry's blueprint and you could have options for:

* New Page (added at the collection root)
* New Child Page
* New Sibling Page

**Comment by jackmcdade** [comment]
You can kinda already do this, and can set the parent page as well. I kinda hesitate to have a whole pile of options in this dropdown. 

Maybe a scaffolding option from the nav would be better. We used to have this in v2 I think, where you would be able to create new entries without hitting the edit form and just keep slinging.
