### ISSUE TITLE
Dynamic Asset File Path

### ISSUE THREAD

**Issue by schwartzmj** [statamic/ideas#901]
I'm looking to save certain uploaded files into a dynamic path, probably WordPress style e.g. `/{currentYear}/{currentMonth}/filename.pdf` or even `/{taxonomy-slug}/filename.pdf`.

I've tested listening for various Entry and Asset events, but I'm not finding a way to do it this way.

I propose allowing us to use Antlers to set a dynamic filepath for an Asset field, similar to how Titles and Routes work when setting up a collection.

**Comment by jasonvarga** [comment]
Duplicate of #725
