### ISSUE TITLE
Contextual keyword snippets in search results

### ISSUE THREAD

**Issue by jacksleight** [statamic/ideas#913]
Something @robdekort and I were just chatting about was the ability to show contextual keyword snippets in search results, where you show the matched word(s) plus a few either side. This kinda thing (search for "lorem"):

> **Lorem** ipsum dolor sit amet, consectetur adipiscing elit. ... Etiam bibendum **lorem** nec tempus sollicitudin. ... Sed in dapibus **lorem**. ... Nunc turpis ipsum, bibendum quis sodales sed, ullamcorper et **lorem**. Donec et metus hendrerit, interdum elit ut, dignissim dui.

This is something that Algolia (and I think Meilisearch) can do, but it's not currently possible with the internal Comb driver.

I had a look and in principle I think it could be fairly simple to implement, it's basically just running an extra regex against the searched text and then returning a list of matches along with each result:

![Screenshot 2022-11-23 at 14 25 14](https://user-images.githubusercontent.com/126740/203577099-e6b70090-acc8-4b11-a0c5-6546b6d66449.png)

You _could_ do this manually when rendering the results, but that would involve scanning through all the content a second time, it would be more efficient to do it inside the search driver.

Could then be used with the `mark` modifier to highlight the matches.

**Comment by jackmcdade** [comment]
I like it!

**Comment by jasonvarga** [comment]
Algolia does this (like you said) and I _think_ will already just work if you use the Algolia driver.
