### ISSUE TITLE
Order asset containers

### ISSUE THREAD

**Issue by robdekort** [statamic/ideas#924]
I'd love the ability to order asset containers (based on most used for example). The yaml files could have simple key called `order` to accomplish this.

**Comment by jacksleight** [comment]
I've always thought the same thing about collections, and I'm guessing the upcoming nav customiser might allow this?

If so perhaps the container tabs could match the nav order?

**Comment by robdekort** [comment]
Ohhhhh I didn't think of that but it would make sense to me if it would be based on that feature for sure.
