### ISSUE TITLE
Conditional required fields

### ISSUE THREAD

**Issue by jasonbradberry** [statamic/ideas#927]
It would be great to be able to set any conditionally hidden fields to 'required', and have the page validate when they're hidden, regardless of whether they are empty.

An example use case:

I have a fieldset for adding a button to a section, with a toggle to show/hide the button fields conditionally. I'd like to set the URL field for the button to be required to avoid any buttons being added with empty links. But the button itself is not always required.

**Comment by jasonvarga** [comment]
Check out required_with https://laravel.com/docs/9.x/validation#rule-required-with
