### ISSUE TITLE
Enable smartypants modifier across all suitable fieldtypes

### ISSUE THREAD

**Issue by wesort** [statamic/ideas#930]
It seems that the `smartypants` modifier doesn't work on every fieldtype ([as discussed on Discord](https://discord.com/channels/489818810157891584/489819906540568593/1013721256702509097)). For example, it's fine on `markdown` fields but not `bard`.

Or better yet, to set this as a system-wide default (which I thought was a default in v2??).

Or can anyone clarify what fields it currently works on and I'll update the docs:
https://statamic.dev/modifiers/smartypants.

**Comment by jasonvarga** [comment]
Use the modifier. It works on any text.

`{{ bard }} ... {{ text | smartypants }} ... {{ /bard }}`

If you need it to be baked in further, we'll review a PR but I don't think it needs to be in all fieldtypes.

**Comment by wesort** [comment]
Ok, thanks @jasonvarga.  It's still not working for me so perhaps I'm doing something wrong. I'll either figure it out or add some more context.
