### ISSUE TITLE
Get Bard content reading_time

### ISSUE THREAD

**Issue by jimblue** [statamic/ideas#94]
In Statamic 2 I was doing:

```twig
{{ bard_field | flatten | join | strip_tags | read_time }}
```

But in Statamic 3 the data structure has change and it's not working anymore.

Also I've read in the doc that Bard have an option to show estimated reading time at the bottom of the field. It is very nice and it could nice to have access to this data in the frontend with Antlers.

**Comment by goellner** [comment]
would need that in the content API too :)

**Comment by jimblue** [comment]
> would need that in the content API too :)

indeed great idea @goellner

**Comment by jacksleight** [comment]
FYI this is now a bit easier with the [bard_text](https://statamic.dev/modifiers/bard_text) modifier:

```antlers
{{ content | raw | bard_text | read_time }}
```

**Comment by hlorofos** [comment]
This should go to the instruction! Thanks @jacksleight
