### ISSUE TITLE
Better identification of the latest Statamic version any locale has been updated for

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/ideas#944]
I'de like the idea to display the latest version any locale has been updated for, as some of them are lacking active development.  Couldn't this be displayed right into the new preference menu where the locale is choosen?  Constraint: how to require the developper to precise the statamic version he/she has tested is work on?

**Comment by joshuablum** [comment]
Hey @ebeauchamps,

Could you please elaborate on this or rephrase it? Not sure I get it 100%.

**Comment by AndreasSchantl** [comment]
I think he means to give localisations a version number as well. For example: If a locale hasn't been updated since statamic 3.1. (missing translations), show the info, that the locale is not up to date.
