### ISSUE TITLE
Uploading assets with the same filename

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/ideas#945]
I'm just looking at the asset container for one of my sites which was only built about 1 year ago. I'm seeing multiple copies of a lot of images, ten copies for a single image in some cases. It doesn't look good.

I assume this is happening because the content managers are re-uploading the same image from their local machine every time they replace an asset.

Can this be improved? I shudder to think what the asset container will look like in another couple of years.

I'm thinking something like:
- On upload of new file
- Check if another file with the same name exists in the same folder
- If it does give the options to: 
  - use existing file
  - upload new file and rename
- show new filename vs old filename, new thumbnail vs old thumbnail, new filesize vs old filesize - So that the user can make an informed decision.

Thanks!

**Comment by jasonvarga** [comment]
You should instruct your client to use "Replace Asset" instead of just uploading the same thing over and over.

Although I'm not sure why they would be uploading the exact same file multiple times.

**Comment by stuartcusackie** [comment]
> You should instruct your client to use "Replace Asset" instead of just uploading the same thing over and over.
> 
> Although I'm not sure why they would be uploading the exact same file multiple times.

I don't think they are 'replacing' images, but rather uploading the same image to multiple entries. In this case we have a "locations" collection and the same image is being upload for each location, when it already exists in the container. The client doesn't understand that they can re-use the same asset. They just keep re-uploading it.

I don't have the resources to train my clients so I was thinking this would be a fool-proof solution.

**Comment by jasonvarga** [comment]
Gotcha, that makes more sense.

**Comment by daun** [comment]
@jasonvarga I think this one can be closed now that the new UI for duplicate asset uploads has landed?
