### ISSUE TITLE
Bard fieldtype - Generate ID attributes in headings?

### ISSUE THREAD

**Issue by stephenmeehanuk** [statamic/ideas#946]
It'd be useful to have a way to generate ID attributes in bard headings

We can do this to generate a table of contents (found this in the Statamic Discord), 

```
{{ headings = test_bard | raw | bard_items |
where:type:heading }}
<ul>
    {{ headings }}
    <li>
        <a href="#{{ content | bard_text | slugify | safe_truncate:30}}">{{ content | bard_text }}</a>
    </li>
    {{ /headings }}
</ul>
```

But the anchors don't work, because the headings in the bard fieldtype don't have ID attributes.

Could this option be added to a future release?

**Comment by jasonvarga** [comment]
Check out https://statamic.com/addons/jacksleight/bard-mutator

One of the examples are how to add ids to headings:

![CleanShot 2023-02-02 at 11 46 43](https://user-images.githubusercontent.com/105211/216387987-4c62aab0-e519-470c-91d8-720d3ffb7735.png)
