### ISSUE TITLE
Option for {{ glide }} to output seo-friendly final file-name

### ISSUE THREAD

**Issue by delz-dev** [statamic/ideas#947]
When generating path-cached images with glide, the url mostly looks like this example:

`https://whatever.com/img/containers/assets/04_aktuell/blogs/header_00068.jpg/56ce2301be602a8096511de3fcb175fc.webp`

All of my SEO-tools and even Google Seach Console are complaining about those URL's.

Wouldn't it be nice to have an opt-in option to have shorter file names generated? Example:

`https://whatever.com/img/containers/assets/04_aktuell/blogs/header_00068.jpg/header_00068_[5 chars ID].webp`

Kind of a naming option inside glide `{{ glide:src name='md5' }}` or shorter `{{ glide:src name='seo' }}` or something like this? `name='md5'`would be the standard-setting so that nothing older will break …

**Comment by stuartcusackie** [comment]
This is also covered by ahinkle's answer [here](https://github.com/statamic/cms/issues/2814#issuecomment-1275196956)

An overhaul to Glide filenames would be nice for both cached and non-cached images. Personally I think it should be the default, with opt-out if required, though I don't see why anyone would want to keep the current filename structure.

**Comment by jasonvarga** [comment]
The default behavior in v5 is to move the "hashes" into a folder and the filename be original.

e.g. /img/the-hash/readable-filename.jpg
