### ISSUE TITLE
[4.x] Ability to disable full-screen mode for Grid fieldtype

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/ideas#963]
It would be great if it was possible to disable the new full-screen mode that's been added to the Grid fieldtype in Statamic 4.

## Use case

I use the Grid fieldtype in my Simple Commerce addon to display line items. I'd like to disable the full-screen mode for this use case.

<img width="776" alt="image" src="https://user-images.githubusercontent.com/19637309/227673970-4d71601f-2d7b-42ee-a36d-6723255ba588.png">

**Comment by jasonvarga** [comment]
That button just dangling there in the middle of nowhere is not the intended UI, by the way.

**Comment by jackmcdade** [comment]
Tagged the wrong issue w/ the commit message, but resolved in https://github.com/statamic/cms/commit/0ce8866da6081089aa052ced0a05a06d198b40ab
