### ISSUE TITLE
Replacing an Asset with an existing filename appends timestamp to new filename

### ISSUE THREAD

**Issue by motion-work** [statamic/ideas#972]
The problem occurs when I want to replace old documents with new documents (with the identical file name). The filename is always supplemented with a sequence of numbers after the replacement and I have to rename the documents in a 2nd step (see screenshots).

Since I want to replace this file, I find it an unnecessary extra step. Especially when I want to replace multiple files.

The file name should remain unchanged.

![example_filename](https://user-images.githubusercontent.com/11538632/229055087-546abe74-5a43-443f-9d4e-114bd26b0ef1.png)

**Comment by AndreasSchantl** [comment]
Open up an issue over at ``statamic/cms``. That's not an idea.

**Comment by motion-work** [comment]
Done https://github.com/statamic/cms/issues/7808
