### ISSUE TITLE
Date picker to be localised

### ISSUE THREAD

**Issue by wesort** [statamic/ideas#98]
Could the date picker be aligned with local preference in terms of which day a week starts on. Here in the UK, and many other countries, a week starts on a Monday but the picker is stuck with the US week starting on a Monday. 

Perhaps an option of `first_day_of_week` or `week_starts_on`? I presume this should accept a number  [1-7] aligned with [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601#Week_dates): _[D] is the weekday number, from 1 through 7, beginning with Monday and ending with Sunday._

**Current date picker:**
![image](https://user-images.githubusercontent.com/3920126/75671314-5cbce100-5c76-11ea-83ef-2dabe1731643.png)

**Comment by jackmcdade** [comment]
This is actually already supported by setting your `app.locale` to `en-GB`.

In `config/app.php` just set `'locale' => 'en-GB',` and it'll start from Monday :)
