### ISSUE TITLE
DropdownItems should support HTTP verbs

### ISSUE THREAD

**Issue by edalzell** [statamic/ideas#99]
Making the Charge CP and I want to allow folks to cancel a subscription. On the front end this is done with a `DELETE` method on a form, as that best maps to the standard Laravel CRUD.

Right now, `DropdownItem`s only allow a normal link, i.e. a `GET` request, which means that instead of keep the route URL constant and changing the verb, we have to use a different url for each action, i.e. `/subscription/{name}/delete` as a `GET` route.

Would be great if we could pass in a URL and a `method` and have Statamic magically call it properly.

http://www.reactiongifs.com/r/mgc.gif

**Comment by jesseleite** [comment]
The reason why we haven't supported this in core is because wherever we need to delete an item via dropdown selection, we open a confirmation modal and handle the DELETE request through our  `<resource-deleter>` component.  Example...

```js
<dropdown-list>
    <dropdown-item :text="__('Edit')" :redirect="form.edit_url" />
    <dropdown-item
        v-if="form.deleteable"
        :text="__('Delete')"
        class="warning"
        @click="$refs[`deleter_${form.id}`].confirm()"
    >
        <resource-deleter
            :ref="`deleter_${form.id}`"
            :resource="form"
            @deleted="removeRow(form)">
        </resource-deleter>
    </dropdown-item>
</dropdown-list>
```

Do you plan on setting up a confirmation modal?  If so, you wouldn't want the delete request happening directly off a dropdown click anyway.

**Comment by jasonvarga** [comment]
You can also just use the click event to do whatever you want.

`<dropdown-item @click="yourOwnMethodThatUsesAxiosToDoDeleteRequest">`

**Comment by jesseleite** [comment]
^ 100% that.  Jason++ for getting straight to the point.

**Comment by edalzell** [comment]
ah I see, perfect. v3 is some much more capable, gonna be a bit until I stop asking ignorant questions.

Thanks to you both for the explanation and suggestions, both would work for me, I'll see which one I like better for this case.

**Comment by jesseleite** [comment]
Saul Goodman! 🤘

**Comment by edalzell** [comment]
@jesseleite @jasonvarga is that confirmation modal available to us? If so, what component?

**Comment by edalzell** [comment]
In my instance I'm not in a Vue component (plain ol' Blade), is this still usable?

**Comment by jasonvarga** [comment]
The confirmation-modal component. You need to be in a vue component, how else would you open it and do stuff once confirmed?

**Comment by edalzell** [comment]
Ya I guess...I'm in a custom utility so hadn't made a component for it, yet. Guess now's the time.

Thanks for the pointer.
