### ISSUE TITLE
[Marketing Site] Update source for `Hacked Websites Report` by sucuri.net

### ISSUE THREAD

**Issue by adevade** [statamic/ideas#993]
On the front page of statamic.com, if you choose the business adventure there's a link to a report from 2019. The report from 2022 sees an increase from 94% to 96%.

![image](https://github.com/statamic/ideas/assets/1066486/a51c9007-06aa-4889-9b7b-2775ddf6d2f1)

https://sucuri.net/reports/2019-hacked-website-report/
https://sucuri.net/reports/2022-hacked-website-report/

**Comment by jackmcdade** [comment]
Nice one, thank you!

**Comment by adevade** [comment]
[Updated](https://statamic.com/#:~:text=And%20then%20there%27s%20security.)! 👍
