### ISSUE TITLE
CP Nav: Ability to customise icons

### ISSUE THREAD

**Issue by duncanmcclean** [statamic/ideas#995]
Alongside customising the name of CP Nav Items, it would nice if you could also customise the icon used. 

For example: I have these two collections, Pages & Posts. It would be great if these could have different icons to differentiate them.

<img width="198" alt="image" src="https://github.com/statamic/ideas/assets/19637309/90a6f5f7-554a-496d-ac12-4815c0dde677">

**Comment by jasonvarga** [comment]
This is happening in https://github.com/statamic/cms/pull/8023
