### ISSUE TITLE
Assets organised by folders

### ISSUE THREAD

**Issue by binoclard** [statamic/ideas#997]
I tend to build "portfolios" sites, for artists, architects, etc. and generally they have a bunch of Collections, with a lot of various Entries, each with a lot of images, and it becomes messy real quick without folders.

It would be really great to have the ability to automatically create a folder for each Entry, to keep assets separated and organised.

Basically what the "Assets organized" add-on was doing for v2: https://statamic.com/addons/goellner/assets-organized.

**Comment by jasonvarga** [comment]
Duplicate of #725
